#!/usr/bin/env python3
"""
composite_aspect.py — composer for composite-chart aspects (the relationship's own dynamics).

Unlike synastry (how two people interact), a composite aspect describes what the relationship
IS. Structure matches the natal-aspect surface: lived experience (two concrete ways the dynamic
shows up in the bond), then guidance, then the technical aspect as a footer. Marie's plain
full-form voice; addresses the couple; planet-accurate; no em dashes.
"""
DISP = {"sun":"the Sun","moon":"the Moon","mercury":"Mercury","venus":"Venus","mars":"Mars",
        "jupiter":"Jupiter","saturn":"Saturn","uranus":"Uranus","neptune":"Neptune","pluto":"Pluto"}
ASPECT_WORD = {"conjunction":"conjunct","square":"square","opposition":"opposite",
               "trine":"trine","sextile":"sextile"}
ASPECT_VERB = {"conjunction":"conjuncts","square":"squares","opposition":"opposes",
               "trine":"trines","sextile":"sextiles"}
VALENCE = {"conjunction":"fused","trine":"flowing","sextile":"flowing","square":"friction","opposition":"friction"}
OUTER_SLOW = {"uranus", "neptune", "pluto"}

# Each pair: theme (metadata) + fused / flowing / friction lived-experience passages + guidance.
PAIRS = {
 "moon-sun":{"theme":"how the relationship's shared purpose fits with what it needs emotionally",
   "friction":"What the two of you are building and what the relationship needs to feel secure do not always line up. You may commit to a shared direction, then find it asks more of the closeness between you than you expected. Or you may protect the comfort you already have and later feel the relationship has quietly stopped moving.",
   "fused":"The relationship's purpose and its emotional needs are closely joined, so what you are building together tends to be the same thing that makes you both feel safe. This gives the bond a whole-hearted unity, though it can make it hard for either of you to step back and see it clearly.",
   "flowing":"The relationship's direction and its emotional needs tend to support each other, so pursuing your shared goals rarely costs you the comfort between you. You can move forward together and still feel at home in the bond.",
   "navigation":"When you decide something as a couple, weigh both where the relationship is headed and what it will need emotionally to hold together on the way."},
 "mercury-sun":{"theme":"how the relationship thinks, talks, and understands itself",
   "fused":"The relationship's sense of itself and the way the two of you communicate are closely tied, so talking things through is central to who you are as a couple. This makes the bond articulate and self-aware, though it can circle its own thoughts or take a difference of opinion too personally.",
   "flowing":"Self-expression and thinking support each other between you, so you tend to understand the relationship and can put it into words with ease.",
   "friction":"How the relationship sees itself and how you talk about it can pull apart, so misunderstandings about what you each meant may need patience.",
   "navigation":"Say plainly what the relationship is to each of you, and let understanding catch up to feeling."},
 "sun-venus":{"theme":"warmth, affection, and pleasure at the heart of the bond",
   "fused":"Affection sits right at the core of what the two of you are, so warmth, pleasure, and enjoying each other are central to the relationship's identity. This makes the bond naturally loving, though it can lean on things staying pleasant and shy away from what is not.",
   "flowing":"Love and ease move through the relationship, so enjoying each other and appreciating what you have together tends to come naturally.",
   "friction":"Affection and the relationship's sense of itself can compete, so vanity, indulgence, or hurt feelings may need attention before they settle.",
   "navigation":"Keep the warmth flowing between you, and let honesty sit beside the pleasure rather than behind it."},
 "mars-sun":{"theme":"the relationship's drive, energy, and capacity to act together",
   "fused":"The relationship runs hot and active, so the two of you tend to do a great deal together and rarely sit still for long. That energy is a real asset, though it can also mean friction, competition, or a pace that wears you both out.",
   "flowing":"You move and act well together, so your shared energy tends to motivate rather than clash, and you can get things done as a pair.",
   "friction":"Drive and ego can collide between you, so competition or conflict may flare, and the same energy that moves the relationship can turn it against itself.",
   "navigation":"Aim your shared energy at goals you both actually want, so it builds the relationship rather than burning it."},
 "saturn-sun":{"theme":"the seriousness, commitment, and staying power of the bond",
   "fused":"The relationship carries real weight and durability, so it tends to feel serious and built to last, sometimes from early on. That seriousness is a strength, though it can also make the bond feel heavy, dutiful, or slow to lighten up between you.",
   "flowing":"Commitment and structure come naturally to the two of you, so the relationship has a steady, dependable quality that holds up over time.",
   "friction":"Duty, restriction, or criticism can weigh on the bond, so it may feel to you like more obligation than joy in the harder stretches.",
   "navigation":"Let the seriousness be a foundation you build on, and keep it from turning into pressure that neither of you can put down."},
 "jupiter-sun":{"theme":"the growth, optimism, and generosity in the relationship",
   "fused":"The bond feels expansive and hopeful, so being together tends to enlarge you both and open things up. That optimism is a gift, though it can spill into overpromising, excess, or taking the relationship's good fortune for granted.",
   "flowing":"Growth and good faith move easily between you, so the relationship tends to encourage the bigger, more generous version of each of you.",
   "friction":"Excess, overpromising, or complacency can creep into the bond, so your expectations may inflate past what the relationship can actually deliver.",
   "navigation":"Let the relationship grow you both, and keep the optimism honest about what you are really building."},
 "pluto-sun":{"theme":"the depth, intensity, and transformative power of the bond",
   "fused":"The relationship is intense and tends to change you both at a deep level, so it rarely stays casual for long. That depth can be profound, though it can also concentrate into power struggles, control, or an all-or-nothing hold.",
   "flowing":"Transformation runs smoothly between you, so the bond can deepen and change you both without a constant fight.",
   "friction":"Power struggles, control, or obsession can concentrate in the bond, so the depth between you sometimes turns into a contest over who holds it.",
   "navigation":"Let the relationship transform you both, and keep power shared between you rather than seized."},
 "sun-uranus":{"theme":"the freedom, individuality, and unpredictability in the bond",
   "fused":"The relationship is unconventional and freedom-loving at its core, so it tends to resist the usual template for what a couple should be. That keeps it alive and interesting, though it can also make the bond unpredictable or slow to settle into anything steady.",
   "flowing":"Independence and closeness coexist easily in the bond, so the two of you can be free and connected at once.",
   "friction":"The pull between togetherness and autonomy can jolt the relationship, so a sudden change or a need for space may unsettle it just as it settles.",
   "navigation":"Give the relationship room to be its own unusual thing, and build enough steadiness between you to hold the surprises."},
 "neptune-sun":{"theme":"the idealism, imagination, and spiritual tone of the bond",
   "fused":"The relationship carries a dreamy, idealized quality, so it can feel inspired and almost fated, though it is also easy to see through rose-colored glasses. At its best it lifts you both; at its worst it hides who each of you really is.",
   "flowing":"Imagination and compassion move through the bond, giving it a gentle, almost spiritual warmth that you both feel.",
   "friction":"Idealization and reality can blur in the relationship, so disappointment or confusion may cloud who each of you actually is.",
   "navigation":"Let the relationship inspire you, and keep seeing the real person on the other side of the ideal."},
 "mercury-moon":{"theme":"how feeling and communication meet in the bond",
   "fused":"Talking and feeling are closely woven in the relationship, so the two of you tend to process emotions out loud together. This makes the bond emotionally articulate, though it can also over-analyze a mood until it grows larger than it was.",
   "flowing":"Head and heart support each other between you, so you can name what you feel and feel what you say without much trouble.",
   "friction":"Logic and mood can talk past each other in the relationship, so one of you may feel unheard while the other feels flooded.",
   "navigation":"Let feeling and reason each take a turn when you talk, and listen before you explain."},
 "jupiter-moon":{"theme":"the warmth, generosity, and emotional abundance of the bond",
   "fused":"The relationship feels emotionally generous and hopeful, so it nurtures on a big scale and tends to be a warm place to land. That generosity is real, though it can overpromise comfort or expect more reassurance than is realistic.",
   "flowing":"Care and optimism move together in the bond, so it tends to feel reassuring, warm, and easy to relax into.",
   "friction":"Emotional expectations can inflate between you, so needing more comfort than the relationship can give may strain it.",
   "navigation":"Let the generosity between you be genuine, and keep the emotional promises ones you can both actually keep."},
 "moon-uranus":{"theme":"the emotional freedom and unpredictability in the bond",
   "fused":"Feelings run electric and independent in the relationship, so closeness tends to come in bursts rather than a steady stream. That keeps things alive, though it can leave one or both of you unsure where you stand from week to week.",
   "flowing":"You give each other emotional freedom easily, so the bond feels alive without feeling clingy.",
   "friction":"Emotional needs and the need for space can clash in the relationship, so sudden distance may leave one of you unsettled.",
   "navigation":"Offer each other both closeness and freedom, and say plainly when you need steadiness."},
 "moon-pluto":{"theme":"the emotional depth and intensity of the bond",
   "fused":"Feelings run deep and powerful in the relationship, so it is capable of profound closeness and also an intensity that can overwhelm. The bond rarely stays on the surface, for better and for worse.",
   "flowing":"Emotional depth moves without a struggle between you, so the bond feels safe to be vulnerable in and can transform you both.",
   "friction":"Jealousy, control, or emotional power struggles can concentrate in the bond, so the depth between you sometimes turns into a grip.",
   "navigation":"Let the depth bond you, and keep feelings from turning into leverage over each other."},
 "mars-moon":{"theme":"how feeling and drive mix in the relationship",
   "fused":"Emotions run hot and reactive in the relationship, so feeling quickly becomes action between you. This makes the bond passionate and alive, though hurt can turn straight into heat and small things can flare fast.",
   "flowing":"Feeling and action support each other in the bond, so you tend to move on your emotions in healthy, direct ways.",
   "friction":"Moods and tempers can spark quickly between you, so hurt turns into heat and arguments catch before either of you has understood the feeling underneath.",
   "navigation":"Name the feeling before it becomes a fight, so the heat between you clears the air rather than scorching it."},
 "moon-venus":{"theme":"tenderness, comfort, and emotional affection between you",
   "fused":"Feeling and affection are closely entwined in the relationship, so the bond is warm, nurturing, and gentle. That tenderness is lovely, though it can also slide into keeping the peace and avoiding what needs to be said.",
   "flowing":"Care and love move easily between you, making the relationship emotionally sweet and comfortable to be in.",
   "friction":"Moods and desires can clash in the bond, or comfort can quietly stand in for facing a real issue.",
   "navigation":"Let the tenderness between you stay honest, so comfort does not become a way of avoiding each other."},
 "moon-saturn":{"theme":"emotional security, commitment, and how safe the bond feels",
   "fused":"Feeling and commitment are closely joined in the relationship, so the bond is serious and steady, with deep loyalty and also real emotional weight. It tends to feel safe and durable, though warmth can be slow to show and duty can crowd out tenderness.",
   "flowing":"Security and commitment come naturally to the two of you, giving the relationship a safe, durable feeling that holds over time.",
   "friction":"Coldness, duty, or emotional restriction can settle into the bond, so one of you may feel unmet even when the commitment is solid.",
   "navigation":"Let commitment create safety rather than obligation between you, and keep the warmth present alongside the loyalty."},
 "moon-neptune":{"theme":"the tenderness, sensitivity, and idealism in the emotional bond",
   "fused":"The emotional connection is dreamy and deeply attuned, so the two of you can feel almost telepathic with each other. That sensitivity is beautiful, though boundaries can blur and it is easy to feel each other's moods as your own.",
   "flowing":"Compassion and imagination move through the bond, making it gentle, understanding, and quietly romantic.",
   "friction":"Idealization, confusion, or quiet disappointment can cloud the emotional truth between you, so it is hard to tell the real feeling from the wished-for one.",
   "navigation":"Enjoy the tenderness between you while staying honest about what is actually there."},
 "mercury-venus":{"theme":"the ease, charm, and affection in how you communicate",
   "fused":"Talk and affection blend warmly in the relationship, so conversation between you tends to be pleasant, diplomatic, and easy to enjoy. This makes the bond graceful, though smoothing things over can take the place of saying the hard thing.",
   "flowing":"Kind words and shared taste move easily between you, so the relationship communicates with warmth and grace.",
   "friction":"Smoothing things over can replace real honesty in the bond, so sweetness may sidestep the issue that actually needs airing.",
   "navigation":"Keep the charm between you, and let honesty share the conversation rather than lose to it."},
 "mars-mercury":{"theme":"how the relationship debates, decides, and drives ideas forward",
   "fused":"Thinking and action are tightly linked in the relationship, so the two of you decide fast and move on it. This makes the bond sharp and productive, though talk can turn combative and debates can heat up quickly.",
   "flowing":"Ideas and initiative support each other between you, so you plan and act well together as a pair.",
   "friction":"Arguments can sharpen fast in the relationship, so words may be used as weapons when tempers rise between you.",
   "navigation":"Aim the mental energy at the problem rather than at each other, and let the sharpness solve things instead of scoring points."},
 "jupiter-mercury":{"theme":"the shared curiosity, learning, and big ideas in the bond",
   "fused":"The relationship loves ideas and possibility, so the two of you are endlessly curious together and drawn to what could be. That keeps the bond lively, though it can promise more than it thinks through or lose the details in the excitement.",
   "flowing":"Curiosity and optimism move together between you, so you learn, plan, and dream well as a pair.",
   "friction":"Big talk can outrun the details in the relationship, so exaggeration or scattered focus may need reining in before plans fall through.",
   "navigation":"Let your shared ideas grow, and check them against the small print before you build on them."},
 "mercury-saturn":{"theme":"how seriously and carefully the relationship communicates",
   "fused":"Thinking is disciplined and deliberate in the relationship, so the two of you tend to talk things through carefully and mean what you say. This makes the bond thoughtful and committed, though conversation can turn dry, critical, or heavy.",
   "flowing":"Structure and communication support each other between you, so you make careful, durable decisions as a pair.",
   "friction":"Criticism, silence, or heavy seriousness can chill the conversation between you, so one of you may end up feeling corrected rather than heard.",
   "navigation":"Let the care in how you speak build trust rather than pressure, and keep seriousness from becoming coldness."},
 "mercury-uranus":{"theme":"the originality and mental spark in the bond",
   "fused":"Thinking is quick, inventive, and unconventional in the relationship, so the two of you spark ideas off each other and rarely bore. That spark is exciting, though it can also be erratic, and plans can change faster than either of you can keep up with.",
   "flowing":"Fresh ideas and open-mindedness move easily between you, so the bond stays mentally alive and surprising.",
   "friction":"Restless or contrary thinking can unsettle your plans, so you may change your minds in ways that jar the other.",
   "navigation":"Enjoy the mental spark between you, and give shared decisions time to settle before you act."},
 "mercury-neptune":{"theme":"the imagination and intuition in how you understand each other",
   "fused":"Thinking is imaginative and intuitive in the relationship, so the two of you understand each other in subtle, unspoken ways. That attunement is lovely, though facts can get lost in impressions and it is easy to assume you understood when you did not.",
   "flowing":"Imagination and communication move together between you, so you grasp each other by feel as much as by words.",
   "friction":"Confusion, vagueness, or wishful thinking can muddy communication between you, so clarity may take real effort.",
   "navigation":"Trust the intuition between you, and check the facts before you act on what you assumed."},
 "mercury-pluto":{"theme":"the depth and intensity of how the relationship thinks and talks",
   "fused":"Thinking runs deep and probing in the relationship, so the two of you can go straight to the hard, honest conversations others avoid. That depth is valuable, though talk can also turn controlling, secretive, or into a contest to be right.",
   "flowing":"Depth and communication move without a fight between you, so you can discuss hard truths and grow from them.",
   "friction":"Power can enter the conversation between you as pressure, secrecy, or the urge to win, so honesty has to be chosen on purpose.",
   "navigation":"Use the depth between you to understand each other rather than to control the story."},
 "jupiter-venus":{"theme":"the warmth, generosity, and pleasure in the love",
   "fused":"Affection is abundant and generous in the relationship, so it tends toward warmth, comfort, and the good life together. That is easy to enjoy, though it can tip into excess or into taking the sweetness for granted.",
   "flowing":"Love and good fortune move together between you, so the bond feels warm, lucky, and easy to enjoy.",
   "friction":"Overindulgence or complacency can soften the bond's edge, so you may coast on the good feeling and forget to tend it.",
   "navigation":"Enjoy the abundance between you, and keep appreciating what you already have."},
 "uranus-venus":{"theme":"the excitement and freedom in the love",
   "fused":"Attraction is electric and unconventional in the relationship, so the love resists the usual rules and stays exciting. That charge is thrilling, though feelings can run hot and then cool, and closeness can start to feel like confinement.",
   "flowing":"Affection and freedom coexist easily between you, so the bond stays exciting without feeling caged.",
   "friction":"The pull between closeness and independence can destabilize the love, so feeling may run hot and then cool without warning.",
   "navigation":"Keep the spark that keeps you interested, and offer the reliability that lets the love last."},
 "saturn-venus":{"theme":"the commitment, loyalty, and durability of the love",
   "fused":"Love here is serious and lasting, so the two of you tend toward real loyalty and long commitment. That steadiness is a strength, though it can also make affection feel dutiful, withheld, or slow to warm.",
   "flowing":"Affection and commitment support each other between you, giving the love a steady, dependable quality.",
   "friction":"Love can feel dutiful, withheld, or tested in the relationship, so warmth may need to be worked at rather than assumed.",
   "navigation":"Let commitment deepen the affection between you rather than cool it."},
 "neptune-venus":{"theme":"romance, idealism, and enchantment in the love",
   "fused":"The love is romantic and dreamy, so the relationship can feel enchanted and tender, easy to idealize. That magic is real, though it can also blur into illusion and set up disappointment when reality shows through.",
   "flowing":"Beauty, compassion, and imagination move through the bond, making the love feel gentle and almost magical.",
   "friction":"Illusion, idealization, or disappointment can cloud the love when reality intrudes, so you may be in love with the dream more than the person.",
   "navigation":"Enjoy the romance between you while keeping your eyes open to the real person you each are."},
 "pluto-venus":{"theme":"the intensity and transformative pull of the love",
   "fused":"The love is intense and consuming, so the relationship tends to run deep and to change you both. That depth is powerful, though it can also concentrate into jealousy, control, or obsession.",
   "flowing":"Depth and passion move without a fight between you, so the bond can change you both gently.",
   "friction":"Jealousy, control, or obsession can concentrate in the love, so the intensity between you must be handled honestly.",
   "navigation":"Let love take you both deep, and keep depth from turning into a grip."},
 "mars-venus":{"theme":"attraction, desire, and chemistry between you",
   "fused":"The attraction is strong and immediate, so there tends to be real chemistry and heat in the relationship. That spark is a gift, though desire and friction arrive together, and passion can tip into conflict.",
   "flowing":"Desire and affection move together between you, so the spark stays warm and easy rather than fraught.",
   "friction":"Attraction and friction mix in the relationship, so passion can tip into conflict or a push-and-pull between you.",
   "navigation":"Let the chemistry between you serve closeness rather than drama."},
 "jupiter-mars":{"theme":"the drive, enthusiasm, and shared adventure in the bond",
   "fused":"Energy and optimism combine into bold, enthusiastic action, so the two of you tend to take on a lot together and aim high. That momentum is exciting, though it can overreach or burn hot and fast.",
   "flowing":"Drive and confidence support each other between you, so you pursue goals together with real momentum.",
   "friction":"Overconfidence, restlessness, or clashing appetites for risk can push the bond past its limits, so you may leap together before you have looked.",
   "navigation":"Let your shared energy build something, and pace the ambition so it lasts."},
 "mars-saturn":{"theme":"how the relationship balances drive and restraint",
   "fused":"Energy and discipline are tightly linked in the relationship, so the two of you are capable of sustained effort together but prone to frustration. The gas and the brake can be pressed at once, which builds tension between you.",
   "flowing":"Drive and structure support each other between you, so you get things done together and finish what you start.",
   "friction":"Action and limitation can grind in the relationship, breeding frustration, blocked effort, or resentment between you.",
   "navigation":"Turn the friction into disciplined, shared effort rather than a standoff."},
 "mars-uranus":{"theme":"the volatility and excitement in how the relationship acts",
   "fused":"Action runs electric and impulsive in the relationship, so the two of you can be bold and spontaneous together. That is exciting, though it can also be reckless or explosive, and conflict can flare without warning.",
   "flowing":"Initiative and independence move together between you, so you act freely and spark each other into motion.",
   "friction":"Sudden anger, impatience, or abrupt moves can jolt the bond, so conflict may flare between you without much warning.",
   "navigation":"Channel the charge into something you build together, and pause before the impulsive move."},
 "mars-neptune":{"theme":"how desire, drive, and imagination mix in the bond",
   "fused":"Action and dreaminess blend in the relationship, so the two of you can be inspired and romantic together, though the drive can dissipate or lose direction. Effort follows inspiration more than plans.",
   "flowing":"Imagination and gentle action support each other between you, so you pursue shared ideals with a soft persistence.",
   "friction":"Confusion about what you each want can sap the drive between you, so passivity or misdirected effort may creep in.",
   "navigation":"Let a shared vision guide your action, and be clear about what you are each actually pursuing."},
 "mars-pluto":{"theme":"the power, drive, and intensity in the bond",
   "fused":"Will and force combine into a formidable, transformative drive, so the two of you can accomplish a great deal together and push through what stops most people. That power is real, though it can turn into a power struggle between you.",
   "flowing":"Deep power and action move without a fight between you, so you accomplish and transform a great deal together.",
   "friction":"Control, domination, or a battle of wills can concentrate in the relationship, so it must be handled with real care.",
   "navigation":"Point the shared power at a goal you both want, not at winning against each other."},
 "jupiter-saturn":{"theme":"how the relationship balances growth and structure",
   "fused":"Expansion and discipline are tightly linked in the relationship, so the bond can build steadily and realistically, though it may swing between hope and caution. You want to grow and to play it safe at once.",
   "flowing":"Optimism and structure support each other between you, so the relationship grows in durable, well-built ways.",
   "friction":"The pull between wanting more and playing it safe can stall the bond, so timing may feel off and openings pass while you weigh them.",
   "navigation":"Let ambition and patience take turns, and build the growth between you to last."},
 "jupiter-uranus":{"theme":"the sense of possibility and awakening the bond shares",
   "fused":"The relationship shares a taste for freedom and breakthrough, so it tends to feel exciting, progressive, and open to change. That is invigorating, though it can also be restless and slow to commit to anything settled.",
   "flowing":"Growth and change move easily together between you, so the bond stays open, hopeful, and forward-looking.",
   "friction":"Impatience for change can outrun what is sustainable, so sudden shifts may unsettle your plans together.",
   "navigation":"Welcome the new between you, and give the breakthroughs room to become real."},
 "jupiter-neptune":{"theme":"the shared idealism and imagination of the bond",
   "fused":"The relationship shares big dreams and a spiritual longing, so it can feel inspiring and compassionate together. That vision is beautiful, though it can also lose the plot in idealism and skip the practical.",
   "flowing":"Faith and imagination move together between you, so the bond feels hopeful, generous, and quietly meaningful.",
   "friction":"Shared illusions or unrealistic hopes can lead to disappointment when reality arrives, so the dream may outrun what the relationship can deliver.",
   "navigation":"Let the shared vision lift you, and keep one foot on the ground."},
 "jupiter-pluto":{"theme":"the ambition and transformative drive the bond shares",
   "fused":"The relationship shares deep ambition and intensity, so together the two of you can be powerful, determined, and capable of large-scale change. That drive is formidable, though it can overreach or harden into a hunger for control.",
   "flowing":"Growth and depth move together between you, so the bond can transform and achieve on a large scale.",
   "friction":"Obsession, excess, or a hunger for power can distort the bond's aims, so the drive to grow can become a drive to dominate.",
   "navigation":"Aim the shared drive at something worthy, and keep the power between you in proportion."},
 "saturn-uranus":{"theme":"how the bond holds tradition and change together",
   "fused":"Structure and rebellion are tightly linked in the relationship, so the bond balances stability and change with some inner tension. You want to keep what is safe and to break free at once.",
   "flowing":"Discipline and innovation support each other between you, so you can change what needs changing without losing your footing.",
   "friction":"The pull between security and freedom can grind in the relationship, so you may feel torn between holding on and breaking free.",
   "navigation":"Change what needs to change between you, and keep the foundation that works."},
 "neptune-saturn":{"theme":"how the bond holds dreams and reality together",
   "fused":"Ideals and structure are closely linked in the relationship, so the two of you can make dreams real together, though doubt and disillusion can visit. At your best you build the imagined; at your worst fear talks you out of it.",
   "flowing":"Vision and discipline support each other between you, so you can build something meaningful with both faith and patience.",
   "friction":"Dreams and hard limits can collide in the relationship, so disappointment or vague fears may weigh on what you are building together.",
   "navigation":"Give the shared dream a real structure, and let patience carry it."},
 "pluto-saturn":{"theme":"the endurance and depth the bond can withstand",
   "fused":"Commitment and depth are tightly linked in the relationship, so the bond is durable and serious, capable of surviving real pressure. That endurance is a strength, though it can harden into control or grim obligation.",
   "flowing":"Discipline and transformation support each other between you, so the relationship can change deeply and still hold.",
   "friction":"Control, fear, or heavy testing can concentrate in the bond, so it may face hard, defining pressure that either deepens or breaks it.",
   "navigation":"Let hardship deepen the commitment between you rather than harden it."},
 "neptune-uranus":{"theme":"the shared imagination and appetite for change in the bond",
   "fused":"The relationship shares a generational sensitivity to change and vision, so the two of you tend to be imaginative and progressive together.",
   "flowing":"Intuition and originality move together between you, so the bond is open to new and unconventional ways of seeing.",
   "friction":"Restlessness and idealism can pull in different directions, unsettling your shared plans.",
   "navigation":"Let the shared vision inspire you, and keep it connected to real life."},
 "pluto-uranus":{"theme":"the shared drive for change and upheaval in the bond",
   "fused":"The relationship shares a generational charge for radical change, so together you are drawn toward overturning what feels stuck.",
   "flowing":"The urge to transform and the urge to break free move together between you, so the bond can change boldly.",
   "friction":"The pressure to overturn things can become disruptive or extreme, straining your stability.",
   "navigation":"Direct the appetite for change toward something you actually want to build together."},
 "neptune-pluto":{"theme":"the deep, generational undercurrent the bond shares",
   "fused":"The relationship shares a deep generational tone of transformation and spiritual change, felt more as atmosphere than event.",
   "flowing":"Profound imagination and depth move quietly together beneath the bond.",
   "friction":"Large, slow undercurrents of change can surface as an unease that is bigger than the relationship itself.",
   "navigation":"Recognize this as the wider era you share, and keep your attention on what is personal between the two of you."},
}

def _key(a, b): return "-".join(sorted([a, b]))
def is_authored(a, b): return _key(a, b) in PAIRS

def compose_composite_aspect(a, b, aspect, prominent=False):
    """`prominent` applies only to the generational outer-outer pairs (Uranus/Neptune/Pluto with
    each other). By default they read as shared cohort background; the app sets prominent=True when
    the pattern is angular, closely contacts a composite personal planet or the Ascendant, rules or
    strongly participates in a major composite configuration, or the two people have a meaningful age
    gap (so 'same cohort' no longer explains it), and the reading upgrades to relationship-specific."""
    key = _key(a, b)
    if key not in PAIRS: return None
    p = PAIRS[key]; A, B = key.split("-")
    val = VALENCE[aspect]
    bareA = DISP[A].replace("the ", ""); bareB = DISP[B].replace("the ", "")
    astro = f"composite {bareA} {ASPECT_VERB[aspect]} {bareB}"
    generational = A in OUTER_SLOW and B in OUTER_SLOW
    # named fields so the app maps to body/sections deterministically (not by paragraph position)
    experience = p[val]
    guidance = p["navigation"]
    if generational and not prominent:
        note = ("This pattern is shared by many people born near your ages, so it does not describe the "
                "relationship by itself. In this composite it becomes more noticeable when it is close to "
                "an angle, in a prominent house, or closely tied to a personal planet or the Ascendant.")
    elif generational and prominent:
        note = ("This pattern is prominent in your composite chart, so here it reads as more than "
                "generational background and genuinely colors the relationship.")
    else:
        note = None
    paras = [experience]
    if note:
        paras.append(note)
    paras.append(guidance)
    paras.append(f"The astro: {astro}.")
    return {"title": f"Composite {bareA} {ASPECT_WORD[aspect]} {bareB}",
            "eyebrow": {"label": "Composite aspect", "pair": key, "aspect": aspect, "valence": val,
                        "theme": p["theme"], "generational": generational, "prominent": prominent},
            "generational": generational, "prominent": prominent,
            "astro": astro,
            "experience": experience, "guidance": guidance, "note": note,
            "paragraphs": paras,
            "trace": {"pair": key, "aspect": aspect,
                      "sourceKeys": [f"cc/composite/{A}", f"cc/composite/{B}"],
                      "readerAuthority": "composed-reviewed"}}
