#!/usr/bin/env python3
"""
natal_aspect.py — composer for natal-chart aspects (aspects between your OWN birth planets).

A character reading, not a dated event (transit) or a relationship (composite/synastry).
Structure: lived experience (two concrete ways the dynamic shows up), then guidance, then the
technical aspect as a footer. Marie's plain full-form voice; planet-accurate; no em dashes.

Astronomical reality is respected: Mercury and Venus never stray far from the Sun, so certain
aspects between them cannot occur natally and are never emitted (CONSTRAINTS below).
"""
DISP = {"sun":"your Sun","moon":"your Moon","mercury":"your Mercury","venus":"your Venus",
        "mars":"your Mars","jupiter":"your Jupiter","saturn":"your Saturn","uranus":"your Uranus",
        "neptune":"your Neptune","pluto":"your Pluto"}
BARE = {k: v.replace("your ", "") for k, v in DISP.items()}
ASPECT_WORD = {"conjunction":"conjunct","square":"square","opposition":"opposite",
               "trine":"trine","sextile":"sextile"}
ASPECT_VERB = {"conjunction":"conjuncts","square":"squares","opposition":"opposes",
               "trine":"trines","sextile":"sextiles"}
VALENCE = {"conjunction":"fused","trine":"flowing","sextile":"flowing","square":"friction","opposition":"friction"}
ALL5 = {"conjunction","square","opposition","trine","sextile"}

# astronomically possible natal aspects for the tight inner pairs (else all 5)
CONSTRAINTS = {
 "mercury-sun": {"conjunction"},               # Mercury never > ~28 deg from the Sun
 "sun-venus":   {"conjunction"},               # Venus never > ~47 deg from the Sun
 "mercury-venus": {"conjunction", "sextile"},  # max separation ~76 deg
}
OUTER_SLOW = {"uranus", "neptune", "pluto"}

# Each pair: theme (metadata) + fused / flowing / friction lived-experience passages + guidance.
PAIRS = {
 "moon-sun":{"theme":"how your sense of direction fits with what you need emotionally",
   "friction":"What you want for yourself and what helps you feel settled do not always agree. You may choose a direction, then struggle with what that choice requires from you. At other times, you may protect your immediate comfort and later feel frustrated that you are no closer to the life you want.",
   "fused":"Your sense of direction and your emotional needs are closely joined, so what you are drawn to usually also settles you. This gives you a whole-hearted, all-in quality, though it can be hard to step outside yourself or take in a very different point of view.",
   "flowing":"Your sense of direction and your emotional needs tend to support each other, so pursuing what you want rarely costs you your sense of safety. You can commit to a path and still feel like yourself while you walk it.",
   "navigation":"Before making an important decision, consider both where you want to go and what you will need emotionally to follow through."},
 "mercury-sun":{"theme":"how closely your thinking is tied to your sense of self",
   "fused":"The way you think and the person you are speak with one voice, so your opinions can feel like extensions of your identity. This makes you articulate and sure of yourself, though you may take disagreement personally, as if a challenge to an idea were a challenge to you.",
   "flowing":"Your mind and your identity work together easily, so you tend to know what you think and can say it clearly.",
   "friction":"Your ideas and your sense of self can crowd each other, so you may defend a position mainly because it has become yours.",
   "navigation":"Say what you think plainly, and let an idea be wrong without taking it as a verdict on you."},
 "sun-venus":{"theme":"how your identity blends with what you love and value",
   "fused":"Who you are is closely tied to what you find beautiful and to being liked, so warmth, taste, and relationship sit near the center of your identity. This makes you charming and easy to be around, though your sense of self can come to lean on being wanted.",
   "flowing":"Your identity and your affections support each other, so you tend to know what you value and to move toward it with a certain grace.",
   "friction":"Your sense of self and your wish to be liked can compete, so approval may quietly pull you off your own course.",
   "navigation":"Enjoy being liked, and check that you are not trading your own direction to keep it."},
 "mars-sun":{"theme":"how your drive serves the person you are becoming",
   "fused":"Your will and your drive move as a single force, so when you want something you tend to go straight at it. This gives you courage and initiative, though it can tip into impatience, or into treating every obstacle as a fight.",
   "flowing":"Your drive backs your intentions, so you can act on what you want without much internal argument. Energy tends to be there when you decide to move.",
   "friction":"Your drive and your sense of self can get in each other's way, so frustration builds when you are blocked, and you may push hardest exactly when it would help to wait.",
   "navigation":"Aim your energy at what you are actually trying to build, and spend it on the goal rather than on whoever is in the way."},
 "saturn-sun":{"theme":"how responsibility and self-doubt shape who you are",
   "fused":"Your sense of self is bound up with duty and seriousness, so you take yourself and your obligations to heart, often carrying weight from an early age. You can be quietly hard on yourself, measuring who you are against a standard that is rarely met.",
   "flowing":"Discipline supports your identity, so you tend to build steadily and to take quiet pride in what you have earned rather than what you were handed.",
   "friction":"Self-doubt can shadow your confidence, so you may feel you have to prove your worth before you are allowed to simply be yourself.",
   "navigation":"Let responsibility give your life shape without letting it become the measure of whether you are good enough."},
 "jupiter-sun":{"theme":"how optimism and the urge to grow color who you are",
   "fused":"Confidence and a sense of possibility are woven into your identity, so you tend to believe things can expand and to reach for more. It lends you warmth and generosity, though it can spill into overreach, or into promising more than you can hold.",
   "flowing":"Optimism supports who you are, so opportunity and goodwill tend to find you, and you carry a faith that usually serves you well.",
   "friction":"Your reach can exceed your grasp, so confidence tips into overextension, and you may take on more than is wise before you notice.",
   "navigation":"Let your optimism move you forward, and keep it honest about what you can actually carry."},
 "pluto-sun":{"theme":"how depth and power run through who you are",
   "fused":"Intensity sits close to the center of who you are, so you rarely do anything halfway and can remake yourself when you need to. That power is real, though it can turn into a need to control, or an all-or-nothing grip on your own life.",
   "flowing":"You can transform yourself without a great struggle, drawing on deep reserves when one chapter of your life needs to end and another to begin.",
   "friction":"Power struggles, control, or a fear of being powerless can shadow your sense of self, especially when it feels like someone else holds the reins.",
   "navigation":"Use your depth to remake yourself rather than to control everything around you."},
 "sun-uranus":{"theme":"how much individuality and independence mark who you are",
   "fused":"Freedom and originality are built into your identity, so you need to be your own person and tend to do things your own way. This makes you inventive and hard to typecast, though it can also leave you restless or contrary when anything asks you to conform.",
   "flowing":"Independence and belonging sit comfortably together in you, so you can be part of things without losing your own shape.",
   "friction":"Your need to be different can unsettle your footing, so you may resist the very structures that would steady you, or change course just as things settle.",
   "navigation":"Give yourself room to be original, and build enough steadiness that your freedom has something to stand on."},
 "neptune-sun":{"theme":"how imagination and ideals color who you are",
   "fused":"Your sense of self is bound up with imagination and longing, so you are sensitive, impressionable, and drawn toward something larger than ordinary life. This gives you artistry and empathy, though it can leave you unsure who you actually are underneath the roles you take on.",
   "flowing":"Imagination and compassion feed your identity, so inspiration and a sense of meaning come to you fairly naturally.",
   "friction":"Your sense of self can blur, so you may lose your outline in other people, in ideals, or in a version of yourself that is more dream than fact.",
   "navigation":"Let what inspires you shape your life, and keep hold of the plain facts of who and where you are."},
 "mercury-moon":{"theme":"how your thinking and your feelings talk to each other",
   "fused":"Your mind and your emotions are closely joined, so you think about how you feel and feel your way through what you think. This makes you perceptive and expressive, though you can also turn a mood over in your head long past the point where it helps.",
   "flowing":"Head and heart cooperate in you, so you can usually put a feeling into words and let reason and emotion inform each other.",
   "friction":"Thinking and feeling can pull against each other, so you may talk yourself out of what you feel, or be so flooded that words desert you.",
   "navigation":"Let a feeling be named before you analyze it, and let your reasoning include what your gut already knows."},
 "jupiter-moon":{"theme":"how generous and hungry your emotional nature is",
   "fused":"Your feelings run large and hopeful, so you nurture generously and want a good deal of warmth in return. This makes you comforting to be around, though your emotional needs can inflate, and you may look for reassurance in food, spending, or simply more of everything.",
   "flowing":"Optimism feeds your emotional life, so you comfort easily, recover well, and tend to expect kindness from the world.",
   "friction":"Your emotional appetite can outrun what is realistic, so you may feel let down when the comfort on offer falls short of the amount you wanted.",
   "navigation":"Let your generous heart give freely, and notice when you are asking the outside world to fill something only you can tend."},
 "moon-uranus":{"theme":"how much freedom and unpredictability your feelings carry",
   "fused":"Your emotions run quick and independent, so closeness tends to happen on your own terms and in its own rhythm. You can feel deeply one moment and need distance the next, which frees you and confuses the people who want steadiness.",
   "flowing":"You give yourself and others emotional room easily, so you can be close without feeling trapped and free without feeling cut off.",
   "friction":"Your need for closeness and your need for space can jolt against each other, so feelings arrive suddenly and just as suddenly ask for distance.",
   "navigation":"Offer people both your warmth and honesty about your need for space, so your changes do not read as rejection."},
 "moon-pluto":{"theme":"how deep and intense your emotional world runs",
   "fused":"Your feelings run deep and powerful, so attachment matters enormously to you and rarely stays on the surface. This lets you bond profoundly, though it can also bring jealousy, a fear of loss, or a pull to control what you cannot bear to lose.",
   "flowing":"You can feel deeply and be changed by it without being overwhelmed, so intensity tends to bond you rather than frighten you.",
   "friction":"A fear of loss or betrayal can grip your emotional life, so you may test people, hold on too tightly, or brace for an ending that has not come.",
   "navigation":"Let the depth of your feeling connect you, and keep it from turning into a grip on the people you love."},
 "mercury-venus":{"theme":"how charm and grace shape the way you think and speak",
   "fused":"Your thinking and your sense of what is pleasing are closely joined, so you tend to speak with tact, warmth, and an ear for how things land. This makes you diplomatic and easy to talk to, though you may smooth a conversation when it needs plain honesty instead.",
   "flowing":"Kind words and good taste come easily to you, so you connect through how you speak and can put people at ease.",
   "friction":"A wish to keep things pleasant can soften your honesty, so the harder truth waits while you keep the peace.",
   "navigation":"Keep your gift for putting people at ease, and let it carry the honest thing rather than replace it."},
 "mars-mercury":{"theme":"how sharp and forceful your thinking and speech are",
   "fused":"Your mind and your drive are closely joined, so you think quickly, decide fast, and say what you mean. This makes you sharp and effective, though your words can turn cutting when you are heated, and you may argue to win rather than to understand.",
   "flowing":"Thought and action support each other, so you plan and then do, and your decisions tend to carry through into movement.",
   "friction":"Arguments can sharpen quickly in you, so impatience outruns your listening and words become weapons before you mean them to.",
   "navigation":"Point your quick mind at the problem rather than at the person, and let listening keep pace with speaking."},
 "jupiter-mercury":{"theme":"how big and curious your thinking runs",
   "fused":"Your mind loves scale and possibility, so you think in broad strokes and are drawn to ideas that open things up. This makes you a natural learner and teacher, though you can skate over the details or claim more than you have checked.",
   "flowing":"Curiosity and optimism feed your thinking, so you learn widely and connect ideas with real enthusiasm.",
   "friction":"Big ideas can outrun the fine print, so exaggeration or scattered focus may cost you when the specifics come due.",
   "navigation":"Let your ideas grow as large as they want, and check them against the small print before you build on them."},
 "mercury-saturn":{"theme":"how careful and serious your thinking is",
   "fused":"Your mind is disciplined and thorough, so you think slowly, build carefully, and prefer to be sure before you speak. This makes you dependable and deep, though it can also make you self-critical, or quiet at the moment your voice is most needed.",
   "flowing":"Structure supports your thinking, so you can concentrate, plan, and finish, and your conclusions tend to hold up.",
   "friction":"Doubt can chill your voice, so you may hold an idea back for fear it is not good enough, and mistake caution for accuracy.",
   "navigation":"Let your rigor sharpen your ideas rather than silence them, and speak before you feel completely certain."},
 "mercury-uranus":{"theme":"how original and quick your mind is",
   "fused":"Your thinking is fast and inventive, so insight tends to arrive in leaps rather than steps, and you see what others miss. This is brilliant when it lands, though it can also scatter, or push you to argue the opposite simply because everyone agrees.",
   "flowing":"Fresh ideas come easily to you, so you stay curious, open, and comfortable with the new.",
   "friction":"Restless or contrary thinking can jump around, so it is hard to settle, and you may change your mind in ways that unsettle the people relying on you.",
   "navigation":"Trust your flashes of insight, and give them time to settle before you act on them."},
 "mercury-neptune":{"theme":"how imaginative and intuitive your mind is",
   "fused":"Your thinking is imaginative and intuitive, so you sense meaning, mood, and what goes unsaid. This makes you poetic and perceptive, though facts can dissolve into impressions, and you may believe a thing because you wish it were so.",
   "flowing":"Imagination feeds your mind, so you grasp things by feel and image as much as by logic.",
   "friction":"Vagueness or wishful thinking can cloud your clarity, so it takes real effort to separate what is true from what you hope is true.",
   "navigation":"Honor your intuition, and check it against plain facts before you act on it."},
 "mercury-pluto":{"theme":"how deep and probing your mind is",
   "fused":"Your thinking is intense and penetrating, so you dig beneath the surface and are not satisfied with easy answers. This makes you insightful and hard to fool, though your mind can fixate, turn suspicious, or use what it learns as leverage.",
   "flowing":"Depth comes naturally to your mind, so you can research, investigate, and sit with hard truths without flinching.",
   "friction":"Your thoughts can lock onto something and refuse to let go, so suspicion or obsession may take the place of understanding.",
   "navigation":"Use your depth to understand rather than to control, and let a conclusion be enough without needing to win with it."},
 "jupiter-venus":{"theme":"how warm and pleasure-loving your affections are",
   "fused":"Love and abundance blend in you, so affection is generous, warm, and inclined toward the good life. This makes you easy to love and quick to give, though it can tip into indulgence, or into taking sweetness for granted.",
   "flowing":"Warmth and good fortune move together in you, so relationship and pleasure tend to come with a certain ease.",
   "friction":"Indulgence or complacency can soften your edge, so you may overdo the pleasant and undervalue what you already have.",
   "navigation":"Enjoy your capacity for pleasure and warmth, and keep appreciating what is already yours."},
 "uranus-venus":{"theme":"how free and unconventional your loving is",
   "fused":"Attraction runs electric and independent in you, so you love in your own way and resist rules about how it should look. This keeps things alive, though your feelings can run hot and then cool, and closeness can start to feel like confinement.",
   "flowing":"You hold love and freedom together with ease, so you can be close without feeling caged.",
   "friction":"Your pull between intimacy and independence can unsettle your affections, so you may want someone most once distance appears.",
   "navigation":"Keep the freedom that keeps you interested, and offer the steadiness that lets love actually land."},
 "saturn-venus":{"theme":"how seriously and cautiously you love",
   "fused":"Affection and commitment are closely joined in you, so you love loyally and for the long term, and you do not give your heart lightly. This makes you steadfast, though you can also hold back, expect little, or feel that love has to be earned.",
   "flowing":"Steadiness supports your affections, so your love is dependable and tends to deepen with time.",
   "friction":"You may feel unworthy of love or keep it at a careful distance until it has proven safe, so warmth arrives slowly and guarded.",
   "navigation":"Let commitment be a way of warming your love rather than guarding it, and risk being wanted before it is proven."},
 "neptune-venus":{"theme":"how romantic and idealistic your loving is",
   "fused":"Love and imagination blend in you, so you love tenderly and tend to see the best in whoever you are drawn to. This makes your affection gentle and forgiving, though you may love the idea of a person and miss the real one in front of you.",
   "flowing":"Compassion and beauty feed your affections, so your love carries a soft, imaginative quality that others feel.",
   "friction":"Idealizing or rescuing can cloud your love, so disappointment tends to follow once the real person comes into focus.",
   "navigation":"Let romance lift you, and keep your eyes open to the actual person you are loving."},
 "pluto-venus":{"theme":"how intense and transformative your loving is",
   "fused":"Love runs deep and consuming in you, so attraction is rarely casual and closeness tends to change you. This can be profound, though it can also bring jealousy, possessiveness, or a fear of losing what you have let matter.",
   "flowing":"You love with depth and can be transformed by it without a struggle, so intensity tends to bond you rather than frighten you.",
   "friction":"A fear of loss can grip your love, so you may hold on too tightly, test the bond, or brace for a betrayal that is not there.",
   "navigation":"Let love take you deep, and keep depth from turning into control."},
 "mars-venus":{"theme":"how your drive and your desire for love work together",
   "fused":"Wanting and loving are closely joined in you, so you pursue what attracts you with real warmth and heat. This gives you magnetism, though desire and tenderness can blur, and the chase can matter more than the person once you have caught them.",
   "flowing":"Your drive and your charm cooperate, so you can go after love and pleasure with confidence and follow through.",
   "friction":"Wanting and loving can pull against each other, so closeness runs hot and conflicted, and attraction and irritation arrive together.",
   "navigation":"Let desire and tenderness take turns rather than compete, so wanting someone and caring for them point the same way."},
 "jupiter-mars":{"theme":"how bold and enthusiastic your drive is",
   "fused":"Energy and optimism combine in you into bold, confident action, so you tend to move first and worry later. This carries real momentum, though it can overreach, burn hot, or take on more risk than the situation deserves.",
   "flowing":"Confidence backs your drive, so you pursue goals with good timing and rarely talk yourself out of the attempt.",
   "friction":"Overconfidence or restlessness can push you past your limits, so you may scatter your effort or leap before you have looked.",
   "navigation":"Let your enthusiasm move you, and pace it so that it builds something rather than burning through it."},
 "mars-saturn":{"theme":"how your drive and your discipline work together",
   "fused":"Energy and restraint are closely joined in you, so you can work hard and long, but often against an inner brake. This makes you capable of sustained effort, though it can breed frustration, or a stop-start rhythm where the gas and the brake are pressed at once.",
   "flowing":"Drive and structure cooperate in you, so you work steadily, finish what you start, and turn effort into something durable.",
   "friction":"Your drive can meet a wall of caution or fear, so effort feels blocked, and frustration builds where momentum should be.",
   "navigation":"Turn the friction into patient, deliberate effort, and let discipline aim your drive rather than fight it."},
 "mars-uranus":{"theme":"how impulsive and electric your drive is",
   "fused":"Your drive runs fast and independent, so you act on impulse and resist being told to wait. This makes you bold and quick, though it can also be reckless, and a sudden move can undo what patience would have kept.",
   "flowing":"Initiative and originality combine in you, so you act freely, improvise well, and spark others into motion.",
   "friction":"Sudden impulses or a short fuse can jolt your actions, so anger and abrupt moves arrive with little warning and cost you afterward.",
   "navigation":"Channel the charge into something you are building, and put a pause between the impulse and the act."},
 "mars-neptune":{"theme":"how your drive mixes with imagination and ideals",
   "fused":"Action and dreaminess blend in you, so your energy follows inspiration more than plans. This makes your effort imaginative and often subtle, though your drive can waver, dissipate, or lose track of what it was for.",
   "flowing":"Imagination guides your action, so you move toward what you envision with a quiet, sidelong persistence.",
   "friction":"Confusion about what you actually want can drain your drive, so effort scatters, stalls, or goes toward the wrong thing.",
   "navigation":"Let a clear picture of what you want give your energy its direction before you spend it."},
 "mars-pluto":{"theme":"how powerful and intense your drive is",
   "fused":"Will and force combine in you into formidable drive, so once you commit, you tend to go all the way. This gives you stamina and the power to transform, though it can also turn into a need to dominate or a refusal to let go.",
   "flowing":"Deep power feeds your action, so you accomplish and endure well past the point where others tire.",
   "friction":"Control, compulsion, or a contest of wills can seize your drive, so ordinary effort turns into a struggle for the upper hand.",
   "navigation":"Aim your considerable power at what you are building, not at winning against the people around you."},
 "jupiter-saturn":{"theme":"how you balance growth and caution",
   "fused":"Expansion and discipline are closely joined in you, so you build in a realistic way but swing between hope and doubt. You want to grow and to be safe at once, which can make you ambitious and hesitant on the same day.",
   "flowing":"Optimism and structure cooperate in you, so you grow in steady, well-built ways and can pace a long climb.",
   "friction":"The pull between wanting more and playing it safe can stall you, so your timing feels off and openings pass while you weigh them.",
   "navigation":"Let ambition and patience take turns, and build your growth so that it can actually last."},
 "jupiter-uranus":{"theme":"your appetite for freedom and breakthrough",
   "fused":"You carry a taste for sudden growth and liberation, so you are drawn to the new and impatient with the settled. This makes you forward-looking, though restlessness can pull you off course before anything has had time to mature.",
   "flowing":"Growth and change move together in you, so you stay open, hopeful, and quick to seize a genuine opening.",
   "friction":"Impatience for change can outrun what is sustainable, so you may overturn something workable in search of something newer.",
   "navigation":"Welcome what is new, and give your breakthroughs the time they need to become real."},
 "jupiter-neptune":{"theme":"your idealism and imagination",
   "fused":"Faith and imagination are closely joined in you, so you dream large and feel drawn toward something greater than daily life. This makes you compassionate and visionary, though it can also lose the plot in idealism or wishful hope.",
   "flowing":"Imagination and hope feed each other in you, giving you a generous, inspired outlook that lifts other people too.",
   "friction":"Unrealistic hopes can set you up for disappointment, so the gap between the dream and the fact can be hard to meet.",
   "navigation":"Let your vision lift you, and keep one foot on the ground so the dream has somewhere to land."},
 "jupiter-pluto":{"theme":"your ambition and drive to transform",
   "fused":"Ambition and depth are closely joined in you, so you aim big and dig deep, with the power to remake things on a large scale. This is formidable, though it can overreach or harden into a hunger for control.",
   "flowing":"Growth and depth cooperate in you, so you can transform and achieve at a scale others find daunting.",
   "friction":"Obsession, excess, or a hunger for power can distort your aims, so the drive to grow becomes a drive to dominate.",
   "navigation":"Aim your considerable drive at something worth building, and keep the hunger in proportion."},
 "saturn-uranus":{"theme":"how you hold structure and change together",
   "fused":"Discipline and rebellion are closely joined in you, so you both respect structure and need to break it. This lets you reform things from the inside, though you may feel a constant tension between holding on and breaking free.",
   "flowing":"Discipline and innovation support each other in you, so you can change what needs changing without losing your footing.",
   "friction":"The pull between security and freedom can grind in you, so you feel torn between keeping what is safe and tearing it down.",
   "navigation":"Change what genuinely needs to change, and keep the parts of the structure that are actually working."},
 "neptune-saturn":{"theme":"how you hold dreams and reality together",
   "fused":"Ideals and structure are closely joined in you, so you try to give your dreams a real shape, though doubt and disillusion visit along the way. At your best you make the imagined practical; at your worst you let fear talk you out of the vision entirely.",
   "flowing":"Vision and discipline cooperate in you, so you can build something meaningful with both faith and patience.",
   "friction":"Dreams and hard limits can collide in you, so disappointment or a vague, hard-to-name fear can weigh on what you are trying to build.",
   "navigation":"Give your dream a real structure, and let patience rather than doubt carry it forward."},
 "pluto-saturn":{"theme":"your endurance and capacity to withstand pressure",
   "fused":"Commitment and depth are closely joined in you, so you are durable and serious, able to hold up under weight that would break other people. That strength is real, though it can harden into grim control or a refusal to bend at all.",
   "flowing":"Discipline and transformation cooperate in you, so you can change at a deep level and still hold your shape.",
   "friction":"Control, fear, or heavy testing can concentrate in you, so you may meet pressure by clamping down rather than adapting.",
   "navigation":"Let hardship deepen your commitment rather than harden you against everything."},
 "mars-moon":{"theme":"how your feelings and your drive interact",
   "fused":"Feeling and action are closely joined in you, so you react quickly and tend to act on emotion. This makes you passionate and alive, though your temper can flare, and hurt can turn straight into heat before you have thought.",
   "flowing":"Your emotions fuel healthy action, so you can move on what you feel with warmth and courage.",
   "friction":"Your moods and your temper can spark fast, so feeling and reaction arrive together, and you may fire before you have understood what you feel.",
   "navigation":"Name what you feel before it becomes a reaction, so your emotions inform your actions instead of driving them."},
 "moon-venus":{"theme":"how tender and affectionate your emotional nature is",
   "fused":"Feeling and affection are closely joined in you, so you are warm, gentle, and drawn toward comfort and beauty. This makes you nurturing and easy to be near, though you may keep the peace at the cost of saying what is true.",
   "flowing":"Care and love come easily to you, so closeness tends to feel natural and pleasant.",
   "friction":"Your need for comfort and your desire for affection can pull at each other, so you may smooth over what actually needs to be faced.",
   "navigation":"Let your tenderness stay honest, so that comfort does not quietly replace the harder conversation."},
 "moon-saturn":{"theme":"how safe and how guarded your emotional world feels",
   "fused":"Feeling and restraint are closely joined in you, so you are emotionally serious and self-contained, loyal but slow to show what you need. You may have learned early to expect little comfort, and to guard a tenderness you find hard to reveal.",
   "flowing":"Steadiness supports your feelings, so you are dependable and emotionally durable, a safe place for other people and for yourself.",
   "friction":"You may hold your feelings back or expect little warmth, so you guard yourself against a disappointment you have come to assume is coming.",
   "navigation":"Let yourself need people; the steadiness is already there, and asking for comfort will not undo it."},
 "moon-neptune":{"theme":"how sensitive and imaginative your emotional nature is",
   "fused":"Feeling and imagination are closely joined in you, so you are deeply empathic and impressionable, often absorbing the moods around you as if they were your own. This gives you gentleness and intuition, though your edges can blur and you may lose track of what is actually yours.",
   "flowing":"Compassion and intuition feed your feelings, giving you a gentle, artistic sensitivity that other people feel.",
   "friction":"Idealizing or absorbing other people can cloud your emotions, so it is hard to tell your feeling from theirs.",
   "navigation":"Feel with people generously, and keep a boundary you can find when you need to come back to yourself."},
 # generational (both bodies slow): short, and flagged as background
 "neptune-uranus":{"theme":"the generational blend of vision and change you carry",
   "fused":"You carry your generation's mix of imagination and disruption, so you are drawn to new and unconventional ways of seeing.",
   "flowing":"Intuition and originality move together in you, keeping you open to fresh ways of understanding the world.",
   "friction":"Restlessness and idealism can pull you in different directions and unsettle your plans.",
   "navigation":"Let the shared vision inspire you, and keep it tied to your actual, daily life."},
 "pluto-uranus":{"theme":"the generational drive for change you carry",
   "fused":"You carry your generation's charge for radical change, so you are drawn toward overturning what feels stuck.",
   "flowing":"The urge to transform and the urge to break free move together in you, so change tends to come boldly.",
   "friction":"The pressure to overturn things can turn extreme or disruptive, straining whatever stability you have.",
   "navigation":"Direct your appetite for change toward something you actually want to build."},
 "neptune-pluto":{"theme":"the deep generational undercurrent you carry",
   "fused":"You carry a deep generational tone of transformation, felt more as atmosphere than as a personal trait.",
   "flowing":"Profound imagination and depth move quietly beneath your personality.",
   "friction":"Vast, slow change can register in you as an unease larger than yourself.",
   "navigation":"Recognize this as your era, and put your attention on what is personally yours."},
}

def _key(a, b): return "-".join(sorted([a, b]))
def is_allowed(a, b, aspect): return aspect in CONSTRAINTS.get(_key(a, b), ALL5)
def is_authored(a, b): return _key(a, b) in PAIRS

def compose_natal_aspect(a, b, aspect):
    key = _key(a, b)
    if key not in PAIRS or aspect not in CONSTRAINTS.get(key, ALL5):
        return None
    p = PAIRS[key]; A, B = key.split("-")
    val = VALENCE[aspect]
    astro = f"{DISP[A]} {ASPECT_VERB[aspect]} {DISP[B]}"
    generational = A in OUTER_SLOW and B in OUTER_SLOW
    # named fields so the app maps to body/sections deterministically (not by paragraph position,
    # which varies when the generational note is present)
    experience = p[val]
    guidance = p["navigation"]
    note = ("This one is shared by everyone born around your time, so hold it as generational "
            "background rather than something that singles you out.") if generational else None
    paras = [experience]
    if note:
        paras.append(note)
    paras.append(guidance)
    paras.append(f"The astro: {astro}.")
    return {"title": f"{BARE[A]} {ASPECT_WORD[aspect]} {BARE[B]}",
            "eyebrow": {"label": "Natal aspect", "pair": key, "aspect": aspect, "valence": val,
                        "theme": p["theme"], "generational": generational},
            "generational": generational,
            "astro": astro,
            "experience": experience, "guidance": guidance, "note": note,
            "paragraphs": paras,
            "trace": {"pair": key, "aspect": aspect,
                      "sourceKeys": [f"cc/planet/{A}", f"cc/planet/{B}"],
                      "readerAuthority": "composed-reviewed"}}
