#!/usr/bin/env python3
"""
transit_house.py — LONG-TERM house-transit surface (background layer).

One of three transit surfaces:
  1. planetary horoscope  (transiting planet + sign + rising -> house; fast planets ok)
  2. personal transit     (transit aspecting a natal point; the dated activation layer)
  3. long-term house transit  <-- THIS: the 7 slow bodies through a house, the background chapter

Fast planets (Sun/Moon/Mercury/Venus/Mars) are excluded HERE (they belong in surfaces 1 and
2), not because a short transit lacks meaning. House-based copy is gated behind reliable
birth-time data (house cusps depend on birth time).

Each reading is BESPOKE per (body, house) and must, per editorial review:
  - name what the transit makes harder to avoid (p1_theme),
  - give two or three plausible, recognizable experiences (experiences),
  - show both the difficult and the useful expression (difficult, useful),
  - close with a concrete response (response),
  - trace to the reviewed CC / Marie banks (source_keys).

When both this layer and a personal-aspect transit exist, compose in this order: house (area)
-> transiting planet (process) -> natal point (contacted) -> aspect (behavior) -> orb/pass
(timing/intensity).
"""
REQUIRES_BIRTH_TIME = True
ORD = {1:"1st",2:"2nd",3:"3rd",4:"4th",5:"5th",6:"6th",7:"7th",8:"8th",9:"9th",10:"10th",11:"11th",12:"12th"}

# per-planet framing (P1 connective) + duration. Only Saturn is authored so far.
PLANET = {
 "saturn":{"name":"Saturn","duration":"about two and a half years","frame":"a reality check about"},
 "jupiter":{"name":"Jupiter","duration":"about a year","frame":"a season of growth and opportunity in"},
 "uranus":{"name":"Uranus","duration":"about seven years","frame":"a period of disruption and awakening in"},
 "neptune":{"name":"Neptune","duration":"about fourteen years","frame":"a slow dissolving and softening of"},
 "pluto":{"name":"Pluto","duration":"many years","frame":"a deep and thorough transformation of"},
 "chiron":{"name":"Chiron","duration":"one to several years (varies; render calculated dates)","frame":"bringing old insecurities about"},
 "north_node":{"name":"The North Node","duration":"about a year and a half","frame":"a strong pull to grow through"},
}

# bespoke readings: READINGS[body][house]
READINGS = {"saturn": {
 1:{"p1_theme":"responsibility, self-definition, and how seriously you take yourself",
    "experiences":"You may feel more visible, more weighed down, or simply older, and more aware of how you come across. You might take on a role or title that asks you to grow into it. Your body, health, or appearance may ask for more discipline than before.",
    "difficult":"If you have leaned on charm, youth, or other people's approval to know who you are, that can stop working, and you may feel exposed or unsure of yourself.",
    "useful":"Saturn can help you build a sense of self that is earned and genuinely your own. It can also show you where you have avoided your own authority.",
    "response":"Decide who you want to become over the next few years, and start acting like that person in small, consistent ways. Treat your health and your word to yourself as commitments.",
    "source_keys":["ms/article/saturn-enters-aries","cc/aspect-pair/saturn-conjunction-ascendant","cc/house/1"]},
 2:{"p1_theme":"money, security, and what you actually value",
    "experiences":"You may need to get serious about money, cut back, or build a more solid financial base. A source of income may tighten or ask for more effort to sustain. You might question whether what you earn matches what you are worth.",
    "difficult":"If your security has rested on something shaky, borrowed, or unspoken, that can start to feel precarious, and worry about having enough may get louder.",
    "useful":"Saturn can help you build real, durable financial ground and a sense of worth that does not depend on the next purchase or paycheck. It can show you what you genuinely value.",
    "response":"Make a plan you can keep, spend on what lasts, and separate your worth from your bank balance. Build the base slowly and on purpose.",
    "source_keys":["cc/aspect-pair/saturn-square-venus","cc/planet-in-house/saturn-in-2-house","cc/house/2"]},
 3:{"p1_theme":"how you think, learn, and communicate",
    "experiences":"You may take on serious study, commit to learning something demanding, or find your usual chatter slowing into more careful thought. Communication with a sibling or neighbor may need more structure or honesty. You might feel the weight of your words and mean them more.",
    "difficult":"If you have kept things light, avoided hard conversations, or talked around what you mean, that can get harder to sustain, and misunderstandings may need real repair.",
    "useful":"Saturn can help you think and speak with more depth and authority, and finish what you start learning. It can turn scattered curiosity into real expertise.",
    "response":"Commit to one thing worth learning, say the honest thing plainly, and follow through on the conversations you have been putting off.",
    "source_keys":["cc/aspect-pair/saturn-conjunction-mercury","cc/planet-in-house/saturn-in-3-house","cc/house/3"]},
 4:{"p1_theme":"home, family, and your foundations",
    "experiences":"You may take on more responsibility at home or for a family member, or restructure where and how you live. An old family pattern or a parent may ask for your attention. You might feel pulled to build a more secure base, or feel the weight of one that no longer fits.",
    "difficult":"If your sense of home has rested on avoidance, obligation, or an unspoken deal, that can grow heavy, and old family dynamics may resurface to be dealt with.",
    "useful":"Saturn can help you build a home and an inner foundation that genuinely hold you, and settle long-standing family business. It can show you what security actually requires.",
    "response":"Tend the foundation on purpose. Have the family conversation, set the boundary, or make the practical change that gives you solid ground to stand on.",
    "source_keys":["cc/aspect-pair/saturn-square-moon","cc/planet-in-house/saturn-in-4-house","cc/house/4"]},
 5:{"p1_theme":"creativity, romance, and what you do for joy",
    "experiences":"You may get serious about a creative gift and treat it as real work rather than a hobby. A romance may deepen into commitment or reveal that it cannot carry weight. Questions about children, or the responsibility that comes with a child, may come forward.",
    "difficult":"If you have used performance, attention, or fun to avoid something, that can lose its shine, and you may feel blocked, self-critical, or short on joy for a while.",
    "useful":"Saturn can help you build a real body of creative work and a love that can bear weight. It can turn a talent into a craft.",
    "response":"Put steady, unglamorous hours into what you love to make. Let a relationship show you whether it can hold commitment, and take your own joy seriously enough to protect it.",
    "source_keys":["cc/aspect-pair/saturn-conjunction-venus","cc/planet-in-house/saturn-in-5-house","cc/house/5"]},
 6:{"p1_theme":"work, health, and daily routines",
    "experiences":"You may take on more responsibility at work, tighten your routines, or feel the cost of overwork catching up with your body. A health matter may ask for real discipline and attention. The gap between how much you do and how sustainable it is may become clear.",
    "difficult":"If you have run on adrenaline, skipped rest, or held a job or routine together by sheer effort, that can stop working, and something may have to give.",
    "useful":"Saturn can help you build routines and a working life that are genuinely sustainable, and take your health seriously before it forces the issue. It rewards steady, realistic effort.",
    "response":"Fix the routine that is quietly wearing you down. Tend the health matter now, set limits at work, and build days you can actually keep.",
    "source_keys":["cc/aspect-pair/saturn-conjunction-mars","cc/planet-in-house/saturn-in-6-house","cc/house/6"]},
 7:{"p1_theme":"commitment, fairness, and follow-through in your closest relationships",
    "experiences":"You may need to decide whether a partnership is ready for marriage, living together, shared expenses, or a clearer division of responsibility. A recurring disagreement may become harder to smooth over. A partner, close friend, client, or business associate may need firmer agreements about time, money, availability, or who is responsible for what.",
    "difficult":"If a relationship depends on you staying composed, avoiding the difficult conversation, or doing more than your share, that arrangement may become harder to maintain.",
    "useful":"Saturn can help a dependable relationship take on greater responsibility. It can also show you when an agreement needs different terms.",
    "response":"Pay attention to who keeps their word, who is willing to repair what is not working, and whether both lives still have room inside the relationship.",
    "source_keys":["cc/aspect-pair/saturn-conjunction-descendant","cc/planet-in-house/saturn-in-7-house","cc/house/7"]},
 8:{"p1_theme":"trust, shared money, and the balance of power in your closest bonds",
    "experiences":"You may need to sort out joint finances, debt, an inheritance, or who controls shared resources. A deep bond may ask for more honesty about money, sex, or dependence. You might confront a fear of losing control, or the cost of having given too much of it away.",
    "difficult":"If intimacy has run on avoidance, secrecy, or an unequal hold on money or power, that can grow untenable, and what has been buried may surface to be dealt with.",
    "useful":"Saturn can help you build real trust and clear, fair agreements around the things people usually leave unspoken. It can turn a fear of depth into genuine intimacy.",
    "response":"Have the honest conversation about money and power. Face the debt or the dependence directly, and set terms both people can actually live with.",
    "source_keys":["cc/aspect-pair/saturn-square-pluto","cc/planet-in-house/saturn-in-8-house","cc/house/8"]},
 9:{"p1_theme":"belief, direction, and what your life is actually for",
    "experiences":"You may commit to a long course of study, a serious teaching or publishing project, or a demanding journey. A belief you have held loosely may be tested against reality. You might feel the weight of needing your life to mean something and not being sure it does yet.",
    "difficult":"If you have used big ideas, future plans, or constant seeking to avoid the present, that can lose its comfort, and a worldview may need to be rebuilt on firmer ground.",
    "useful":"Saturn can help you turn scattered searching into real knowledge, mastery, or a philosophy you have actually earned. It grounds meaning in experience.",
    "response":"Commit to the course of study or the journey and see it all the way through. Let your beliefs be tested, and keep the ones that survive contact with real life.",
    "source_keys":["cc/aspect-pair/saturn-conjunction-jupiter","cc/planet-in-house/saturn-in-9-house","cc/house/9"]},
 10:{"p1_theme":"career, reputation, and what you want to be responsible for",
    "experiences":"You may reach a serious point in your career: a promotion, a heavier role, a public test, or a reckoning with whether you are on the right path. Your reputation may come under scrutiny. You might feel the full weight of responsibility, or the emptiness of a goal that was never really yours.",
    "difficult":"If your standing has rested on image, shortcuts, or someone else's ambition, that can start to crack, and you may face a slower climb or a public setback.",
    "useful":"Saturn can help you build lasting authority and a career that reflects who you actually are. This is often where long, patient effort finally pays off.",
    "response":"Do the visible, accountable work. Take on the responsibility you are ready for, and let go of a summit you only ever climbed for someone else.",
    "source_keys":["cc/aspect-pair/saturn-conjunction-midheaven","cc/planet-in-house/saturn-in-10-house","cc/house/10"]},
 11:{"p1_theme":"friendship, belonging, and the future you are building toward",
    "experiences":"You may take on responsibility within a group or community, or find your circle thinning to the people who are truly there. A long-held hope may need a realistic plan, or a rethink. You might feel lonely in a crowd, or clearer about who your people actually are.",
    "difficult":"If you have belonged by being useful, agreeable, or always available, that can wear thin, and some connections may fall away.",
    "useful":"Saturn can help you build durable friendships and turn a vague dream about the future into a plan you can actually work. It shows you where you truly belong.",
    "response":"Invest in the friendships that are real and mutual. Give one long-term hope a concrete first step, and stop spending yourself on rooms that only want your usefulness.",
    "source_keys":["cc/aspect-pair/saturn-conjunction-sun","cc/planet-in-house/saturn-in-11-house","cc/house/11"]},
 12:{"p1_theme":"rest, solitude, and what you have been carrying out of sight",
    "experiences":"You may feel a strong pull to withdraw, slow down, or deal with something you have kept hidden, even from yourself. Old grief, guilt, or exhaustion may surface asking to be tended. A quiet, behind-the-scenes chapter may ask more of you than it looks like from the outside.",
    "difficult":"If you have stayed busy to avoid what is underneath, that can get harder to keep up, and the unattended thing may make itself felt.",
    "useful":"Saturn can help you build a real inner life and finally face what you have been outrunning, on your own terms. It lends structure to the parts of you that live in the dark.",
    "response":"Give yourself real rest and quiet. Tend the private thing you have been avoiding, gently and slowly, and let this be a season of repair rather than output.",
    "source_keys":["cc/aspect-pair/saturn-square-neptune","cc/planet-in-house/saturn-in-12-house","cc/house/12"]},
},
"jupiter": {
 1:{"p1_theme":"your confidence, your presence, and how you put yourself forward",
    "experiences":"You may feel more optimistic, more visible, and more willing to take up opportunities that come your way. A fresh start, a new look, or a bigger sense of what you can do may open up. Other people may respond to you more warmly, and doors can open simply because you showed up.",
    "difficult":"The easy pull is to overpromise, overspend, or overestimate what you can take on, and confidence can tip into taking your luck for granted.",
    "useful":"Jupiter can genuinely enlarge your sense of what is possible for you, and give you the nerve to begin something you have wanted for a while.",
    "response":"Say yes to the opportunities that actually grow you, and start the thing you have been putting off. Keep one honest eye on what you are promising and spending.",
    "source_keys":["ms/article/jupiter-in-cancer","cc/aspect-pair/jupiter-conjunction-ascendant","cc/house/1"]},
 2:{"p1_theme":"your income, your resources, and your relationship with money",
    "experiences":"You may see a raise, a new source of income, or a chance to increase what you earn. Money can move more easily, and you may feel more generous or more able to invest in yourself. A shift in how you value your own time and skills may follow.",
    "difficult":"The temptation is to spend as fast as it comes, take on more than you can carry, or assume the good stretch will last forever.",
    "useful":"Jupiter can genuinely expand your resources and your confidence about money, especially if you build on it rather than blow through it.",
    "response":"Say yes to the earning opportunities, and let yourself charge what you are worth. Put some of the growth somewhere that keeps growing instead of spending all of it.",
    "source_keys":["ms/article/jupiter-in-cancer","cc/aspect-pair/jupiter-conjunction-venus","cc/house/2"]},
 3:{"p1_theme":"your learning, your ideas, and your everyday communication",
    "experiences":"You may take a course, start writing or teaching, or find your conversations opening onto bigger ideas. Learning comes more easily, and the right information or connection may arrive at the right time. A sibling or neighbor may share good news or an opportunity.",
    "difficult":"The pull is to scatter across too many interests, talk more than you follow through on, or promise more than you can deliver in your daily commitments.",
    "useful":"Jupiter can genuinely broaden your mind and open doors through what you say, share, and learn.",
    "response":"Say yes to learning something that stretches you, and follow through on the ideas you start. Let your curiosity go somewhere, rather than everywhere at once.",
    "source_keys":["cc/aspect-pair/jupiter-conjunction-mercury","cc/planet-in-house/jupiter-in-3-house","cc/house/3"]},
 4:{"p1_theme":"your home, your family, and your foundations",
    "experiences":"You may move to a bigger or better place, expand your home, or welcome someone into the family. Things can feel warmer and more abundant at home, and support from family or an inheritance may come through. A sense of belonging can deepen.",
    "difficult":"The easy trap is to overextend on a house you cannot quite afford, or to let comfort at home become a reason to stop reaching.",
    "useful":"Jupiter can genuinely enlarge your sense of home and roots, and lift the warmth and support available from family or the past.",
    "response":"Say yes to a home that gives you room to grow, and lean into the family warmth that is offered. Keep the housing decisions within what you can actually sustain.",
    "source_keys":["ms/article/jupiter-in-cancer","cc/planet-in-house/jupiter-in-4-house","cc/house/4"]},
 5:{"p1_theme":"your creativity, your romantic life, and what you do for joy",
    "experiences":"You may fall in love, start a creative project that takes off, or simply feel more playful and alive. A romance can flourish, a talent can find an audience, and pregnancy or a child may come into the picture. Life can feel more generous and fun.",
    "difficult":"The temptation is to overindulge, chase pleasure past the point of good sense, or take a romance or a gamble further than is wise.",
    "useful":"Jupiter can genuinely open your heart and your creative life, and remind you that joy is not a luxury you have to earn.",
    "response":"Say yes to love and to making things for the pleasure of it. Enjoy the abundance without betting more than you can afford to lose.",
    "source_keys":["cc/aspect-pair/jupiter-conjunction-venus","cc/planet-in-house/jupiter-in-5-house","cc/house/5"]},
 6:{"p1_theme":"your work, your health, and your daily routines",
    "experiences":"You may get a better job, more responsibility, or a workload that finally feels worth it. Your health can improve, especially if you build good habits, and a helpful colleague or mentor may appear. Daily life can feel more purposeful.",
    "difficult":"The pull is to take on too much because it is all going well, to overwork, or to overdo a health regimen to the point of strain.",
    "useful":"Jupiter can genuinely improve your working life and your wellbeing, rewarding steady, honest effort with real growth.",
    "response":"Say yes to the better work and the healthier habits, and let a good routine build. Watch for the point where more stops being better.",
    "source_keys":["cc/aspect-pair/jupiter-conjunction-mars","cc/planet-in-house/jupiter-in-6-house","cc/house/6"]},
 7:{"p1_theme":"your closest partnerships",
    "experiences":"You may meet someone significant, deepen a partnership, or find the right collaborator or client arriving with goodwill. An existing relationship can grow warmer and more generous. Marriage, a business partnership, or a meaningful commitment may come into view.",
    "difficult":"The easy trap is to idealize a partner, overpromise, or expect one relationship to carry more than any relationship can.",
    "useful":"Jupiter can genuinely enlarge your relationships and draw the right people toward you, especially when you meet them as an equal.",
    "response":"Say yes to connection and let a good partnership grow. Keep your eyes open, and love the real person rather than the ideal.",
    "source_keys":["cc/aspect-pair/jupiter-conjunction-descendant","cc/planet-in-house/jupiter-in-7-house","cc/house/7"]},
 8:{"p1_theme":"intimacy, shared resources, and your capacity for deep change",
    "experiences":"You may receive support, a loan, an inheritance, or a boost in shared finances. Intimacy can deepen, and you may feel braver about trusting someone with the vulnerable parts of yourself. A psychological breakthrough or a real healing can open up.",
    "difficult":"The temptation is to take on debt or risk you cannot cover, or to assume trust where it has not yet been earned.",
    "useful":"Jupiter can genuinely expand your ability to share, to trust, and to be changed, and it can lift real support through other people's resources.",
    "response":"Say yes to the deeper trust and the shared opportunity, and let yourself receive. Keep the borrowing and the risk inside what you can honestly carry.",
    "source_keys":["cc/aspect-pair/jupiter-conjunction-pluto","cc/planet-in-house/jupiter-in-8-house","cc/house/8"]},
 9:{"p1_theme":"your beliefs, your horizons, and your search for meaning",
    "experiences":"You may travel somewhere that changes you, commit to study, or start teaching or publishing. A new philosophy, faith, or worldview may take hold. The right teacher, book, or journey may arrive at just the right time.",
    "difficult":"The pull is to preach, to promise a grand plan you will not follow through on, or to chase the far horizon while neglecting the life in front of you.",
    "useful":"Jupiter is at home here, and it can genuinely expand your understanding, your faith, and your sense of what your life is for.",
    "response":"Say yes to the journey, the study, or the belief that calls you, and let your world get bigger. Then bring the vision back down into something you actually do.",
    "source_keys":["ms/article/jupiter-in-cancer","cc/planet-in-house/jupiter-in-9-house","cc/house/9"]},
 10:{"p1_theme":"your career and public standing",
    "experiences":"You may get a promotion, public recognition, or a chance to step into a bigger role. Your reputation can grow, mentors or influential people may open doors, and a long climb can suddenly speed up. Ambition can feel rewarded.",
    "difficult":"The easy trap is to overpromise publicly, take on a role you are not ready for, or let a run of success go to your head.",
    "useful":"Jupiter can genuinely lift your career and your public reputation, especially when the growth rests on real ability.",
    "response":"Say yes to the bigger role and let your work be seen. Make sure what you promise in public is something you can actually deliver.",
    "source_keys":["cc/aspect-pair/jupiter-conjunction-midheaven","cc/planet-in-house/jupiter-in-10-house","cc/house/10"]},
 11:{"p1_theme":"your friendships, your community, and your hopes for the future",
    "experiences":"You may find your circle widening, join a group or cause that lifts you, or meet people who open real doors. Friendships can become more generous and rewarding, and a long-term dream may gain momentum and support. The future can feel more possible.",
    "difficult":"The pull is to spread yourself across too many groups, to over-rely on a network, or to promise more to a cause than you can give.",
    "useful":"Jupiter can genuinely enlarge your community and your vision of the future, and gather the right people around a shared hope.",
    "response":"Say yes to the connections and the causes that genuinely lift you, and let a long-term hope grow. Give your energy where it is actually returned.",
    "source_keys":["cc/aspect-pair/jupiter-conjunction-sun","cc/planet-in-house/jupiter-in-11-house","cc/house/11"]},
 12:{"p1_theme":"your inner life, your rest, and what works quietly behind the scenes",
    "experiences":"You may feel a pull toward retreat, spirituality, or quiet inner work that turns out to be surprisingly rich. Support can arrive from unexpected or unseen places, and old burdens may lift. Time alone, or time spent helping others quietly, can feel unusually nourishing.",
    "difficult":"The temptation is to escape into comfort, avoidance, or wishful thinking, or to give so much behind the scenes that you disappear.",
    "useful":"Jupiter can genuinely expand your compassion, your faith, and your inner life, and grace can arrive from places you cannot see.",
    "response":"Say yes to real rest and to the quiet inner work that restores you. Let yourself receive help, and keep some ground so the retreat does not become an escape.",
    "source_keys":["cc/aspect-pair/jupiter-conjunction-neptune","cc/planet-in-house/jupiter-in-12-house","cc/house/12"]},
},
"uranus": {
 1:{"p1_theme":"your identity, your independence, and how you show up",
    "experiences":"You may feel a strong urge to break out of an old version of yourself, change your look, or claim more freedom in how you live. Sudden shifts in your circumstances can push you to become more yourself. You might surprise the people who thought they had you figured out.",
    "difficult":"The risk is throwing off something good along with what genuinely confines you, or becoming so restless that you cannot settle anywhere.",
    "useful":"Uranus can free you into a truer, more independent version of yourself, and shake loose an identity you had outgrown.",
    "response":"Give the urge for change a real outlet before it forces one. Experiment on purpose, and keep what still serves you even as you let the rest go.",
    "source_keys":["ms/article/uranu-retrograde-in-gemini","cc/aspect-pair/uranus-conjunction-ascendant","cc/house/1"]},
 2:{"p1_theme":"your income, your resources, and your sense of security",
    "experiences":"Your finances may become less predictable, with sudden gains, losses, or a change in how you earn. You might break away from a steady but stifling source of income, or find an unconventional way to make money. Your relationship with security itself can shift.",
    "difficult":"The risk is impulsive spending, gambling on a whim, or blowing up a stable situation before you have anything to replace it.",
    "useful":"Uranus can free you from a definition of security that was quietly trapping you, and open genuinely new ways to earn and to value your worth.",
    "response":"Keep a cushion for the surprises, and channel the restlessness into one real experiment rather than a reckless leap. Let your idea of security become more flexible.",
    "source_keys":["cc/aspect-pair/uranus-square-venus","cc/planet-in-house/uranus-in-2-house","cc/house/2"]},
 3:{"p1_theme":"your thinking, your communication, and your daily surroundings",
    "experiences":"Your mind may speed up and reach for new, unconventional ideas, and you might take up a subject that upends how you see things. Communication with siblings or neighbors can change suddenly. A local move or a new technology may shake up your daily rhythm.",
    "difficult":"The risk is scattering into too many novel ideas, speaking before you think, or growing so restless that nothing holds your attention.",
    "useful":"Uranus can spark real originality in how you think and speak, and free your mind from a rut you had stopped noticing.",
    "response":"Follow the genuinely new idea, but ground it in something you finish. Say the honest thing, and let your curiosity break the routine on purpose.",
    "source_keys":["ms/article/uranu-retrograde-in-gemini","cc/planet-in-house/uranus-in-3-house","cc/house/3"]},
 4:{"p1_theme":"your home, your family, and your living situation",
    "experiences":"You may move suddenly, change your living situation, or feel a strong need to break from a family pattern. The stability of home can shift, sometimes through an unexpected event. You might rethink what home even means to you.",
    "difficult":"The risk is uprooting yourself impulsively, or disrupting the family base you actually rely on before you know what you want instead.",
    "useful":"Uranus can free you from a home or a family role that no longer fits, and help you build a living situation that suits who you have become.",
    "response":"If change is coming, take part in it rather than just reacting. Loosen the old family expectation, and give yourself a base that allows for who you are now.",
    "source_keys":["cc/aspect-pair/uranus-square-moon","cc/planet-in-house/uranus-in-4-house","cc/house/4"]},
 5:{"p1_theme":"your creativity, your romantic life, and how you express yourself",
    "experiences":"You may feel a surge of original creative energy, or a sudden, unconventional attraction. A romance can begin or end quickly, and you might want more freedom in how you love or create. Your relationship to fun and self-expression can change.",
    "difficult":"The risk is chasing excitement for its own sake, disrupting a good creative or romantic thing on impulse, or mistaking novelty for real feeling.",
    "useful":"Uranus can unlock a bolder, more authentic creativity, and a way of loving that gives both people room to be themselves.",
    "response":"Make the strange, original thing you actually want to make. Let a relationship have space, and tell the difference between a real spark and simple restlessness.",
    "source_keys":["cc/aspect-pair/uranus-conjunction-venus","cc/planet-in-house/uranus-in-5-house","cc/house/5"]},
 6:{"p1_theme":"your work, your health, and your daily routines",
    "experiences":"Your job or daily routine may change suddenly, sometimes in ways you did not choose. You might break from a rigid schedule, adopt an unconventional way of working, or address a health matter with a new approach. Restlessness with the daily grind can build.",
    "difficult":"The risk is quitting or blowing up a job impulsively, or neglecting your body's real needs in the name of doing things differently.",
    "useful":"Uranus can free you from work and routines that were quietly draining you, and open a healthier, more flexible way of running your days.",
    "response":"Change the routine on purpose rather than by rupture. Experiment with how you work and care for your body, and keep the structure your health still needs.",
    "source_keys":["cc/aspect-pair/uranus-conjunction-mars","cc/planet-in-house/uranus-in-6-house","cc/house/6"]},
 7:{"p1_theme":"your closest partnerships and your need for freedom within them",
    "experiences":"A key relationship may go through sudden change, more distance, or a renegotiation of how much freedom each of you has. You might be drawn to an unconventional partnership, or feel a partner pulling away or waking up. Old relationship rules can stop working.",
    "difficult":"The risk is breaking a good bond over a passing need for space, or provoking a rupture rather than asking for the room you need.",
    "useful":"Uranus can free a relationship from a stale pattern, and help you build partnerships that let both people stay individuals.",
    "response":"Ask for the freedom you need out loud before you act it out. Let a real relationship adapt, and notice whether change is clearing space or just running away.",
    "source_keys":["cc/aspect-pair/uranus-conjunction-descendant","cc/planet-in-house/uranus-in-7-house","cc/house/7"]},
 8:{"p1_theme":"intimacy, shared resources, and the parts of life you cannot fully control",
    "experiences":"Shared finances, debts, or someone else's money may shift suddenly. Intimacy can intensify or change shape, and buried material may surface without warning. You might experience a sudden psychological breakthrough or the end of a way of relating.",
    "difficult":"The risk is upending joint arrangements impulsively, or acting on a sudden intensity before you understand it.",
    "useful":"Uranus can break open a stuck pattern around trust, control, or shared power, and free you to relate more honestly.",
    "response":"Face the shared-money or trust question directly rather than letting it detonate. Let a breakthrough change you, and give sudden intensity a little time before you act.",
    "source_keys":["cc/aspect-pair/uranus-square-pluto","cc/planet-in-house/uranus-in-8-house","cc/house/8"]},
 9:{"p1_theme":"your beliefs, your worldview, and your sense of what is possible",
    "experiences":"A belief you held firmly may suddenly change, and you might be drawn to unconventional ideas, teachers, or places. A sudden trip, a new philosophy, or an eye-opening experience can shift your whole outlook. The future may look different than it did.",
    "difficult":"The risk is swapping one rigid certainty for another, or chasing every new idea without letting any of it take root.",
    "useful":"Uranus can free your mind from an outgrown worldview, and open genuinely new horizons and possibilities.",
    "response":"Let your beliefs be shaken and see what survives. Follow the new horizon that calls you, and stay open without grabbing the first thing that dazzles you.",
    "source_keys":["cc/aspect-pair/uranus-conjunction-jupiter","cc/planet-in-house/uranus-in-9-house","cc/house/9"]},
 10:{"p1_theme":"your career, your direction, and your public role",
    "experiences":"Your career may change suddenly, through an unexpected opportunity, a break from a conventional path, or an abrupt shift you did not plan. You might feel a strong need to do your work on your own terms. Your public role or reputation can take a surprising turn.",
    "difficult":"The risk is quitting or torching a position impulsively, or rebelling against structure you actually still need to get where you want to go.",
    "useful":"Uranus can free you from a career that no longer fits, and open an original, more authentic professional direction.",
    "response":"Steer the change rather than just reacting to it. Move toward work that lets you be yourself, and keep enough structure to land the leap.",
    "source_keys":["cc/aspect-pair/uranus-conjunction-midheaven","cc/planet-in-house/uranus-in-10-house","cc/house/10"]},
 11:{"p1_theme":"your friendships, your community, and your vision of the future",
    "experiences":"Your social circle may change suddenly, with new, unusual people arriving and older ties falling away. You might join or leave a group, or find your hopes for the future taking a new shape. A cause or community can wake something up in you.",
    "difficult":"The risk is dropping loyal friends for the excitement of the new, or scattering your energy across too many groups and causes.",
    "useful":"Uranus can free you into the community and the future vision that genuinely fit who you are becoming.",
    "response":"Let the friendships that no longer fit loosen, and welcome the ones that do. Give one real vision of the future your energy instead of chasing every new scene.",
    "source_keys":["cc/aspect-pair/uranus-conjunction-sun","cc/planet-in-house/uranus-in-11-house","cc/house/11"]},
 12:{"p1_theme":"your inner life, your unconscious patterns, and what works behind the scenes",
    "experiences":"Sudden insights may surface from your inner depths, and hidden things can come to light without warning. You might feel a restless urge to break free of something you cannot quite name, or wake up to a pattern that ran you for years. Old ghosts can suddenly lose their grip.",
    "difficult":"The risk is acting out an unconscious restlessness before you understand it, or disrupting your own inner peace with anxiety you have not traced.",
    "useful":"Uranus can free you from a buried pattern, and let a genuine, liberating insight rise from below the surface.",
    "response":"Give the restlessness some quiet attention rather than acting it out. Follow the insight when it comes, and let an old, hidden pattern finally release.",
    "source_keys":["cc/aspect-pair/uranus-conjunction-neptune","cc/planet-in-house/uranus-in-12-house","cc/house/12"]},
},
"neptune": {
 1:{"p1_theme":"your identity, your image, and how solid you feel in yourself",
    "experiences":"Your sense of who you are may grow softer and less defined, and you might feel more sensitive, impressionable, or uncertain of your edges. Other people may see you through their own projections. A more spiritual or creative identity can slowly emerge.",
    "difficult":"The risk is losing yourself in an image, a role, or someone else's idea of you, or drifting without a clear sense of direction.",
    "useful":"Neptune can dissolve a rigid, over-defended self, and open a softer, more compassionate, more inspired way of being.",
    "response":"Keep gentle contact with what is real and yours. Let the old rigid identity soften, but check your choices against solid ground rather than a dream.",
    "source_keys":["cc/aspect-pair/neptune-conjunction-ascendant","cc/planet-in-house/neptune-in-1-house","cc/house/1"]},
 2:{"p1_theme":"your money, your resources, and what you truly value",
    "experiences":"Your finances may become foggy or hard to track, with money slipping away or arriving in unclear ways. You might feel confused about what you are worth, or drawn to earn through something creative or compassionate. Material security can matter less than it did.",
    "difficult":"The risk is financial confusion, wishful thinking about money, or being deceived or deceiving yourself about what you can afford.",
    "useful":"Neptune can loosen a grip on money that was standing in for security, and reconnect you to what you actually value beyond the material.",
    "response":"Keep clear, honest records precisely because the picture is hazy. Be cautious with anything that sounds too good, and let your values guide what you chase.",
    "source_keys":["cc/aspect-pair/neptune-square-venus","cc/planet-in-house/neptune-in-2-house","cc/house/2"]},
 3:{"p1_theme":"your thinking, your communication, and your everyday mind",
    "experiences":"Your thinking may become more intuitive and imaginative and less linear, and facts can feel slippery. You might find it harder to concentrate, or easier to sense what is unspoken. Communication with those around you can carry more feeling and more room for misunderstanding.",
    "difficult":"The risk is confusion, missed details, or misreading a situation through hope or fear rather than what is actually there.",
    "useful":"Neptune can open a more poetic, intuitive, compassionate way of thinking and communicating.",
    "response":"Double-check the practical details you would rather float past. Trust your intuition, and say what you mean plainly so it is not lost in the fog.",
    "source_keys":["cc/aspect-pair/neptune-conjunction-mercury","cc/planet-in-house/neptune-in-3-house","cc/house/3"]},
 4:{"p1_theme":"your home, your family, and your emotional foundation",
    "experiences":"The ground under you may feel less solid, and home or family life can grow dreamy, confusing, or quietly sad. You might idealize a family member or the past, or feel a longing for a home you cannot quite find. A spiritual sense of belonging can deepen.",
    "difficult":"The risk is confusion or disillusionment at home, a boundary dissolving where you needed one, or an old family sorrow rising to the surface.",
    "useful":"Neptune can soften a hard family history, and open a more compassionate, spiritual sense of what home means.",
    "response":"Keep some structure at home even as feelings run deep. Meet the family sorrow with compassion, and separate the real family from the idealized one.",
    "source_keys":["cc/aspect-pair/neptune-square-moon","cc/planet-in-house/neptune-in-4-house","cc/house/4"]},
 5:{"p1_theme":"your creativity, your romantic life, and your sense of joy",
    "experiences":"Your imagination may open wide, and creative or romantic inspiration can flow. You might fall for someone in an idealized, dreamlike way, or pour yourself into art, music, or a devotion. The line between love and fantasy can blur.",
    "difficult":"The risk is falling in love with an illusion, being disappointed when reality intrudes, or losing yourself in a romance or a fantasy.",
    "useful":"Neptune can raise your creativity to something genuinely transcendent, and open a tender, selfless kind of love.",
    "response":"Pour the inspiration into real work you can finish. Enjoy the romance while checking, gently, whether you love the person or the dream.",
    "source_keys":["cc/aspect-pair/neptune-conjunction-venus","cc/planet-in-house/neptune-in-5-house","cc/house/5"]},
 6:{"p1_theme":"your work, your health, and your daily routines",
    "experiences":"Your daily structure may feel harder to hold, and work can become confusing, disillusioning, or quietly draining. A health matter may be vague or hard to diagnose. You might feel called toward more meaningful, compassionate, or creative work.",
    "difficult":"The risk is fatigue, escapism, or a health issue you overlook because it is hard to pin down, and boundaries at work that quietly dissolve.",
    "useful":"Neptune can lead you toward work that actually feels meaningful, and a gentler, more intuitive relationship with your body.",
    "response":"Keep enough routine to function, and take vague symptoms seriously enough to check. Move your work toward something you can care about.",
    "source_keys":["cc/aspect-pair/neptune-conjunction-mars","cc/planet-in-house/neptune-in-6-house","cc/house/6"]},
 7:{"p1_theme":"your closest relationships and how clearly you see the people in them",
    "experiences":"A close relationship may become more spiritual and compassionate, or more confusing and hard to read. You might idealize a partner, or slowly realize a bond is not what you hoped. The boundaries between you and someone close can blur.",
    "difficult":"The risk is deceiving yourself about a partner, giving until you disappear, or staying attached to who you wish they were rather than who they are.",
    "useful":"Neptune can deepen the compassion and spiritual connection in a real relationship, and teach a selfless kind of love.",
    "response":"See the actual person, not the ideal. Keep your own outline inside the relationship, and be honest with yourself about what is really there.",
    "source_keys":["cc/aspect-pair/neptune-conjunction-descendant","cc/planet-in-house/neptune-in-7-house","cc/house/7"]},
 8:{"p1_theme":"intimacy, shared resources, and the deepest currents of trust",
    "experiences":"Shared finances may grow murky, and you might feel confusion or vulnerability around debt, inheritance, or someone else's money. Intimacy can deepen into something almost mystical, or dissolve boundaries you needed. Psychic or spiritual sensitivity can heighten.",
    "difficult":"The risk is being deceived, or deceiving yourself, around shared money and trust, or losing your boundaries in a merging that costs you.",
    "useful":"Neptune can open a profound, transformative intimacy, and a real capacity to surrender and trust.",
    "response":"Get clear, written terms around any shared money precisely because it feels hazy. Let intimacy deepen while keeping enough of yourself intact.",
    "source_keys":["cc/aspect-pair/neptune-square-pluto","cc/planet-in-house/neptune-in-8-house","cc/house/8"]},
 9:{"p1_theme":"your beliefs, your spirituality, and your search for meaning",
    "experiences":"You may be drawn toward faith, mysticism, or a spiritual quest, and old certainties can dissolve into something larger and less definable. A pilgrimage, a teacher, or a vision may move you. Meaning itself can feel more fluid.",
    "difficult":"The risk is chasing a guru or a belief that turns out to be illusion, or drifting so far into the spiritual that you lose your footing.",
    "useful":"Neptune can open a genuine, humbling sense of the sacred, and a faith that is felt rather than argued.",
    "response":"Follow the spiritual pull while keeping your discernment. Test a teacher or a belief against how it actually lives, not just how it feels.",
    "source_keys":["cc/aspect-pair/neptune-conjunction-jupiter","cc/planet-in-house/neptune-in-9-house","cc/house/9"]},
 10:{"p1_theme":"your career, your public image, and your sense of direction",
    "experiences":"Your career direction may grow foggy, or you might feel disillusioned with a goal you once chased. You could be drawn toward creative, spiritual, or caregiving work. Your public image can become idealized, hard to control, or slowly dissolving.",
    "difficult":"The risk is confusion about your path, a reputation clouded by others' projections, or drifting from a career without a plan for what replaces it.",
    "useful":"Neptune can dissolve an ambition that was never really yours, and draw you toward work with real meaning.",
    "response":"Let go of the goal that has lost its meaning without abandoning your ground entirely. Move, step by step, toward work you can believe in.",
    "source_keys":["cc/aspect-pair/neptune-conjunction-midheaven","cc/planet-in-house/neptune-in-10-house","cc/house/10"]},
 11:{"p1_theme":"your friendships, your community, and your hopes for the future",
    "experiences":"You may be drawn to idealistic groups, spiritual communities, or causes larger than yourself. Some friendships can grow more compassionate, others more confusing or disappointing. Your dreams for the future may become more visionary and less concrete.",
    "difficult":"The risk is being let down by an idealized group or friend, giving too much to a cause, or losing yourself in a collective dream.",
    "useful":"Neptune can connect you to a genuinely inspiring community, and a compassionate vision of the future.",
    "response":"Give your energy to the people and causes that are real, not just idealized. Hold a visionary hope while keeping one practical foot on the ground.",
    "source_keys":["cc/aspect-pair/neptune-conjunction-sun","cc/planet-in-house/neptune-in-11-house","cc/house/11"]},
 12:{"p1_theme":"your inner life, your dreams, and your relationship with the unseen",
    "experiences":"Your inner and spiritual life may open profoundly, with vivid dreams, heightened intuition, and a pull toward solitude or contemplation. Old sorrows may rise gently to be released. You might feel the boundary between you and something larger grow thin.",
    "difficult":"The risk is escapism, confusion, or getting lost in the inner world at the cost of the outer one.",
    "useful":"Neptune is at home here, and it can open a deep, genuine spiritual life, and a compassion that reaches beyond yourself.",
    "response":"Make real space for rest, dreams, and quiet. Let old grief move through you, and keep enough structure that the inner tide does not pull you under.",
    "source_keys":["cc/aspect-pair/neptune-conjunction-neptune","cc/planet-in-house/neptune-in-12-house","cc/house/12"]},
},
"pluto": {
 1:{"p1_theme":"your identity, your power, and how you meet the world",
    "experiences":"You may go through a slow, total transformation of who you are, sometimes triggered by a crisis or a loss. Your presence can intensify, and you might feel compelled to shed an old self entirely. People may respond to a new depth or force in you.",
    "difficult":"The risk is trying to control everything, becoming consumed by a single obsession, or resisting a change that is going to happen anyway.",
    "useful":"Pluto can regenerate you from the ground up, and hand you real, earned personal power.",
    "response":"Let the old self die instead of clinging to it. Face what you would rather avoid, and use the power that comes with real honesty about yourself.",
    "source_keys":["cc/aspect-pair/pluto-conjunction-ascendant","cc/planet-in-house/pluto-in-1-house","cc/house/1"]},
 2:{"p1_theme":"your money, your resources, and your deeper sense of worth",
    "experiences":"Your finances may go through an intense transformation, sometimes including loss and rebuilding. You might confront how you use money for power or security, or face a fear of not having enough. What you truly value can change at the root.",
    "difficult":"The risk is obsessing over money and control, or a financial crisis that forces a reckoning you kept postponing.",
    "useful":"Pluto can rebuild your relationship with money and worth on far more honest, resilient ground.",
    "response":"Look honestly at what money means to you and where you use it for control. Rebuild your security deliberately, and let a crisis teach you what you actually need.",
    "source_keys":["cc/aspect-pair/pluto-conjunction-venus","cc/planet-in-house/pluto-in-2-house","cc/house/2"]},
 3:{"p1_theme":"your thinking, your communication, and how you use your mind",
    "experiences":"Your thinking may deepen and intensify, drawn toward what is hidden, taboo, or psychologically true. A powerful idea can take hold of you. Communication with a sibling or in your daily world may go through a hard, transformative passage.",
    "difficult":"The risk is obsessive thinking, using words to control or wound, or getting locked in a mental power struggle.",
    "useful":"Pluto can give your mind real depth and investigative power, and let you speak truths most people avoid.",
    "response":"Turn the intensity into genuine understanding rather than obsession. Use your words to reveal what is true, and repair the conversations that turned into battles.",
    "source_keys":["cc/aspect-pair/pluto-conjunction-mercury","cc/planet-in-house/pluto-in-3-house","cc/house/3"]},
 4:{"p1_theme":"your home, your family, and your deepest roots",
    "experiences":"Home and family may go through a profound transformation, sometimes through an ending, a move, or a buried family truth coming to light. You might confront old family power dynamics or wounds at their source. What home means to you can be rebuilt from the foundation.",
    "difficult":"The risk is a family power struggle, a controlling grip on the household, or resisting a change to your roots that is already underway.",
    "useful":"Pluto can heal a family pattern at its root, and let you build a home and an inner foundation that are truly your own.",
    "response":"Face the family truth or the buried dynamic directly. Let an old pattern end, and rebuild your foundation on what is honest rather than inherited.",
    "source_keys":["cc/aspect-pair/pluto-square-moon","cc/planet-in-house/pluto-in-4-house","cc/house/4"]},
 5:{"p1_theme":"your creativity, your romantic life, and your self-expression",
    "experiences":"A romance may become intense, consuming, or transformative, and love can bring you face to face with power, jealousy, or deep desire. Your creativity may turn darker, deeper, and more compelling. Questions about children can carry real weight.",
    "difficult":"The risk is obsession, control, or jealousy in love, or a creative intensity that tips into all-or-nothing.",
    "useful":"Pluto can give your creative work real depth and power, and turn love into something genuinely transformative.",
    "response":"Let love change you without letting it consume you. Pour the intensity into creative work, and notice where desire tips into control.",
    "source_keys":["cc/aspect-pair/pluto-conjunction-venus","cc/planet-in-house/pluto-in-5-house","cc/house/5"]},
 6:{"p1_theme":"your work, your health, and your daily life",
    "experiences":"Your work or daily life may go through a deep transformation, sometimes through a crisis, a compulsion, or a complete change of routine. A health matter can force real change. You might confront patterns of overwork, control, or self-neglect at their root.",
    "difficult":"The risk is workaholism, an obsessive routine, or a health crisis that surfaces what you have been ignoring.",
    "useful":"Pluto can rebuild your daily life and your relationship with your body on healthier, more honest ground.",
    "response":"Take the health matter seriously and change the pattern behind it. Let a compulsive routine transform into something that actually serves you.",
    "source_keys":["cc/aspect-pair/pluto-conjunction-mars","cc/planet-in-house/pluto-in-6-house","cc/house/6"]},
 7:{"p1_theme":"your closest partnerships and the balance of power within them",
    "experiences":"A key relationship may transform completely, sometimes through crisis, an ending, or a struggle over power and control. You might attract or become intensely bound to someone. Partnership itself can teach you about your own depths.",
    "difficult":"The risk is a power struggle, jealousy, or a controlling grip that damages a bond you value.",
    "useful":"Pluto can burn away everything false in a relationship, and forge one built on real depth and honesty.",
    "response":"Look honestly at power and control between you. Let what is over end cleanly, and let a real bond be transformed rather than fought over.",
    "source_keys":["cc/aspect-pair/pluto-conjunction-descendant","cc/planet-in-house/pluto-in-7-house","cc/house/7"]},
 8:{"p1_theme":"intimacy, shared resources, and the deepest processes of change",
    "experiences":"You may go through an intense passage around shared money, debt, inheritance, sex, or trust. Deeply buried material can surface, and you might face loss, crisis, or a total psychological rebirth. Power and control in close bonds come to a head.",
    "difficult":"The risk is a power struggle over shared resources, an obsession you cannot release, or clinging to what needs to die.",
    "useful":"Pluto is at home here, and it can work a profound transformation, and a hard-won, unshakable depth.",
    "response":"Face the buried thing and the shared-power question directly. Let go of what is genuinely over, and let yourself be changed all the way down.",
    "source_keys":["cc/aspect-pair/pluto-conjunction-pluto","cc/planet-in-house/pluto-in-8-house","cc/house/8"]},
 9:{"p1_theme":"your beliefs, your worldview, and your search for truth",
    "experiences":"A belief system may be transformed, or destroyed and rebuilt, and you might become intensely absorbed in a philosophy, a cause, or a search for deeper truth. A journey or a course of study can change you profoundly. What your life means can be reforged.",
    "difficult":"The risk is fanaticism, using belief as a form of power, or clinging to a worldview that reality is dismantling.",
    "useful":"Pluto can deepen your understanding to something genuinely powerful, and let you rebuild your beliefs on unshakable ground.",
    "response":"Let a shallow or borrowed belief be destroyed so a truer one can grow. Follow the deep question without turning it into dogma.",
    "source_keys":["cc/aspect-pair/pluto-conjunction-jupiter","cc/planet-in-house/pluto-in-9-house","cc/house/9"]},
 10:{"p1_theme":"your career, your public role, and your relationship with power",
    "experiences":"Your career or public standing may go through a complete transformation, sometimes including a fall and a rebuild. You might rise to real power, or confront how you use it. A reckoning with ambition, control, or reputation can arrive.",
    "difficult":"The risk is a ruthless drive for power, a public downfall, or clinging to a position that has run its course.",
    "useful":"Pluto can rebuild your career from the ground up, and hand you real, earned authority.",
    "response":"Use power honestly, and let a false position fall. Rebuild your public life on what you actually stand for.",
    "source_keys":["cc/aspect-pair/pluto-conjunction-midheaven","cc/planet-in-house/pluto-in-10-house","cc/house/10"]},
 11:{"p1_theme":"your friendships, your community, and your vision of the future",
    "experiences":"Your social circle may transform, sometimes through the intense end of a friendship or a group, or through powerful new alliances. You might confront power dynamics within a community. Your hopes for the future can be reforged around something deeper.",
    "difficult":"The risk is a power struggle within a group, an all-consuming alliance, or clinging to a friendship or dream that needs to end.",
    "useful":"Pluto can clear away the connections that were never real, and bind you to a community and a purpose with genuine depth.",
    "response":"Let the group ties that are over end. Invest in the alliances that are honest, and let a deeper purpose reshape what you are working toward.",
    "source_keys":["cc/aspect-pair/pluto-conjunction-sun","cc/planet-in-house/pluto-in-11-house","cc/house/11"]},
 12:{"p1_theme":"your inner life, your hidden depths, and what you have buried",
    "experiences":"Buried material may surface from the depths of your psyche, sometimes with real force, and you might confront fears, compulsions, or ghosts you have carried for years. A slow, private transformation can remake you from the inside. What has been hidden demands to be faced.",
    "difficult":"The risk is being overwhelmed by what surfaces, or fighting a deep inner change instead of allowing it.",
    "useful":"Pluto can heal something ancient at its root, and free you from a pattern that has quietly run your life.",
    "response":"Face what rises from below, with support if you need it. Let the old, buried thing be transformed, and trust the slow inner work even when it is hard.",
    "source_keys":["cc/aspect-pair/pluto-square-neptune","cc/planet-in-house/pluto-in-12-house","cc/house/12"]},
},
"chiron": {
 1:{"p1_theme":"how you come across and whether you are enough as you are",
    "experiences":"You may become newly self-conscious about your body, your voice, or the impression you make, and assume people are judging what you have barely noticed yourself. You might over-apologize, downplay yourself, or brace for criticism before it arrives. A small comment about how you look or act can land harder than it should.",
    "difficult":"The same self-doubt can show up in situation after situation until you notice how quickly you expect disapproval.",
    "useful":"This period can help you meet yourself with less judgment and stop performing to earn a place you already have.",
    "response":"Notice when you are holding back to avoid attention, and stay present anyway. Let a compliment land without deflecting it, and treat yourself the way you would treat a friend.",
    "source_keys":["ms/article/chiron-retrograde-in-aries","cc/chiron/chiron-in-1-house","cc/house/1"]},
 2:{"p1_theme":"what you are worth and whether you deserve to have enough",
    "experiences":"You may undercharge, hesitate to ask for a raise, or feel a flush of guilt when you want something for yourself. Money situations can stir an old sense of not deserving, even when the numbers are fine. You might tie your worth to what you earn and come up feeling short.",
    "difficult":"The same fear about deserving can surface around different purchases and paychecks until you see the pattern under it.",
    "useful":"This period can help you value yourself apart from what you own or earn, and let yourself want things without apology.",
    "response":"Charge what your time is worth, and let yourself receive without immediately paying it back. Notice when guilt is deciding for you, and choose differently.",
    "source_keys":["cc/chiron/chiron-in-2-house","cc/aspect-pair/chiron-conjunction-venus","cc/house/2"]},
 3:{"p1_theme":"whether your voice matters and whether you are clever enough",
    "experiences":"You may hold back an opinion for fear of sounding stupid, over-explain to prove you belong, or replay a conversation convinced you said the wrong thing. A comment about how you speak or what you know can sting more than expected. You might go quiet exactly where you have the most to say.",
    "difficult":"The same fear about your intelligence can show up across conversations until you notice how often you silence yourself first.",
    "useful":"This period can help you trust that your voice is enough and speak without auditioning for approval.",
    "response":"Say the thing you would normally keep to yourself, and let it be imperfect. Ask a question instead of pretending to know, and stop editing yourself into silence.",
    "source_keys":["cc/chiron/chiron-in-3-house","cc/aspect-pair/chiron-conjunction-mercury","cc/house/3"]},
 4:{"p1_theme":"whether you truly belong and were ever fully cared for",
    "experiences":"You may feel a fresh pang about your upbringing, notice how hard it is to let anyone take care of you, or find an old family dynamic getting under your skin again. Visiting home or dealing with a parent can reopen a familiar ache. You might long for a sense of home you are not sure you ever had.",
    "difficult":"The same feeling of not being fully held can return through family and living situations until you see where it started.",
    "useful":"This period can help you give yourself the steadiness you did not fully get, and build a home that actually feels safe.",
    "response":"Let someone care for you without earning it first. Set the boundary with family you have avoided, and make your space somewhere you genuinely rest.",
    "source_keys":["cc/chiron/chiron-in-4-house","cc/aspect-pair/chiron-square-moon","cc/house/4"]},
 5:{"p1_theme":"whether you are special enough to be seen and enjoyed",
    "experiences":"You may hide a creative project for fear it is not good enough, hold back in a new romance in case you are not wanted, or feel a sting when someone else gets the attention. Being watched or admired can feel exposing rather than fun. You might talk yourself out of joy before you let yourself have it.",
    "difficult":"The same fear of not being enough can block your self-expression again and again until you catch it happening.",
    "useful":"This period can help you create and love more openly, without needing a guarantee that you will be chosen.",
    "response":"Make the thing and share it before you feel ready. Let yourself flirt, play, and be seen, and notice when you are hiding to avoid a no.",
    "source_keys":["cc/chiron/chiron-in-5-house","cc/aspect-pair/chiron-conjunction-venus","cc/house/5"]},
 6:{"p1_theme":"whether you are competent enough and doing enough",
    "experiences":"You may drive yourself past exhaustion to prove your worth, treat a health issue as a personal failure, or feel that whatever you do is never quite enough. Even minor criticism at work can cut deep. You might notice how rarely you let good enough be enough.",
    "difficult":"The same fear of not measuring up can return through jobs and routines until you see how hard you are on yourself.",
    "useful":"This period can help you ease the inner critic and tend your body without needing to earn the right to rest.",
    "response":"Take the health matter seriously and stop treating it as a moral failure. Do the work well, then let it be finished, and rest before you are forced to.",
    "source_keys":["cc/chiron/chiron-in-6-house","cc/aspect-pair/chiron-conjunction-mars","cc/house/6"]},
 7:{"p1_theme":"being chosen and easy to love in your closest relationships",
    "experiences":"You may read too much into a delayed reply, agree to something you do not want because you are afraid they will leave, or pull away once someone matters enough to hurt you. A partner, close friend, or client may show you where you expect rejection before it has happened.",
    "difficult":"The same fear can return through different relationships until you recognize what keeps setting it off.",
    "useful":"This period can help you say what you need without making the other person prove your worth first.",
    "response":"Ask what they meant instead of filling in the answer, say what bothered you before resentment builds, and give ordinary misunderstandings a chance to be clarified while taking repeated dismissal seriously.",
    "source_keys":["cc/chiron/chiron-in-7-house","cc/aspect-pair/chiron-conjunction-descendant","cc/house/7"]},
 8:{"p1_theme":"trusting someone with the parts of you that could be used against you",
    "experiences":"You may keep a partner at arm's length around money, sex, or real dependence, test someone before you let them close, or brace for the moment you get hurt. A situation involving shared finances or deep vulnerability can touch an old fear of being controlled or betrayed. You might hold back the very closeness you most want.",
    "difficult":"The same guardedness can repeat across close bonds until you notice how much you are protecting against.",
    "useful":"This period can help you risk real closeness with someone who has earned it, and let yourself be known.",
    "response":"Let one guarded thing be shared with someone safe. Say the fear out loud instead of acting it out, and notice the difference between real danger and old reflex.",
    "source_keys":["cc/chiron/chiron-in-8-house","cc/aspect-pair/chiron-square-pluto","cc/house/8"]},
 9:{"p1_theme":"whether life has meaning and whether your faith can hold",
    "experiences":"You may feel let down by a belief you once trusted, struggle to find meaning in something that used to steady you, or cling to certainty to avoid the discomfort of not knowing. A crisis or a big question can reopen an old sense that the ground gave way. You might chase answers to outrun the ache.",
    "difficult":"The same disillusionment can return through different beliefs and teachers until you let your search include the ache rather than bypass it.",
    "useful":"This period can help you build a faith honest enough to hold real life, doubt and all.",
    "response":"Let a belief that no longer fits fall away without grabbing the next certainty. Sit with the open question, and keep what survives honest reflection.",
    "source_keys":["cc/chiron/chiron-in-9-house","cc/aspect-pair/chiron-conjunction-jupiter","cc/house/9"]},
 10:{"p1_theme":"whether you are good enough to belong at the top",
    "experiences":"You may downplay an accomplishment, over-prepare to prove you deserve a role, or feel like an impostor even when you are clearly competent. A public setback or a piece of criticism can hit an old nerve about not being enough. You might undercut your own visibility just as it grows.",
    "difficult":"The same inadequacy can resurface through jobs and titles until you notice you are trying to earn a place you already hold.",
    "useful":"This period can help you own your competence and be seen without needing to prove your worth first.",
    "response":"Take the credit you have earned, and let your work speak before you undercut it. Step toward the visible role, and treat one setback as feedback rather than a verdict.",
    "source_keys":["cc/chiron/chiron-in-10-house","cc/aspect-pair/chiron-conjunction-midheaven","cc/house/10"]},
 11:{"p1_theme":"whether you belong or will always be the outsider",
    "experiences":"You may hover at the edge of a group, hold back from joining in case you are not wanted, or feel your difference more sharply in a crowd. An old memory of being left out can flare in a new setting. You might keep people at a distance to avoid being excluded first.",
    "difficult":"The same outsider feeling can return through different groups until you see how often you exclude yourself first.",
    "useful":"This period can help you find the community where your difference is welcome, and let yourself get closer to it.",
    "response":"Say yes to the group that actually wants you, and let yourself be included. Notice when you are keeping your distance to avoid a no, and step in anyway.",
    "source_keys":["cc/chiron/chiron-in-11-house","cc/aspect-pair/chiron-conjunction-sun","cc/house/11"]},
 12:{"p1_theme":"an old, hard-to-name ache you carry out of sight",
    "experiences":"You may feel a low, unexplained sadness rise without an obvious cause, or sense something tender you cannot quite put into words. Old grief can surface in dreams, quiet moments, or when you finally slow down. You might feel more raw and porous than usual, especially around other people's pain.",
    "difficult":"The same buried feeling can keep resurfacing until it is given attention rather than outrun.",
    "useful":"This period can help you meet something old and wordless with real compassion, and turn even the hardest of it into depth.",
    "response":"Give the quiet ache gentle attention, with support if you need it. Make space for rest and reflection, and let yourself feel what you have been too busy to feel.",
    "source_keys":["cc/chiron/chiron-in-12-house","cc/aspect-pair/chiron-conjunction-neptune","cc/house/12"]},
},
"north_node": {
 1:{"p1_theme":"putting yourself first and leading your own life",
    "experiences":"You may feel pulled to start things on your own, be more visible, and want things openly rather than blending in. Opportunities can come that ask you to stand out. The easy pull back toward pleasing others or hiding may feel strong.",
    "difficult":"The temptation is to retreat into relationships or accommodation, letting other people define you rather than risking being yourself.",
    "useful":"The North Node here is growing your capacity to be a self, to lead, and to want things out loud.",
    "response":"Do the thing that puts you forward, even when it feels self-indulgent. Notice when you are hiding inside someone else's needs, and step back into your own life.",
    "source_keys":["ms/article/lunar-nodes-eclipses-2025","cc/node/north-node-in-1-house","cc/house/1"]},
 2:{"p1_theme":"building your own worth and standing on your own resources",
    "experiences":"You may feel pulled to develop real self-sufficiency, earn your own way, and value what is actually yours. Situations can ask you to build security rather than rely on shared or borrowed resources. The pull back toward other people's money or intensity may tug at you.",
    "difficult":"The temptation is to fall back on crises, shared resources, or someone else's power instead of building your own base.",
    "useful":"The North Node here is growing your self-worth, your resourcefulness, and your capacity to stand on your own ground.",
    "response":"Build something of your own, however small. Notice when you are reaching for someone else's resources or drama, and put the energy into your own stability instead.",
    "source_keys":["ms/article/lunar-nodes-eclipses-2025","cc/node/north-node-in-2-house","cc/house/2"]},
 3:{"p1_theme":"learning, listening, and staying curious about your world",
    "experiences":"You may feel pulled to learn, ask questions, and stay curious about your immediate world rather than assuming you already know. Everyday conversations and connections can become the growth edge. The pull back toward your fixed beliefs may feel strong.",
    "difficult":"The temptation is to retreat into what you already believe and stop actually listening or learning.",
    "useful":"The North Node here is growing your curiosity, your open-mindedness, and your engagement with the people right around you.",
    "response":"Ask more than you tell, and let the near world teach you. Notice when you are hiding in certainty, and get curious again.",
    "source_keys":["ms/article/lunar-nodes-eclipses-2025","cc/node/north-node-in-3-house","cc/house/3"]},
 4:{"p1_theme":"tending your home, your roots, and your emotional foundation",
    "experiences":"You may feel pulled to build a real home base, tend family ties, and honor your inner emotional needs rather than only chasing outer achievement. Situations can ask you to show up for private, foundational things. The pull back toward career and status may feel strong.",
    "difficult":"The temptation is to hide in work and public achievement to avoid the vulnerability of home and feeling.",
    "useful":"The North Node here is growing your capacity to nurture yourself, build a foundation, and belong somewhere.",
    "response":"Put real energy into home and the people who are your ground. Notice when you are escaping into achievement, and come back to what actually holds you.",
    "source_keys":["ms/article/lunar-nodes-eclipses-2025","cc/node/north-node-in-4-house","cc/house/4"]},
 5:{"p1_theme":"self-expression, creativity, and heartfelt risk",
    "experiences":"You may feel pulled to create, play, love openly, and let yourself be seen rather than hiding in the group or the plan. Chances to express yourself and take a heartfelt risk can arrive. The pull back toward the crowd, the cause, or detachment may tug at you.",
    "difficult":"The temptation is to retreat into groups, ideals, or cool detachment instead of risking real, personal self-expression.",
    "useful":"The North Node here is growing your creativity, your capacity for joy, and your willingness to be seen.",
    "response":"Make the thing, take the risk, love out loud. Notice when you are hiding in the collective, and let yourself be an individual with a heart.",
    "source_keys":["ms/article/lunar-nodes-eclipses-2025","cc/node/north-node-in-5-house","cc/house/5"]},
 6:{"p1_theme":"the daily work, your health, and being genuinely useful",
    "experiences":"You may feel pulled to build good routines, tend your body, and do the humble, practical work rather than escaping into fantasy or overwhelm. Small acts of service and care can become the growth path. The pull back toward escapism or martyrdom may tug at you.",
    "difficult":"The temptation is to drift, avoid, or lose yourself in confusion instead of showing up for the concrete daily task.",
    "useful":"The North Node here is growing your discipline, your health, and your ability to help in real, grounded ways.",
    "response":"Do the small, useful thing today, and tend your body honestly. Notice when you are drifting or over-giving, and come back to the practical next step.",
    "source_keys":["ms/article/lunar-nodes-eclipses-2025","cc/node/north-node-in-6-house","cc/house/6"]},
 7:{"p1_theme":"relating, cooperating, and truly sharing your life",
    "experiences":"You may feel pulled to open to partnership, cooperation, and real give-and-take rather than doing everything alone. Relationships can become the place you grow. The pull back toward going it alone and self-sufficiency may feel strong.",
    "difficult":"The temptation is to retreat into independence and self-reliance to avoid the vulnerability of needing someone.",
    "useful":"The North Node here is growing your capacity to relate, compromise, and let another person genuinely matter.",
    "response":"Let someone in, and practice real partnership. Notice when you are insisting on doing it all yourself, and choose cooperation instead.",
    "source_keys":["ms/article/lunar-nodes-eclipses-2025","cc/node/north-node-in-7-house","cc/house/7"]},
 8:{"p1_theme":"deep intimacy, shared resources, and letting yourself change",
    "experiences":"You may feel pulled toward deeper intimacy, honest merging, and transformation rather than staying on the safe surface. Situations can ask you to trust, share, and let go of control. The pull back toward comfort, possessions, and the familiar may feel strong.",
    "difficult":"The temptation is to cling to security, stubbornness, or what you own instead of risking real depth and change.",
    "useful":"The North Node here is growing your capacity for intimacy, trust, and genuine transformation.",
    "response":"Let yourself go deeper with someone, and share what you usually hold. Notice when you are clinging to the comfortable, and allow the change that wants to happen.",
    "source_keys":["ms/article/lunar-nodes-eclipses-2025","cc/node/north-node-in-8-house","cc/house/8"]},
 9:{"p1_theme":"expanding your horizons, your beliefs, and your search for meaning",
    "experiences":"You may feel pulled to travel, study, explore new philosophies, and trust a bigger picture rather than getting lost in details or others' opinions. Chances to widen your world can arrive. The pull back toward gossip, overthinking, or scattered facts may tug at you.",
    "difficult":"The temptation is to stay in the weeds of daily information and never reach for the larger meaning.",
    "useful":"The North Node here is growing your faith, your vision, and your willingness to seek what your life is for.",
    "response":"Follow the bigger question, take the trip, study the thing. Notice when you are drowning in detail, and lift your eyes to the horizon.",
    "source_keys":["ms/article/lunar-nodes-eclipses-2025","cc/node/north-node-in-9-house","cc/house/9"]},
 10:{"p1_theme":"your public role, your ambition, and real responsibility",
    "experiences":"You may feel pulled to take on a bigger role in the world, own your ambition, and be accountable for a public direction rather than staying safely at home. Opportunities to lead or be seen can arrive. The pull back toward retreat and the private may feel strong.",
    "difficult":"The temptation is to hide in home, comfort, or old emotional patterns instead of claiming your place in the world.",
    "useful":"The North Node here is growing your competence, your authority, and your willingness to be responsible in public.",
    "response":"Take the visible step and own the ambition. Notice when you are retreating into the familiar, and let yourself be seen doing something that matters.",
    "source_keys":["ms/article/lunar-nodes-eclipses-2025","cc/node/north-node-in-10-house","cc/house/10"]},
 11:{"p1_theme":"your community, your friendships, and a vision bigger than yourself",
    "experiences":"You may feel pulled toward community, friendship, and a shared future rather than the spotlight or personal drama. The right groups and causes can find you. The pull back toward ego, performance, or a single relationship may tug at you.",
    "difficult":"The temptation is to stay in the drama of self-expression or romance instead of contributing to something larger.",
    "useful":"The North Node here is growing your sense of belonging, your friendships, and your investment in a collective future.",
    "response":"Show up for the group and the cause that matter to you. Notice when you are stuck in ego or performance, and give yourself to something bigger.",
    "source_keys":["ms/article/lunar-nodes-eclipses-2025","cc/node/north-node-in-11-house","cc/house/11"]},
 12:{"p1_theme":"surrender, rest, and trusting the unseen",
    "experiences":"You may feel pulled toward inner work, rest, spirituality, and letting go rather than controlling every practical detail. Solitude and reflection can become the growth path. The pull back toward overwork, worry, and micromanagement may feel strong.",
    "difficult":"The temptation is to bury yourself in busywork and criticism to avoid the vulnerability of surrender and trust.",
    "useful":"The North Node here is growing your faith, your compassion, and your ability to let go of what you cannot control.",
    "response":"Make space for rest, reflection, and the inner life. Notice when you are hiding in busyness, and practice trusting what you cannot see.",
    "source_keys":["ms/article/lunar-nodes-eclipses-2025","cc/node/north-node-in-12-house","cc/house/12"]},
}}

def is_authored(body, house):
    return body in READINGS and house in READINGS[body]

def compose_transit_house(body, house):
    if not is_authored(body, house):
        return None
    p, r = PLANET[body], READINGS[body][house]
    # Chiron's orbit is uneven, so no duration is baked into the body (dates render separately)
    if body == "chiron":
        p1 = f"{p['name']} is moving through your {ORD[house]} house, {p['frame']} {r['p1_theme']}."
    else:
        p1 = (f"{p['name']} is moving through your {ORD[house]} house, where it may spend "
              f"{p['duration']}. This is {p['frame']} {r['p1_theme']}.")
    p2 = r["experiences"]
    p3 = f"{r['difficult']} {r['useful']} {r['response']}"
    return {
        "title": f"{p['name']} transiting your {ORD[house]} house",
        "eyebrow": {"label": "Transit", "body": body, "house": house},
        "requires_birth_time": REQUIRES_BIRTH_TIME,
        "paragraphs": [p1, p2, p3],
        "fields": r,
        "trace": {"body": body, "house": house, "sourceKeys": r["source_keys"],
                  "readerAuthority": "composed-reviewed"},
    }
