export type LunarBeatCopy = { title: string; archetypeTitle: string | null; archetypeLore: string | null; body: string };

export const lunarBeatCopyByKey: Record<string, LunarBeatCopy> = {
  "lunation/new-moon/capricorn": {
    "title": "New Moon in Capricorn",
    "archetypeTitle": "Forgotten One's Moon",
    "archetypeLore": "Capricorn begins from neglect, exile, or the sense of being overlooked. The self starts building because no one else seems to be coming. Ambition can grow from deprivation. The person may equate worth with endurance or achievement. Build without letting absence become the whole foundation. Responsibility should not require emotional starvation.",
    "body": "Story position: The beginning. Nobody is watching, and nobody is coming. What you build now, you build for yourself.\n\nCapricorn Season opening: The cycle begins with the Forgotten One, the child no one noticed. Undervalued and overlooked, he starts building his own way up because no one else is coming for him.\n\nIf you've been exhausted from building everyone else's dreams while yours sit untouched, this is your moment. If you've been the responsible one, the reliable one, the one who never drops the ball, this New Moon in Capricorn isn't asking for another achievement to add to your resume. It's asking what YOU actually want to build when no one's watching. When you're not trying to prove your worth through how much you can handle. Your legacy doesn't have to look impressive to anyone else. It just has to be true to you. Stop building from obligation and start building from desire.\n\nWhat structure or goal actually belongs to me, not to who I think I should be?\n\nCapricorn Energy: Discipline, patience, building foundations, long-term vision, integrity"
  },
  "lunation/first-quarter/aries": {
    "title": "First Quarter in Aries",
    "archetypeTitle": "Brigand's Moon",
    "archetypeLore": "The ideal has collided with the imperfect world. Under the anger is bruised belief: a part of the psyche still wants honor, courage, and fairness to be real, but now distrust moves first. Reaction, provocation, testing, striking first, or making someone else pay for disappointment. Anger can become a way to stay ahead of vulnerability. Work with heat without letting it decide the ethics of the moment. The real question is whether the anger belongs to the person in front of you.",
    "body": "Story position: You've hit the silver in the rock. Watch what you abandon to dig, and what you're trying to buy instead of earn.\n\nCapricorn Season lessons under pressure: The Brigand started as an idealist. The world knocked him down too many times, and he turned angry and cynical. Underneath, he still believes in his ideals. He just stopped trusting anyone to live up to them, so he strikes before anyone can strike him.\n\nThe goal you committed to at the New Moon is meeting resistance, and the resistance is making you angry. If you've been snapping at people who aren't the problem, forcing things that need patience, furious at how slow the build is going, the anger isn't proof the plan is wrong. It's proof you still care about it. But anger looking for a target will find one, deserved or not. Slow down before you act. The question isn't whether you're mad. It's whether the person in front of you earned it.\n\nCheck-in: Where is my plan meeting resistance, and am I fighting the obstacle or just fighting?"
  },
  "lunation/full-moon/cancer": {
    "title": "Full Moon in Cancer",
    "archetypeTitle": "Sea Mother's Moon",
    "archetypeLore": "Cancer feeling reaches vastness. The Sea Mother is tidal, protective, overwhelming, generous, and deep. Emotion can become engulfing. The person may confuse being needed with being loved or confuse intensity with safety. Let feeling move like tide instead of flood. Holding does not require swallowing.",
    "body": "Story position: The authority is yours now. Hold the people you're responsible for without letting duty replace tenderness.\n\nCapricorn Season culmination: This Full Moon belongs to the Sea Mother, tidal, protective, generous, and deep. She can hold everyone, and her danger is confusing being needed with being loved.\n\nThe Capricorn ambitions of this season are meeting Cancer's emotional wisdom, and something's got to give. If you've been building and climbing and achieving, but your soul is asking \"for what? for who?\" this Full Moon illuminates where success has been chosen over softness, achievement over actual nourishment. You can't keep pushing yourself this hard and calling it self-care. Your emotional needs aren't weakness. They're wisdom. It's time to stop building empires on empty hearts.\n\nAxis Integration – Capricorn-Cancer: How can I build success that actually feeds my soul instead of depleting it? This axis teaches that true achievement includes emotional well-being, family, and home. Your professional structure must support your emotional sanctuary.\n\n🕯️ Integration: How can I build success that actually feeds my soul instead of depleting it?"
  },
  "lunation/last-quarter/libra": {
    "title": "Last Quarter in Libra",
    "archetypeTitle": "Judge's Moon",
    "archetypeLore": "Libra meets consequence through evidence, fairness, ruling, and accountability. The Judge asks what the record shows. Fairness can harden into merciless judgment. The person may become attached to being right, lawful, or justified. Hold evidence and mercy together. Accountability is not the same as punishment.",
    "body": "Story position: The respect didn't come the way you wanted. Check what you're withholding and what score you're keeping.\n\nCapricorn Season cycle reflection: The Judge is the Black Knight given real authority. He finally has the power to punish wrongdoers, with everyone's approval behind him. His failing is that he becomes rigid and merciless. He calls his verdicts fairness, but his old anger is doing much of the judging, and he secretly enjoys handing down the sentence.\n\nThe Full Moon showed you what your ambition has been costing your heart. Now you're in the judge's seat, ruling on the season: what worked, what failed, and who is to blame. The trap of this Moon is believing your judgments are fair when your feelings are doing the judging. That might be the harsh sentence on yourself, the grudge against whoever didn't carry enough, or the case you've already decided. The work isn't to ignore the feelings. It's to notice them before you sentence anyone, including yourself, and to leave room for mercy, which is the Judge's blind spot.\n\nCheck-in: How much of what I'm calling fair this season is actually a feeling?"
  },
  "lunation/new-moon/aquarius": {
    "title": "New Moon in Aquarius",
    "archetypeTitle": "Father's Son Moon",
    "archetypeLore": "Aquarius begins as the Golden Boy: the Father's heir and favorite, told from the start that he is special, even a genius. He accepts the role, and as an Air Moon he stays out of touch with his own feelings while living up to it. Being the chosen one can replace knowing oneself. The person may perform the inherited role fluently while having no idea what they actually feel. Enjoy the gifts without mistaking the role for the self. The inheritance is a starting point, not an identity.",
    "body": "Story position: You're the favorite, playing the part well. Find out what you actually feel underneath it.\n\nAquarius Season opening: The cycle begins with the Father's Son, the favorite who is told from the start that he is special. He plays the part so well that he loses track of what he actually feels.\n\nIf you've been playing by rules that were never yours, following paths that made sense to everyone except you, this New Moon in Aquarius is your permission slip to stop fitting in where you were never meant to belong. If you've spent so long making yourself smaller to be understood, editing your truth to be palatable, it's time to stop. What if your weirdness is exactly what the world needs? What if the thing that makes you different is the thing that makes you valuable? Stop apologizing for seeing things differently. Your revolution doesn't need anyone's approval.\n\nWhat truth have I been hiding because I thought it was too much, too different, too revolutionary?\n\nAquarius Energy: Innovation, independence, humanitarian vision, authentic rebellion, collective service"
  },
  "lunation/first-quarter/taurus": {
    "title": "First Quarter in Taurus",
    "archetypeTitle": "Woodcutter's Moon",
    "archetypeLore": "Making something real requires labor and cost. The Woodcutter clears the woods he came from to make room and money, choosing his own survival over what he used to belong to. The forced bargain. The person may be pushed into trading long-term values for short-term survival or comfort, and then judge themselves or others for the trade. Look at each compromise plainly and build a thought-through code of values. Know what must be cleared and what must be preserved.",
    "body": "Story position: The break. Make it a decision, not a reaction, and keep the friends who can argue with you.\n\nAquarius Season lessons under pressure: The Woodcutter was once part of the forest. He needed more room for his garden, so he cut down the woods he came from, and the trees became firewood, furniture, and money. He wasn't cutting from greed. He chose his own survival over what he used to belong to.\n\nThe revolution you committed to at the New Moon has met its real cost. Having the vision was easy. Building it costs something. If you've hit the part where the change requires labor, money, and giving up something real to pay for it, this Moon is asking you to look at the bargain plainly. Every trade you make to feel more secure says something about your priorities. Don't feel superior about your compromises and don't punish yourself for them. Just see them clearly.\n\nCheck-in: What am I clearing, selling, or using up to make this vision real, and is the trade worth it?"
  },
  "lunation/full-moon/leo": {
    "title": "Full Moon in Leo",
    "archetypeTitle": "Queen's Moon",
    "archetypeLore": "Leo sovereignty becomes visible. The Queen carries dignity, presence, command, and the power of being recognized. Authority can become entitlement. The person may expect loyalty without offering generosity. Lead from warmth and responsibility, not from hunger for the throne. True presence steadies the room.",
    "body": "Story position: The community is real. Stay human inside the collective.\n\nAquarius Season culmination: This Full Moon belongs to the Queen, who carries dignity, presence, and the power of being recognized. Her danger is putting pride ahead of letting anyone close.\n\nThe Aquarius revolutionary energy of this season meets Leo's demand for authentic self-expression, and suddenly it's clear: you can't create authentic change while performing confidence. This Full Moon is showing where there's been leading from ego instead of truth. Where applause has been sought instead of impact. Real leadership doesn't need everyone's approval. It needs your full, honest, messy humanity. Stop performing authenticity and start living it.\n\nAxis Integration – Aquarius-Leo: How can I lead with my real self instead of my polished persona? This axis teaches that true leadership serves both individual expression and collective evolution. Your personal revolution can inspire others to find their own.\n\n🕯️ Integration: How can I lead with my real self instead of my polished persona?"
  },
  "lunation/last-quarter/scorpio": {
    "title": "Last Quarter in Scorpio",
    "archetypeTitle": "Madwoman's Moon",
    "archetypeLore": "Scorpio intensity has become too much to contain alone. Grief, obsession, fear, and pressure overflow. The person may isolate at the exact moment support is needed. Suspicion can make help feel humiliating. Let outside support enter the crisis. Survival here requires not fighting every demon alone.",
    "body": "Story position: They cast you out for saying it. Don't stay anywhere you must hide what you believe.\n\nAquarius Season cycle reflection: The Madwoman fought every battle alone, and this time the thing she fought was stronger than she was. What saved her was the realization she resisted the longest: she could not recover alone. The people she once helped were the ones who brought her in from the rain.\n\nYou've been carrying this season alone, and the Full Moon showed you how tired you are. The Madwoman's story is the extreme version of what happens next: she held everything in until it broke her, and only then let anyone help. This Moon asks you to learn from her before you get there. If what you're holding, the work, the worry, the feelings you haven't said out loud, is getting close to more than you can contain, that's the signal. You don't have to wait for a breaking point. Tell someone what's heavy while it's still manageable. Letting steady people help you is not weakness. In her story, it's what saved her.\n\nCheck-in: What am I carrying by myself that has become too heavy, and who has a steady enough grip to help?"
  },
  "lunation/new-moon/pisces": {
    "title": "New Moon in Pisces",
    "archetypeTitle": "Dreamer's Moon",
    "archetypeLore": "Pisces begins in image, sensitivity, dream, and porous imagination. The Dreamer feels what has not yet become form. The boundary between intuition and fantasy may blur. The person may drift before choosing what is real enough to follow. Honor the dream without abandoning embodiment. The beginning needs a vessel.",
    "body": "Story position: Half in the other world. Honor the dream and give it a vessel.\n\nPisces Season opening: The cycle begins with the Dreamer, the child who lives half in another world and feels things before they take form.\n\nIf you've been holding it all together for so long that you've forgotten what it feels like to let go, to trust, to stop managing every outcome, this New Moon in Pisces is asking you to loosen your grip on the steering wheel. You don't have to have all the answers. You don't have to know exactly where you're going. Sometimes the bravest thing you can do is admit you're lost and let yourself be guided. Your intuition has been trying to tell you something, but you've been too busy being strong to listen. It's okay to not know. It's okay to feel your way forward.\n\nWhat am I desperately trying to control that's actually asking me to surrender?\n\nPisces Energy: Intuition, surrender, compassion, creativity, spiritual flow, unconditional love"
  },
  "lunation/first-quarter/gemini": {
    "title": "First Quarter in Gemini",
    "archetypeTitle": "Liar's Moon",
    "archetypeLore": "Language reaches crisis. Words can now bend reality, soften truth, distort facts, or turn imagination into manipulation. The person may improve the story until truth disappears. Half-truths, omissions, and convenient explanations become tempting. Notice where language is being used to escape consequence. The repair begins with naming what is actually true.",
    "body": "Story position: The giving has crossed the line. Give cleanly and keep enough to live on.\n\nPisces Season lessons under pressure: On the Liar's Moon, words start to mean whatever gets the result. Small exaggerations turn into polished lies, the lies get rewarded, and soon the liar is lying to himself too, struggling to remember which version he told to whom.\n\nThe surrender you committed to at the New Moon asked you to stop managing every outcome. Under this Moon, everyone's words get a little slippery: a truth gets softened to keep things smooth, a detail gets left out, a story improves slightly with each retelling. This isn't about being a liar. It's about the small ways we all bend the story when something feels hard to face. The exercise for this Moon is simple: notice one thing you've been telling yourself lately that makes something easier to avoid, and look at what's underneath it. Facing that one thing is the whole work.\n\nCheck-in: What was said versus what is true, including in my own version of events?"
  },
  "lunation/full-moon/virgo": {
    "title": "Full Moon in Virgo",
    "archetypeTitle": "Spinner's Moon",
    "archetypeLore": "Virgo craft becomes visible as thread, pattern, and careful work. The Spinner shows how small motions create fate. The pattern can become compulsive. The person may keep spinning because stopping would reveal exhaustion. See the whole cloth, not only the thread. The detail matters because it belongs to a larger form.",
    "body": "Story position: Stop being drained. Open up and let the mercy come through you instead.\n\nPisces Season culmination: This Full Moon belongs to the Spinner, the first of the Fates, whose small, careful, repeated motions create the thread of a life.\n\nThis Full Moon is done with perfectionism. Done with using \"improvement\" as punishment. If you've been trying to perfect your way to worthiness, organize your way to peace, routine your way to healing — this Full Moon is showing you: you can't hate yourself into a version you'll love. You can't criticize yourself into growth. Your healing doesn't need to be perfect. It just needs to be honest.\n\nAxis Integration – Pisces-Virgo: What would change if I approached my healing with compassion instead of criticism? This axis teaches that true service flows from love, not perfectionism. Your spiritual surrender needs grounded daily practice, but without rigid control.\n\n🕯️ Integration: What would change if I approached my healing with compassion instead of criticism?"
  },
  "lunation/last-quarter/sagittarius": {
    "title": "Last Quarter in Sagittarius",
    "archetypeTitle": "Hunter's Moon",
    "archetypeLore": "Sagittarius meets the consequence of pursuit. The Hunter asks whether the target still matters or whether the chase has taken over. Being right or reaching the target can become more important than relationship, humility, or truth. Review the aim. A path that once held meaning may need to be released or redirected.",
    "body": "Story position: Nothing left, and fog everywhere. Stop forcing clarity and rest near the strong.\n\nPisces Season cycle reflection: In the book, the Philosopher becomes the Hunter when the world rejects his beliefs, and the rejection cuts deepest when it comes from people who once believed alongside him. Because he needs to be right, he stops sharing his beliefs and starts hunting the people who question them, treating disagreement as something to be stamped out.\n\nHis story is the warning for this part of the season. This season's New Moon asked you to loosen your grip and trust the process; now check what you've been chasing while calling it trust. If the pursuit still has momentum but you can't remember the last time you asked whether the target matters, this is his Moon. There's a point where defending the belief stops being about the belief and starts being about winning. Lower the bow long enough to look at what you're aiming at.\n\nCheck-in: Does the target still matter, or has the chase become the point?"
  },
  "lunation/new-moon/aries": {
    "title": "New Moon in Aries",
    "archetypeTitle": "Infant's Moon",
    "archetypeLore": "This is the raw beginning of the zodiacal cycle: life arriving before it knows itself. The Infant is hungry, direct, trusting, and urgent. It has not yet learned strategy, restraint, disappointment, or self-control. Wanting can feel like entitlement. Need can become demand. The person may expect life to respond immediately because the desire feels so alive. Keep the courage and immediacy, but learn that impulse is not the same as permission. Trust matters, but so does restraint.",
    "body": "Story position: Everything is new and the wanting is immediate. Start before you talk yourself out of it, but wanting isn't permission.\n\nAries Season opening: The cycle begins with the Infant, brand new and hungry, wanting everything now, before strategy or restraint exist.\n\nThis New Moon doesn't care about your five-year plan. It's not interested in what makes sense or what's practical. It wants to know what makes you feel ALIVE. If you've been waiting for permission, for the right time, for things to feel less scary — this New Moon is showing you that the only permission you need is your own. If you've spent years being who you needed to be to survive, this is about who you want to become. Stop waiting to be ready. You were born ready. The fear you feel? That's not a warning. It's confirmation that this matters.\n\nWhat would I start immediately if I stopped waiting for permission?\n\nAries Energy: Courage, initiation, leadership, pioneering spirit, authentic action, fearless beginning"
  },
  "lunation/first-quarter/cancer": {
    "title": "First Quarter in Cancer",
    "archetypeTitle": "Weeping Moon",
    "archetypeLore": "Emotional safety breaks open. The Weeping Moon carries grief, family pain, body memory, and the feeling that finally comes through. Pain may collapse inward. The person may retreat into mood, silence, or private hurt rather than asking for care. Let feeling be information without letting it become a locked room. Grief needs contact as well as privacy.",
    "body": "Story position: The world hit back and the anger is up. Check whether the person in front of you earned it.\n\nAries Season lessons under pressure: The Weeping Moon belongs to the Orphan, who lost home and mother and built walls around herself. Part of the wall was protection. Part of it was a test, to see if anyone cared enough to get through it.\n\nThe bold beginning you claimed at the New Moon is moving fast, and the feelings are catching up. If grief, family weight, or your own tired body has surfaced right in the middle of your momentum, that's not the plan failing. That's the feeling finally breaking through because you're actually in motion. Don't run over it, and don't wall it off either. The Orphan's walls kept her safe, but they also kept out everyone who could have helped. Let the feeling come, and let one person through. The way back is small: one small comfort at a time, not one big fix, because big sweeping changes are what caused the loss in the first place.\n\nCheck-in: What feeling is my momentum running over?"
  },
  "lunation/full-moon/libra": {
    "title": "Full Moon in Libra",
    "archetypeTitle": "Artist's Moon",
    "archetypeLore": "Libra beauty becomes visible through proportion, art, harmony, and the arrangement of parts into form. Beauty can become surface management. The person may polish appearance while avoiding what feels unfair. Let beauty reveal truth, not conceal it. Harmony is strongest when it has integrity.",
    "body": "Story position: Fight in the open, for something worth protecting.\n\nAries Season culmination: This Full Moon belongs to the Artist, who turns feeling into visible form. Her danger is polishing the surface while avoiding what feels unfair.\n\nThe Aries courage of this season meets Libra's need for harmony, and you're learning: real peace includes your truth. If you've been starting a new chapter but worrying about who you're leaving behind, this Full Moon shows you that the right people will support your growth, not guilt you for it. You don't have to choose between authenticity and relationships. The ones that matter will make room for who you're becoming.\n\nAxis Integration – Aries-Libra: How can I honor my new beginning without abandoning the relationships that truly matter? This axis teaches that personal courage can enhance relationships when expressed with consideration for others.\n\n🕯️ Integration: How can I honor my new beginning without abandoning the relationships that truly matter?"
  },
  "lunation/last-quarter/capricorn": {
    "title": "Last Quarter in Capricorn",
    "archetypeTitle": "Miser's Moon",
    "archetypeLore": "Capricorn meets consequence through scarcity, control, and fear of loss. The Miser withholds resources because worth has become tangled with what is stored. Time, money, effort, or responsibility can be hoarded. The person may hold too tightly because letting go feels like losing proof of value. Review what fear is protecting. Security that cannot circulate becomes a prison.",
    "body": "Story position: The fight is over but the habits aren't. Start the healing without a schedule.\n\nAries Season cycle reflection: The Miser began as the Grandfather who worked for his family out of duty and expected respect in return. When the respect didn't come the way he wanted, he withheld the money instead, using it to punish and steer the people he loved.\n\nThe Full Moon showed you that the right people support who you're becoming. The Miser is what happens when you don't trust that. If you've been carrying everything yourself this season, the money, the time, the responsibilities, and holding it all tighter because letting anyone help feels unsafe, this is his Moon. The Miser gave for years and didn't get the respect he expected back, so he started keeping score and withholding. Underneath is a fear that providing is the only thing that makes him valuable. The way out isn't giving more. It's giving without keeping score: letting people help you, and letting your giving come with no bill attached.\n\nCheck-in: What am I withholding, and what appreciation am I waiting for?"
  },
  "lunation/new-moon/taurus": {
    "title": "New Moon in Taurus",
    "archetypeTitle": "Dryad's Moon",
    "archetypeLore": "Taurus begins as living nature: rooted, sensory, quiet, and not separate from the green world. The Dryad belongs to the body, the land, and what can be touched. The self may resist change because the world is experienced as something to endure rather than alter. Need can become silent, stubborn, or wordless. Stay connected to the body and the earth without becoming passive inside discomfort. Belonging does not mean immobility.",
    "body": "Story position: You belong to the body and the land. Start with what's real enough to touch.\n\nTaurus Season opening: The cycle begins with the Dryad, who belongs to the body, the land, and what can be touched, not yet separate from the living world.\n\nIf you've been undervaluing yourself for so long that it feels normal, accepting less because you didn't want to seem difficult, giving discounts on your worth because someone made you feel like you were asking for too much — this New Moon in Taurus is here to remind you that your worth isn't negotiable. It's not up for debate. You don't have to earn it through endless giving or prove it through exhaustion. Your value exists whether anyone sees it or not. Stop apologizing for having standards. Stop shrinking to make others comfortable with your abundance.\n\nWhat would I build if I actually believed I was worth it?\n\nTaurus Energy: Self-worth, stability, patience, sensuality, building value, embodied wisdom"
  },
  "lunation/first-quarter/leo": {
    "title": "First Quarter in Leo",
    "archetypeTitle": "Actor's Moon",
    "archetypeLore": "Leo identity becomes performance. The Actor learns to shape the self around what the audience wants to see. Applause can become the steering wheel. The person may keep editing themselves until sincerity is hard to locate. Notice where visibility has become a mask. The point is not to stop performing, but to stop disappearing into the role.",
    "body": "Story position: The bargain point: something real gets cleared or sold to keep going. See the trade plainly.\n\nTaurus Season lessons under pressure: The Actor got so good at becoming what the audience wanted that he lost track of where the roles ended and he began. Every part used a real piece of him, and over time those pieces stopped being his.\n\nThe worth you committed to building at the New Moon is meeting an audience, and the audience has opinions. If you've caught yourself shaping the build around what gets applause, the version that photographs well, the progress that impresses, this is his Moon. You know how to become what the room wants. It works, so you keep doing it, and each time it costs a little more of you. Somewhere in there is a line between adjusting for the audience and disappearing into them, and this Moon is when you find out which side you're on.\n\nCheck-in: What would I sell myself for?"
  },
  "lunation/full-moon/scorpio": {
    "title": "Full Moon in Scorpio",
    "archetypeTitle": "Priestess's Moon",
    "archetypeLore": "Scorpio depth becomes ritual, sacred power, mystery, and communion with what lies underneath. Mystery can become control. The person may use depth to hold power over others. Let the mystery transform rather than dominate. Power is cleanest when it serves truth.",
    "body": "Story position: The harvest is visible and there's enough to hold others. Give without owning.\n\nTaurus Season culmination: This Full Moon belongs to the Priestess, keeper of what lies underneath. Her power is depth, and her danger is using it to hold power over others.\n\nThe Taurus worth-building energy of this season meets Scorpio's transformative fire, and everything hidden comes to light. This Full Moon is exposing where there's been accepting less because you didn't think you deserved more. Where undervaluing has been disguised as humility. The pain around worth? It's not telling you you're not enough. It's showing you where you've been believing lies about your value. Time to burn those stories down.\n\nAxis Integration – Taurus-Scorpio: What pain about my worth am I ready to transform into power? This axis teaches that true worth includes both material stability and emotional authenticity.\n\n🕯️ Integration: What pain about my worth am I ready to transform into power?"
  },
  "lunation/last-quarter/aquarius": {
    "title": "Last Quarter in Aquarius",
    "archetypeTitle": "Heretic's Moon",
    "archetypeLore": "Aquarius meets rejection. The group brands the message as unacceptable, and the person must decide what truth is worth exile. Being cast out can become identity. The person may cling to opposition even when the field changes. Hold the truth without needing rejection to prove it. Freedom includes leaving the old audience behind.",
    "body": "Story position: Do the accounting. Keep what's worth the price and release what isn't.\n\nTaurus Season cycle reflection: Unlike the Rebel, who never really belonged anywhere, the Heretic finally found his group. Then he said something the group couldn't accept, and they cast him out.\n\nThe Full Moon burned down the lies about your value. Now comes the group's verdict on the new you. If owning your worth has put you at odds with people you belonged to, the family that liked you better when you were smaller, the friends who liked you better when you asked for less, this is his Moon. Losing a home you fought to earn hurts more than never having one. But the rule is firm: never stay somewhere you have to hide what you believe to keep your place. There is always another group, and if there isn't, there is the strength to stand alone.\n\nCheck-in: What do I believe that I've been hiding to keep my place?"
  },
  "lunation/new-moon/gemini": {
    "title": "New Moon in Gemini",
    "archetypeTitle": "Little Brother's Moon",
    "archetypeLore": "Gemini begins as curiosity, mimicry, quick perception, and the early play of language. The Little Brother learns by watching, copying, asking, and trying words on. Attention may scatter before meaning forms. The person may keep moving from stimulus to stimulus without absorbing the lesson. Let curiosity become connection, not just motion. Questions are seeds when they are allowed to deepen.",
    "body": "Story position: Everything is a question. Learn by asking and trying words on.\n\nGemini Season opening: The cycle begins with the Little Brother, who learns by watching, copying, asking questions, and trying words on.\n\nIf you've been telling the same stories about yourself for years — the ones that keep you small, safe, understood — what if those stories were never true? This New Moon in Gemini is asking you to examine the narrative you've been living in. The one where you're always fine, always handling it, never needing too much. If you've edited yourself for so long that you don't remember your real voice, it's time to find it again. Stop explaining yourself to people who are committed to misunderstanding you. Your truth doesn't need to make everyone comfortable.\n\nWhat story about myself am I ready to stop telling, and what truth am I ready to speak instead?\n\nGemini Energy: Communication, curiosity, learning, adaptability, authentic expression, mental flexibility"
  },
  "lunation/first-quarter/virgo": {
    "title": "First Quarter in Virgo",
    "archetypeTitle": "Counting Moon",
    "archetypeLore": "Virgo measurement reaches crisis. The Counting Moon tracks, corrects, measures, and can become trapped in what is wrong. Fixing becomes delay. The person may keep counting flaws because moving forward would expose the unfinished thing. Correct what matters and release the rest. Precision should support movement, not replace it.",
    "body": "Story position: The words have bent. Find the one lie you've told yourself and face what's under it.\n\nGemini Season lessons under pressure: The Accountant shut himself into a small, ordered room where everything was numbered and nothing was out of place. No mess got in, and no people did either. At night he counted his own faults, got overwhelmed, and closed the book.\n\nThe new story you started telling at the New Moon has hit the details, and the details are multiplying. If you've been measuring, tracking, correcting, polishing the process so hard that nothing ships, this is his Moon. There's a version of order that improves the work, and a version that's just a locked room where nothing chaotic gets in, including people. All that counting, and what has it improved? Fix what's actually broken, then finish one thing even though it isn't perfect.\n\nCheck-in: Is the measuring improving anything, or has the process become the point?"
  },
  "lunation/full-moon/sagittarius": {
    "title": "Full Moon in Sagittarius",
    "archetypeTitle": "Priest's Moon",
    "archetypeLore": "Sagittarius belief becomes visible as faith, teaching, ritual, and spiritual or philosophical authority. Conviction can become certainty that demands agreement. The person may confuse faith with being right. Let belief stay alive enough to be humbled. Truth does not need domination.",
    "body": "Story position: Tell the story so it reveals the truth instead of replacing it.\n\nGemini Season culmination: This Full Moon belongs to the Priest, whose belief becomes visible as faith and teaching. His danger is certainty that demands agreement.\n\nThe Gemini communication focus of this season meets Sagittarius wisdom, and suddenly small stories feel too tight. This Full Moon is showing that your voice is meant for bigger stages, wider circles, deeper impact. If you've been keeping your message small because you were afraid of being wrong — what if your truth could free someone else? What if your story is exactly what someone needs to hear? Stop whispering what's meant to be declared.\n\nAxis Integration – Gemini-Sagittarius: How can my personal truth serve a bigger purpose than I imagined? This axis teaches that meaningful communication combines curiosity with wisdom, details with vision. Your voice can inform AND inspire.\n\n🕯️ Integration: How can my personal truth serve a bigger purpose than I imagined?"
  },
  "lunation/last-quarter/pisces": {
    "title": "Last Quarter in Pisces",
    "archetypeTitle": "Moon of Lost Souls",
    "archetypeLore": "Pisces meets exhaustion, confusion, dissolution, and spiritual overwhelm. The soul is tired from trying to keep caring without limits. Fog can become paralysis. The person may keep forcing clarity while the cycle is asking for mercy and release. Stop trying to solve what is dissolving. Release can be an act of sanity.",
    "body": "Story position: Look at what your words built. Test your own framing the way you test everyone else's.\n\nGemini Season cycle reflection: The Lost Soul gave care to everyone who needed it, and the need never stopped coming. Now she has nothing left, and even daydreaming doesn't help anymore.\n\nHer emptiness is where this season can land if the output never stops. The Full Moon asked you to declare your message on a bigger stage. Now look at how much all that talking, explaining, and adjusting has drained you. If clarity isn't coming and forcing it is making you more tired, not more certain, this is her Moon, and the answer is not more effort. Hope comes back through other people: the ones still strong, still doing the work, still winning sometimes. Stop trying to figure it out. Rest until your energy comes back on its own.\n\nCheck-in: Where do I need to stop forcing an answer and rest?"
  },
  "lunation/new-moon/cancer": {
    "title": "New Moon in Cancer",
    "archetypeTitle": "Mother's Daughter Moon",
    "archetypeLore": "Cancer begins inside belonging, mothering, lineage, family atmosphere, and emotional inheritance. The self forms through being held or not held. Identity may become fused with family feeling. The person may inherit moods, needs, or loyalties without knowing what belongs to them. Honor the root without being swallowed by it. Care begins with knowing whose feeling is whose.",
    "body": "Story position: The self is still woven into the family feeling. Learn whose feeling is whose.\n\nCancer Season opening: The cycle begins with the Mother's Daughter, whose identity is still woven into her mother's. The self forms through being held or not held.\n\nIf you've been everyone's safe space while having nowhere to land yourself — the strong one, the caretaker, the one who holds it all together — this New Moon in Cancer is asking what it would look like to create safety for yourself. Not the kind where you manage everyone's emotions so there's no conflict. Real safety. Where you can fall apart without apologizing. Where you can need without feeling guilty. If you've been so busy nurturing everyone else that you forgot you deserve care too, this is your reminder. Your needs aren't an inconvenience. They're valid.\n\nWhat kind of emotional safety have I been giving everyone else that I need to give myself?\n\nCancer Energy: Emotional safety, nurturing, intuition, home, family, protective care, deep feeling"
  },
  "lunation/first-quarter/libra": {
    "title": "First Quarter in Libra",
    "archetypeTitle": "Black Knight's Moon",
    "archetypeLore": "Libra harmony reaches crisis. Resentment, imbalance, and conflict emerge beneath politeness or idealized agreement. The person may maintain the appearance of fairness while privately sharpening a sword. Courtesy becomes cover for anger. Name the imbalance before it becomes a crusade. Honesty is kinder than hidden resentment.",
    "body": "Story position: The loss broke through. Let the feeling come, and let one person past the wall.\n\nCancer Season lessons under pressure: The Black Knight got tired of watching unfair people go unpunished, so he started punishing them himself. His problem is rules without mercy, and his rules keep changing, so last week's friend becomes this week's enemy.\n\nHis Moon shows up in your ordinary arrangements, not on a battlefield. The safety you committed to at the New Moon is testing your relationships. If there's resentment underneath the politeness, an imbalance hiding inside an agreement that was supposed to be even, this is his Moon. The pressure comes from the gap between the ideal and what's actually happening. Don't keep smoothing it over, and don't swing to rules without mercy either. Name the imbalance plainly. That's all you need to do.\n\nCheck-in: What imbalance is hiding inside the agreement?"
  },
  "lunation/full-moon/capricorn": {
    "title": "Full Moon in Capricorn",
    "archetypeTitle": "Grandmother's Moon",
    "archetypeLore": "Capricorn authority becomes elder care, memory, family structure, and practical wisdom held by the matriarchal figure. Duty can become emotional distance. Care may be given through structure while tenderness is withheld. Let wisdom include warmth. Authority can protect without becoming cold.",
    "body": "Story position: You can hold everyone. Don't confuse being needed with being loved.\n\nCancer Season culmination: This Full Moon belongs to the Grandmother, the matriarch whose care comes through structure. Her danger is duty that withholds tenderness.\n\nThe Cancer emotional focus of this season meets Capricorn structure, and it becomes clear: you've been building walls when you meant to build foundations. This Full Moon illuminates where the need for security became a prison. Where protecting yourself became isolating yourself. You can create stability without sacrificing vulnerability. You can be successful without being hard. Your softness isn't weakness — it's the source of your strength.\n\nAxis Integration – Cancer-Capricorn: What structures do I need that support my heart instead of armoring it? This axis teaches that emotional health requires both nurturing and discipline. Your career and public life must support your inner sanctuary.\n\n🕯️ Integration: What structures do I need that support my heart instead of armoring it?"
  },
  "lunation/last-quarter/aries": {
    "title": "Last Quarter in Aries",
    "archetypeTitle": "Survivor's Moon",
    "archetypeLore": "The fight has left marks. The Survivor is no longer proving courage through battle; now the work is to face the wound and learn what healing requires. Old fight responses can keep running after the danger has passed. Anger may go underground and reappear as withdrawal, tension, or sudden explosion. Admit the wound without making it the whole identity. Surviving is not only endurance; it is learning how to live after impact.",
    "body": "Story position: Loss again, as an adult this time. Build something from the grief or the house goes quiet.\n\nCancer Season cycle reflection: The Survivor is the Soldier home from the war, wounded, surrounded by people who expect him to get over it on a schedule. He's angry at them for that, and angry at himself for not being able to.\n\nThe Full Moon showed you the difference between walls and foundations. Now look at the fighter who built the walls. If the hard time is over but the survival habits haven't stopped, staying guarded, keeping people at a distance, holding the anger in until it finally bursts, this is his Moon. Those habits did their job. The courage this Moon asks for is different from the courage that got you through it. It's admitting that you were hurt, that it still affects you, and starting to heal even though healing is slow and there's no promise about how long it will take. You don't have to be ashamed of how you survived. You just don't have to keep living that way.\n\nCheck-in: Which survival moves am I still running that I no longer need?"
  },
  "lunation/new-moon/leo": {
    "title": "New Moon in Leo",
    "archetypeTitle": "Sun Child's Moon",
    "archetypeLore": "Leo begins as innocent radiance. The Sun Child wants to play, create, be loved, and shine before self-consciousness enters. Joy can become demand for attention. The person may expect applause simply because expression feels alive. Keep the warmth without making the room responsible for it. Real radiance gives as well as receives.",
    "body": "Story position: Shine before self-consciousness arrives. Play first.\n\nLeo Season opening: The cycle begins with the Sun Child, who wants to play, create, and be loved, shining before self-consciousness arrives.\n\nIf you've been dimming your light to make others feel more comfortable with their darkness, playing small so no one feels threatened, hiding your joy because someone once made you feel like it was too much — this New Moon in Leo wants you to stop apologizing for shining. Your brightness isn't arrogance — it's authenticity. You don't need permission to take up space, to be seen, to celebrate yourself. The world doesn't need another person pretending to be less than they are. It needs you, fully expressed, unapologetically radiant.\n\nWhat part of myself have I been hiding because I thought it was \"too much\"?\n\nLeo Energy: Authentic confidence, creative expression, heart-centered leadership, joy, generous spirit, natural radiance"
  },
  "lunation/first-quarter/scorpio": {
    "title": "First Quarter in Scorpio",
    "archetypeTitle": "Executioner's Moon",
    "archetypeLore": "Scorpio's stored anger finally gets an approved target, and judging feels good. Then he notices some of the condemned are not guilty, and one day a case comes where he knows the ruling is wrong and must choose between speaking for mercy and keeping the job. Enjoying finality. The person may condemn faster and forgive slower because the punishing feels justified. Learn to forgive, and check every strike before swinging. The defining moment of this Moon is choosing mercy when the ruling is wrong.",
    "body": "Story position: The masks are winning. Decide what you'd sell yourself for.\n\nLeo Season lessons under pressure: The Executioner finally got an approved target for a lifetime of stored anger, and punishing wrongdoers felt good. Then he noticed that some of the people sent to him weren't guilty, and one day a case came where he knew the ruling was wrong.\n\nClaiming your light at the New Moon put you in a position of power, and now something is up for judgment: a project, a relationship, a commitment that may deserve to end. Ending it will feel justified, maybe even satisfying. That feeling is exactly what this Moon asks you to examine. The Executioner's lesson isn't about swinging faster. It's about the day he realized the ruling was wrong and had to choose between speaking up for mercy and keeping his job. So before you end anything, ask whether it truly deserves to end, or whether you just have permission to be angry. If it deserves it, end it and take responsibility for the ending. If it doesn't, have the courage to say so, even when everyone expects you to swing.\n\nCheck-in: Is this ending deserved, or do I just have permission to be angry?"
  },
  "lunation/full-moon/aquarius": {
    "title": "Full Moon in Aquarius",
    "archetypeTitle": "Friendship Moon",
    "archetypeLore": "Aquarius becomes visible through community, chosen kin, group identity, and the social field. Friendship can become ideology or distance. The person may value the group while avoiding intimacy. Let community stay human. Collective vision needs actual relationship.",
    "body": "Story position: Rule with warmth. Don't let pride keep people at a distance.\n\nLeo Season culmination: This is the Friendship Moon, where connection blossoms as community and chosen family. Its danger is valuing the group while avoiding real closeness.\n\nThe Leo authenticity of this season meets Aquarius innovation, and you see it clearly: you don't have to choose between being yourself and belonging. This Full Moon shows that uniqueness IS contribution. If you've been trying to fit into communities that require you to be less of yourself — your people are waiting for exactly who you are, not who you think you should be. Stop betraying yourself to belong somewhere that was never home.\n\nAxis Integration – Leo-Aquarius: How can my authentic self serve the collective without sacrificing what makes me unique? This axis teaches that true creativity serves both personal joy and collective evolution.\n\n🕯️ Integration: How can my authentic self serve the collective without sacrificing what makes me unique?"
  },
  "lunation/last-quarter/taurus": {
    "title": "Last Quarter in Taurus",
    "archetypeTitle": "Merchant's Moon",
    "archetypeLore": "Value is tested through exchange. The Merchant asks what something costs, what it returns, and whether the trade still makes sense. Everything can become a transaction. The person may mistake price for worth or keep paying for something because stopping would mean admitting the cost. Separate true value from sunk cost. What is worth keeping should feed life, not just prove endurance.",
    "body": "Story position: The throne question. Some things cost less handed over than lost in a fight.\n\nLeo Season cycle reflection: The Merchant started earning money for a good cause, and then the earning became the cause. He is the one with resources, and his job is to hold them well.\n\nThe Full Moon handed your work to the crowd. Now the bill comes due. If this season used you up, if energy, money, and pieces of yourself got traded for visibility, this is his Moon, and it's time to do the accounting. Everything on the table has a price and a return: the projects, the commitments, the work of keeping up appearances. Some of it is worth keeping. Some of it stopped being worth the price a while ago. Keep the first kind and let go of the second.\n\nCheck-in: What was worth the price this season, and what stopped being worth it?"
  },
  "lunation/new-moon/virgo": {
    "title": "New Moon in Virgo",
    "archetypeTitle": "Maiden's Moon",
    "archetypeLore": "Virgo begins in self-containment, privacy, discernment, and the wish to remain whole and unspoiled. Purity can become isolation or fear of mess. The person may avoid contact because contact complicates the system. Protect the self without turning life into contamination. Discernment should serve participation.",
    "body": "Story position: Whole in yourself. Start simple and private.\n\nVirgo Season opening: The cycle begins with the Maiden, whole in herself, private and discerning, preferring her own company and her own space.\n\nIf you've been using perfectionism as armor — thinking if you could just get it right, be good enough, organized enough, disciplined enough, then you'd finally feel worthy — this New Moon in Virgo is calling you out. Your worth doesn't come from your productivity. Your value isn't measured in how perfectly you can perform wellness. This is about creating routines that actually nourish you, not ones that look good on social media. Stop punishing yourself with self-improvement. Start caring for yourself with compassion.\n\nWhat would my daily life look like if it was built from self-love instead of self-improvement?\n\nVirgo Energy: Sacred routine, body wisdom, practical service, healthy discernment, devotional practice, functional beauty"
  },
  "lunation/first-quarter/sagittarius": {
    "title": "First Quarter in Sagittarius",
    "archetypeTitle": "Seeker's Moon",
    "archetypeLore": "Sagittarius belief reaches crisis. The path is questioned, the truth is searched for, and doubt becomes part of the journey. Doubt can become constant escape from commitment. The person may keep looking for a wider view to avoid the next concrete step. Let questioning refine the path, not erase it. Truth needs motion and honesty.",
    "body": "Story position: The counting has taken over. Fix what's broken and let one imperfect thing out the door.\n\nVirgo Season lessons under pressure: The Seeker knows she's looking for something real but doesn't know what it is or which direction it's in. She piles up experiences, one belief system after another, and each gives her something, but never the thing.\n\nThe practice you built at the New Moon has raised a bigger question: is this even the right path? If the doubt has arrived, second-guessing the routine, researching alternatives, wondering whether the whole direction is off, this is her Moon, and the doubt is not failure. It's part of checking whether the path is right. The searching is the life, not a delay before the life starts. Just learn to tell the difference between experiences worth having and detours that will damage you. Ask the question and follow the answer, even if it redirects you.\n\nCheck-in: Is the doubt information, or is it avoidance?"
  },
  "lunation/full-moon/pisces": {
    "title": "Full Moon in Pisces",
    "archetypeTitle": "Healer's Moon",
    "archetypeLore": "Pisces compassion becomes visible as mercy, forgiveness, and spiritual medicine. Healing can become saviorhood. The person may take responsibility for pain that is not theirs to cure. Offer mercy without losing center. Healing is relationship, not rescue fantasy.",
    "body": "Story position: You're at the center of the web. See the whole cloth, not just the thread.\n\nVirgo Season culmination: This Full Moon belongs to the Healer, who stops being drained by others and lets something larger carry the mercy through him. His danger is taking responsibility for pain that is not his to cure.\n\nThis Full Moon is washing away the need to have it all figured out. The Virgo practices of this season meet Pisces surrender, and you finally understand: control is an illusion. If you've been trying to perfect your way to peace — peace comes from accepting the mess. From trusting the mystery. From letting yourself be human. This Full Moon is your invitation to stop managing the universe and start trusting it.\n\nAxis Integration – Virgo-Pisces: What would change if I trusted the process instead of trying to control it? This axis teaches that true healing combines practical action with spiritual faith. Your daily routines become sacred when infused with love and surrender.\n\n🕯️ Integration: What would change if I trusted the process instead of trying to control it?"
  },
  "lunation/last-quarter/gemini": {
    "title": "Last Quarter in Gemini",
    "archetypeTitle": "Magician's Moon",
    "archetypeLore": "Language shows its consequence. The Magician's knowledge gives him power over how things are seen and decided, and he concludes that no one can be trusted with that power except himself. A justification arrives at every step. Self-exempting arrogance. The person may be trapped inside their own framing, applying standards to everyone but themselves, until the repeated explanation becomes a spell that limits what is possible. Review the words that built the situation, and submit your own framing to the same test you give everyone else's. Change may begin by changing the story that has been treated as fact.",
    "body": "Story position: Pick up the scissors. Say the necessary no and let them resent it.\n\nVirgo Season cycle reflection: The Magician is the Scribe after he discovers writings that promise power. He uses that power in small ways first, then bigger ones, with a good reason ready at every step. His mistake is believing he alone can handle it responsibly, and never stopping to ask whether what he's doing with it is actually good.\n\nThis season asked you to build your daily life from love instead of fear, and the words you use are part of that: how you describe yourself, your situation, and the people in it. Language is a quiet power. Call yourself lazy for long enough and you start acting like it. Describe someone as difficult for long enough and every conversation with them proves it. Some of what happened this season was shaped by how it was worded. So review your words the way the Magician should have reviewed his power. Ask what each description has created, whether it's actually true, and whether the goal behind it is a good one. Keep the descriptions that hold up against the facts. Retire the ones that only hold up because you keep repeating them.\n\nCheck-in: What has my version of events created, and does it match the facts?"
  },
  "lunation/new-moon/libra": {
    "title": "New Moon in Libra",
    "archetypeTitle": "White Knight's Moon",
    "archetypeLore": "Libra begins with noble ideals about fairness, romance, rescue, and the beautiful possibility of relationship. Idealism can flatten real people into roles. The person may rescue in order to avoid seeing complexity. Let fairness include truth. A noble relationship has to survive contact with imperfection.",
    "body": "Story position: The ideals are bright. Let fairness include truth.\n\nLibra Season opening: The cycle begins with the White Knight, full of ideals about fairness and rescue, wanting to do right and correct wrongs.\n\nIf you've been keeping the peace by silencing your needs, being the understanding one, the flexible one, the one who never asks for too much — this New Moon in Libra is showing you that real harmony includes your voice. Real balance honors your needs too. If you've been so focused on being easy to love that you forgot to ask if these relationships are actually loving YOU, it's time to reassess. Stop negotiating your worth. Stop accepting crumbs and calling it compromise. You deserve partnerships that meet you where you are.\n\nWhat truth have I been swallowing to keep the peace, and what boundary needs to be spoken?\n\nLibra Energy: Authentic relating, diplomatic truth, balanced partnerships, graceful boundaries, cooperative fairness"
  },
  "lunation/first-quarter/capricorn": {
    "title": "First Quarter in Capricorn",
    "archetypeTitle": "Miner's Moon",
    "archetypeLore": "The Miner abandons the climb when he spots treasure in the rock, telling himself the wealth will make people respect him. Finishing the climb would have earned the respect he now plans to buy. Buying what has to be earned. Endurance turns into isolation, excuses pile up, and pessimism keeps him digging in the dark. Do work that is worthwhile even when no one sees it, until no one seeing it stops mattering. Not every hard thing is valuable because it is hard.",
    "body": "Story position: The politeness has cracked. Name the imbalance plainly.\n\nLibra Season lessons under pressure: The Miner was a climber who reached the top, saw higher peaks ahead, and then spotted silver in the rock. He abandoned the climb to dig, telling himself the money would make people respect him. Finishing the climb would have earned the respect he's now trying to buy.\n\nThe partnership you committed to at the New Moon has turned into work, and the work is heavier and lonelier than it looked at the start. If you're deep in the tunnel, carrying the load, telling yourself the payoff will finally earn you the respect or security you're after, this is his Moon. Watch out for trying to buy what has to be earned, and watch the excuses that keep you digging in the dark. Work that you know is good, even when no one sees it, is the way out.\n\nCheck-in: What am I carrying alone, and what buried thing makes it worth it?"
  },
  "lunation/full-moon/taurus": {
    "title": "Full Moon in Taurus",
    "archetypeTitle": "Earth Mother's Moon",
    "archetypeLore": "Taurus abundance becomes visible as nourishment, fertility, comfort, beauty, and the ability to hold life. Holding can become smothering or possessive. The desire to provide may slide into defining others by what they receive. Let abundance support life without turning love into ownership. Nourishment is strongest when it does not trap.",
    "body": "Story position: Turn the love into form. Let beauty reveal, not conceal.\n\nLibra Season culmination: This Full Moon belongs to the Earth Mother, whose generosity feeds and holds everyone. Her danger is letting providing slide into ownership.\n\nThe Libra relating focus of this season meets Taurus values, and the truth becomes clear: you can't build sustainable relationships by abandoning your values. This Full Moon shows where there's been compromising on things that aren't negotiable. Where flexibility has been applied to things that needed to be firm. Real harmony honors everyone's worth — including yours. Stop negotiating your non-negotiables.\n\nAxis Integration – Libra-Taurus: What values do I need to stop compromising on in my relationships? This axis teaches that sustainable partnerships require both cooperation and individual worth.\n\n🕯️ Integration: What values do I need to stop compromising on in my relationships?"
  },
  "lunation/last-quarter/cancer": {
    "title": "Last Quarter in Cancer",
    "archetypeTitle": "Widow's Moon",
    "archetypeLore": "Cancer meets loss. The Widow holds grief, memory, absence, and what remains after something changes. The past can become more alive than the present. The person may keep tending what is gone because letting go feels like betrayal. Grieve honestly while staying available to what remains. Memory can guide without freezing life.",
    "body": "Story position: You're on the bench now. Notice how much of your fairness is feeling, and leave room for mercy.\n\nLibra Season cycle reflection: The Widow built her home with great effort, and it emptied out anyway. Her grief can take two shapes: one builds something from what was lost, the other locks the door and lives inside the memories.\n\nHer two kinds of grief are the choice this Moon puts in front of you. The Full Moon revealed the individuals inside the partnership. Now the season closes with what remains. If something about the arrangement has changed or ended, a relationship, a version of it, an expectation you finally released, this is her Moon. Nothing replaces what was lost. But new life is what carries you, and the door has to be open for it to get in.\n\nCheck-in: What am I grieving, and what is the memory asking me to build?"
  },
  "lunation/new-moon/scorpio": {
    "title": "New Moon in Scorpio",
    "archetypeTitle": "Raging Moon",
    "archetypeLore": "Scorpio begins in raw emotional force. The Raging Moon is the first contact with intensity, survival instinct, and the depth below polite feeling. Feeling can arrive as force before it has language. The person may experience intensity as threat or weapon. Let intensity become information. Power begins by staying present with what is real.",
    "body": "Story position: The feeling arrives as force. Let intensity become information.\n\nScorpio Season opening: The cycle begins with the Raging Moon, the child whose feelings arrive as force before they have words.\n\nIf you've been giving your power away in tiny pieces — through people-pleasing, through silence, through pretending things don't hurt when they do — this New Moon in Scorpio is here for your resurrection. For the part of you that's been buried under \"I'm fine\" and \"It's okay.\" If you've been so afraid of your own intensity that you've been living at half-strength, hear this: your depth isn't too much — it's your superpower. Your intensity isn't wrong — it's your truth. Stop apologizing for feeling deeply. Start reclaiming what you've given away.\n\nWhat power have I been giving away that I'm ready to take back?\n\nScorpio Energy: Transformation, authentic power, emotional alchemy, intimate truth, regeneration, fearless depth"
  },
  "lunation/first-quarter/aquarius": {
    "title": "First Quarter in Aquarius",
    "archetypeTitle": "Rebel Moon",
    "archetypeLore": "Aquarius reaches the crisis of refusal. The system, rule, group, or inherited model no longer fits, and disruption becomes necessary. Rebellion can become reflex. The person may break the structure because it is there, not because it is wrong. Make the break a decision, not a reaction. A better system needs more than refusal.",
    "body": "Story position: The axe is in your hand. Check the strike, and speak for mercy when the ruling is wrong.\n\nScorpio Season lessons under pressure: The Rebel throws out everything connected to the old authority, including the parts that worked. A rebel who never questions his own rules grows up to be the same tyrant he overthrew. What saves him is friends he respects enough to let them disagree.\n\nThe power you reclaimed at the New Moon is turning against the structures around it, and the urge is to burn the whole system down. If you're ready to refuse everything, the job, the group, the rules, the useful parts along with the broken ones, this is his Moon. Some refusal is overdue. But change for its own sake has casualties. Be clear about what you're breaking from and what you're building instead.\n\nCheck-in: Is this break a decision or a reaction?"
  },
  "lunation/full-moon/gemini": {
    "title": "Full Moon in Gemini",
    "archetypeTitle": "Storyteller's Moon",
    "archetypeLore": "Gemini language becomes visible as story, myth, memory, and shared narrative. The Storyteller reveals how meaning is made through telling. The story can become more important than reality. The person may entertain, explain, or dramatize instead of facing the fact underneath. Tell the story in a way that reveals truth rather than replacing it. Narrative is a vessel, not a disguise.",
    "body": "Story position: The belief is public now. Keep the faith alive enough to be humbled.\n\nSagittarius Season culmination: This Full Moon belongs to the Storyteller, since the Moon returns to Gemini here. The season's belief is tested by how it gets told.\n\nIf you've been keeping your dream at arm's length, thinking about it instead of living it, circling it in thought loops instead of packing for it, this Full Moon is the push. The dream you admitted this season now meets the Gemini Moon: the facts, the questions, the details, the other versions of the story. This axis holds both ends of how we understand our lives. Gemini gathers the information; Sagittarius gives it meaning. Get lost in the details and you never leave the house. Run on faith alone and you never check whether the path matches the map. This Full Moon asks for both: keep the big picture and let the honest questions in. This is also the Moon of expansion, the territory of travel, higher learning, and the step past the comfort zone, and it favors speaking your truth boldly. It turns the light on the stories you tell yourself about your life. You are the author of your story. Release the limiting ones.\n\nAxis Integration – Sagittarius-Gemini: What story do I want to tell about my life? This axis holds facts and faith, details and meaning. The dream needs both the map and the horizon.\n\n🕯️ Integration: What story do I want to tell about my life?"
  },
  "lunation/last-quarter/leo": {
    "title": "Last Quarter in Leo",
    "archetypeTitle": "Usurper's Moon",
    "archetypeLore": "Leo meets the consequence of attention and power. The Usurper asks who gets the throne, who controls the story, and what pride has cost. Recognition can become a fight. The person may cling to control because losing the center feels like losing the self. Review what was genuine and what became a role. Handing something over may cost less than losing it in a fight.",
    "body": "Story position: It got too heavy to hold alone. Let steadier hands help before the breaking point.\n\nScorpio Season cycle reflection: The King built his whole life on the love of his people, and his people turned on him. The deepest cut wasn't the rival who took his place. It was the crowd that watched and walked away. There is a second version of his story: the king who steps down on his own, so his people can eat.\n\nThe Full Moon made the deep work visible in the concrete world. Now comes the question of the throne: who gets the credit, the control, the recognition. If there's a fight brewing over who owns what this season produced, or if something you've been holding is slipping regardless, this is his Moon. Be honest about what you actually want to hold. Some things cost less handed over than lost in a fight, and there is real power in stepping down on your own terms.\n\nCheck-in: What am I holding onto that would cost less handed over than lost in a fight?"
  },
  "lunation/new-moon/sagittarius": {
    "title": "New Moon in Sagittarius",
    "archetypeTitle": "Gypsy's Moon",
    "archetypeLore": "Sagittarius begins as movement, restlessness, and the instinct to leave the known world for a wider horizon. Freedom can become refusal to belong anywhere. The person may leave before learning what the place had to teach. Let movement become experience, not avoidance. The road should widen the self.",
    "body": "Story position: Wander. Let the road pull you.\n\nSagittarius Season opening: The cycle begins with the Gypsy, wandering without a care, pulled toward a wider horizon.\n\nIf you've been playing small because big dreams felt dangerous, because hoping felt like setting yourself up for disappointment — this New Moon in Sagittarius wants you to remember what it feels like to believe in possibility again. If you've been so focused on what's realistic that you forgot what's magical, it's time to expand. Your vision isn't too big — your container has been too small. Stop downsizing your dreams to fit your fears. The world needs your wild hope, your impossible vision, your refusal to think small.\n\nWhat dream have I been afraid to admit I still want?\n\nSagittarius Energy: Visionary expansion, adventurous truth, philosophical wisdom, global perspective, inspired teaching, meaningful exploration"
  },
  "lunation/first-quarter/pisces": {
    "title": "First Quarter in Pisces",
    "archetypeTitle": "Martyr's Moon",
    "archetypeLore": "Pisces compassion reaches crisis through sacrifice. She gives past self-preservation, and the giving feels worthwhile. The hidden side of sacrifice. Quiet superiority toward the people who need her, power in being needed, and a debt the receivers can feel and resent. The person may give past the line, confuse suffering with love, or disappear into someone else's need. Give cleanly, with no hidden agenda, and decide what can be given without starving yourself. Compassion needs edges.",
    "body": "Story position: The crisis of faith. The searching is the life; ask the question honestly.\n\nSagittarius Season lessons under pressure: The Martyr gives her energy to others until she barely has enough left to live on. But sacrifice has a hidden side: it's easy to feel quietly superior to the people who need you, and being needed is a kind of power. The people receiving can feel that debt, and they resent it.\n\nThis is the pressure her story warns about. The dream you finally admitted at the New Moon is costing more of you than you agreed to give. If the pursuit has you covering for everyone, absorbing every cost, saying yes when your body already said no, this is her Moon. Some sacrifice is love. Past a certain line it's loss, and the hidden side from her story creeps in with it: the quiet score-keeping, the debt no one agreed to owe you. Give cleanly, with nothing hidden attached, and accept that you cannot feed everyone without starving yourself.\n\nCheck-in: Where am I giving past the line, and who is the giving really for?"
  },
  "lunation/last-quarter/virgo": {
    "title": "Last Quarter in Virgo",
    "archetypeTitle": "Fate's Moon",
    "archetypeLore": "Virgo meets consequence through routine, service, health, and repeated choices. Fate shows what the pattern has produced. Obligation can overrun boundaries. The person may serve until solitude or refusal becomes the only way back to self. Learn the holy usefulness of no. Boundaries are part of service.",
    "body": "Story position: You've started hunting the doubters. Lower the bow and check the target.\n\nSagittarius Season cycle reflection: The Fate is the one holding the scissors. Her job is to say no, draw the line, and cut the thread, and people resent her even when the cut is necessary. Every no costs her something.\n\nHer scissors are what this part of the season asks you to pick up. The Full Moon put your belief up against the facts. Now the season's repeated choices show their results. If the results are visible, in the body, the bank account, the state of the house, the routine that quietly ran the whole time, this is her Moon. None of it is punishment. It's just what those choices produce. This is also the Moon of the necessary no: setting the boundaries that protect your time alone, and accepting that people may resent the cut even when it's right. Look at what your choices produced, and change the ones that aren't working.\n\nCheck-in: What is the pattern producing, and which input needs to change?"
  }
};

export function lunarBeatBodyForKey(contentKey: string) {
  return lunarBeatCopyByKey[contentKey]?.body ?? null;
}

export function lunarBeatArchetypeForKey(contentKey: string) {
  return lunarBeatCopyByKey[contentKey]?.archetypeTitle ?? null;
}

export function lunarBeatArchetypeLoreForKey(contentKey: string) {
  return lunarBeatCopyByKey[contentKey]?.archetypeLore ?? null;
}
