import { expect, test } from "@playwright/test";
import { skyPlacementSourceRecords } from "../../api/_lib/sky-placement-sources";
import { servingPackageRecords } from "../../api/_lib/content-live-status";

const key = "sky-placement/article/saturn/aries";
const template = "Fixture {{planetTitle}} in {{signTitle}}, {{motion}}. Entry: {{entryDate}}.";
for (const width of [390, 1440]) for (const theme of ["light", "dark"]) {
 test(`Sky variable insertion and named template ${width} ${theme}`, async ({ page }) => {
  const errors: string[] = []; page.on("pageerror", error => errors.push(error.message));
  await page.setViewportSize({ width, height: 1000 });
  await page.addInitScript(theme => { localStorage.setItem("tldrastro:contentAdminSecret", "sky-variable-fixture"); localStorage.setItem("tldrastro:studio-theme", theme); }, theme);
  await page.route("**/api/admin/**", async route => {
   const url = new URL(route.request().url());
   const rows = (url.searchParams.get("contentKeys") ?? "").split(",").flatMap(contentKey => {
    // Shared sign sources use the same exact full-document lookup as placement records.
    const baseline = skyPlacementSourceRecords.get(contentKey) ?? servingPackageRecords.get(contentKey);
    if (!baseline) return [];
    const source = contentKey === key ? { ...baseline, placementArticle: template, fallback: { ...baseline.fallback, hook: template, sections: [{ id: "hook", source: "hook" }, { id: "structure", label: "Structural fixture", role: "main", depth: "deep", paragraphs: [{ id: "first", job: "Event and meaning", phrases: [{ id: "one", role: "meaning", text: "Fixture packet.", joinBefore: "" }] }] }] } } : baseline;
    return [{ id: `package:${contentKey}`, content_key: contentKey, surface: "sky", mode: "in_depth", status: "DRAFT", lane: "reference", provider: "tldrastro-fallback-architecture-v3", headline: source.headline, summary: source.summary ?? "", body: source.body_you ?? source.body ?? "", sections: { packageRecord: source }, facts: { fallbackArchitectureV3: true }, source_snapshot: { sourcePackage: source.source_package, content_role: source.content_role }, block_type: "fallback_hook", event_type: "fallback-hook", package_starter: true }];
   });
   await route.fulfill({ json: { ok: true, rows, statuses: [], nextCursor: null } });
  });
  await page.goto(process.env.STUDIO_PRODUCTION_ENTRY === "1" ? "/admin/content#sky-writeups" : "/#sky-writeups");
  await page.evaluate(theme => document.documentElement.setAttribute("data-theme", theme), theme);
  await expect(page.getByLabel("Sky placement planet or point")).toBeVisible();
  await page.getByLabel("Sky placement planet or point").selectOption("saturn");
  await page.getByLabel("Sky placement zodiac sign").selectOption("aries");
  await page.getByLabel("Sky write-up motion").selectOption("retrograde");
  const map = page.getByRole("region", { name: "Sky placement composition map" });
  await expect(map).toBeVisible();
  await expect(map.getByRole("button", { name: "Edit placement article", exact: true })).toContainText("Fixture Saturn in Aries, retrograde. Entry: {{entryDate}}.");
  await map.getByLabel("Placement writing path").selectOption("fallback");
  await map.getByRole("tab", { name: "Main template", exact: true }).click();
  const list = map.getByRole("list", { name: "Placement template order" });
  const opening = list.locator("li").filter({ has: page.getByRole("button", { name: "Edit fallback opening", exact: true }) });
  await expect(opening.getByRole("button")).toHaveText("Saturn in Aries · Fallback opening");
  await expect(opening.locator(".admin-sky-section-reference")).toHaveText(`${key}#fallback.hook`);
  await expect(opening.locator(".admin-sky-template-comparison > div").first()).toContainText(template);
  await expect(opening.locator(".admin-sky-template-comparison > div").last()).toContainText("Fixture Saturn in Aries, retrograde. Entry: {{entryDate}}.");
  await expect(opening.locator(".variable-fact")).toHaveCount(3);
  await expect(opening.locator(".variable-unmapped")).toHaveText("{{entryDate}}");
  const labelStyle = (el: Element) => { const s = getComputedStyle(el); return [s.fontFamily, s.fontSize, s.fontWeight, s.lineHeight, s.letterSpacing, s.textTransform]; };
  expect(await opening.locator(".admin-eyebrow").first().evaluate(labelStyle)).toEqual(await map.locator("header .admin-eyebrow").evaluate(labelStyle));
  await opening.screenshot({ path: `test-results/sky-variable-template-${width}-${theme}.png` });
  const structure = list.locator("li").filter({ has: page.getByRole("button", { name: "Edit structural fixture", exact: true }) });
  await structure.getByText("Section structure", { exact: true }).click();
  await expect(structure.getByRole("list", { name: "Structural fixture paragraph plan" })).toContainText("Event and meaning");
  await expect(structure).toContainText("Target depth: deep");
  await opening.getByRole("button").click();
  const editor = page.getByRole("dialog");
  const writing = editor.locator("textarea[data-sky-field]");
  await writing.fill("Before TARGET after");
  await writing.evaluate((el: HTMLTextAreaElement) => el.setSelectionRange(7, 13));
  const variableKey = editor.locator(".admin-sky-variable-key").filter({ has: page.getByText("Calculated Sky variables", { exact: true }) });
  const openVariableKey = async () => {
    const articlePicker = editor.locator("[data-sky-article-variable-picker]");
    if (await articlePicker.count() && !(await articlePicker.evaluate(el => el.hasAttribute("open")))) await articlePicker.locator(":scope > summary").click();
    if (!(await variableKey.evaluate(el => el.hasAttribute("open")))) await variableKey.locator(":scope > summary").click();
  };
  await openVariableKey();
  const rowsGeometry = await variableKey.locator("dl > div").evaluateAll(rows => rows.map(row => {
    const term = row.querySelector("dt")!.getBoundingClientRect();
    const definition = row.querySelector("dd")!.getBoundingClientRect();
    const bounds = row.getBoundingClientRect();
    const style = getComputedStyle(row);
    return { term: { x: term.x, bottom: term.bottom }, definition: { x: definition.x, y: definition.y }, top: bounds.top, bottom: bounds.bottom, padding: parseFloat(style.paddingLeft) };
  }));
  for (const [index, row] of rowsGeometry.entries()) {
    expect(row.padding).toBe(16);
    if (width < 720) expect(row.definition.y - row.term.bottom).toBeGreaterThanOrEqual(15);
    else expect(row.definition.x).toBeGreaterThan(row.term.x);
    if (index) expect(row.top).toBeGreaterThanOrEqual(rowsGeometry[index - 1].bottom);
  }
  for (const label of ["Source history and validation", "Aspects and horoscopes"]) {
    const summary = editor.locator("summary").filter({ hasText: new RegExp(`^${label}$`) });
    const disclosure = summary.locator("..");
    const surface = await disclosure.evaluate(el => {
      const style = getComputedStyle(el);
      return { background: style.backgroundColor, padding: style.paddingLeft, radius: style.borderRadius };
    });
    expect(surface).toEqual(await variableKey.evaluate(el => {
      const style = getComputedStyle(el);
      return { background: style.backgroundColor, padding: style.paddingLeft, radius: style.borderRadius };
    }));
    await summary.click();
    await expect(disclosure).toHaveAttribute("open", "");
    expect(await disclosure.evaluate(el => el.scrollWidth - el.clientWidth)).toBeLessThanOrEqual(1);
    await disclosure.screenshot({ path: `test-results/sky-disclosure-${label.replaceAll(" ", "-")}-${width}-${theme}.png` });
    await summary.click();
    await expect(disclosure).not.toHaveAttribute("open");
  }
  await expect(editor.getByRole("alert")).toHaveCount(0);
  await editor.getByRole("button", { name: "Insert {{signTitle}}", exact: true }).click();
  await expect(writing).toHaveValue("Before {{signTitle}} after");
  await expect(writing).toBeFocused();
  expect(await writing.evaluate((el: HTMLTextAreaElement) => el.selectionStart)).toBe(20);
  await editor.getByText("Preview this section", { exact: true }).click();
  await expect(editor.locator(".admin-sky-writing-preview")).toHaveText("Before Aries after");
  await writing.fill("{{unknown}}");
  await expect(writing).toHaveAttribute("aria-invalid", "true");
  await expect(editor.getByRole("alert")).toContainText("Unknown Sky variable {{unknown}}");
  await writing.fill("");
  await expect(writing).not.toHaveAttribute("aria-invalid", "true");
  await expect(editor.locator(".admin-sky-writing-preview")).toHaveText("No writing saved for this section.");
  await editor.getByLabel("Writing section", { exact: true }).selectOption("placementArticle");
  await openVariableKey();
  await writing.fill("{{planetTitle}} in {{signTitle}}");
  await expect(editor.locator(".admin-sky-writing-preview")).toHaveText("Saturn in Aries");
  for (const name of ["planetTitle", "signTitle"]) {
    const badge = variableKey.locator("code", { hasText: `{{${name}}}` });
    const previewVariable = editor.locator(`.admin-sky-writing-preview [title^="{{${name}}}"]`);
    expect(await previewVariable.getAttribute("data-variable-color")).toBe(await badge.getAttribute("data-variable-color"));
    expect(await previewVariable.evaluate(el => getComputedStyle(el).color)).toBe(await badge.evaluate(el => getComputedStyle(el).color));
    expect(await previewVariable.evaluate(labelStyle)).toEqual(await writing.evaluate(labelStyle));
  }
  expect(await variableKey.locator("code").evaluateAll(nodes => new Set(nodes.map(el => getComputedStyle(el).color)).size)).toBeGreaterThanOrEqual(3);
  await writing.fill("{{ planetTitle }} in {{signTitle}}");
  expect(await editor.locator(".admin-sky-writing-preview [data-variable-color]").count()).toBe(2);

  expect(await variableKey.locator("p").first().evaluate(labelStyle)).toEqual(await writing.evaluate(labelStyle));
  await variableKey.screenshot({ path: `test-results/sky-variable-key-${width}-${theme}.png` });
  expect(await editor.evaluate(el => el.scrollWidth - el.clientWidth)).toBeLessThanOrEqual(1);
  await editor.getByLabel("Writing section", { exact: true }).selectOption("placementArticleRetrograde");
  await openVariableKey();
  await writing.fill("Fixture {{planetTitle}} {{motion}} article.");
  await expect(editor.locator(".admin-sky-writing-preview")).toHaveText("Fixture Saturn retrograde article.");
  const sections = editor.locator(".admin-evergreen-sections");
  if (!(await sections.evaluate(el => el.hasAttribute("open")))) await sections.locator("summary").click();
  await editor.getByRole("button", { name: "Add section", exact: true }).click();
  await editor.getByLabel("Section name", { exact: true }).fill("Retrograde aspects");
  await expect(editor.getByLabel("Motion for Retrograde aspects", { exact: true })).toHaveValue("retrograde");
  await writing.fill("During this transit, {{aspectsWhileRetrograde}}");
  await expect(writing).not.toHaveAttribute("aria-invalid", "true");
  await openVariableKey();
  await expect(editor.getByRole("button", { name: "Insert {{aspectsInSign}}", exact: true })).toBeVisible();
  await editor.getByRole("button", { name: "Insert {{aspectsWhileRetrograde}}", exact: true }).click();
  expect(await writing.inputValue()).toContain("{{aspectsWhileRetrograde}}");
  expect(await sections.locator(".admin-evergreen-section-name").first().evaluate(el => el.getBoundingClientRect().width)).toBeGreaterThan(200);
  await editor.locator(".admin-evergreen-sections").scrollIntoViewIfNeeded();
  await page.screenshot({ path: `test-results/sky-motion-blocks-${width}-${theme}.png` });
  await writing.fill("During this transit");
  await editor.getByRole("button", { name: "Compose from phrases", exact: true }).click();
  await expect(editor.getByLabel("Phrase text 1", { exact: true })).toHaveValue("During this transit");
  expect(await editor.getByLabel("Phrase source 1", { exact: true }).inputValue()).toContain(key);
  await editor.getByRole("button", { name: "Add phrase", exact: true }).click();
  await editor.getByLabel("Connecting text 2", { exact: true }).fill(", ");
  await editor.getByLabel("Phrase text 2", { exact: true }).fill("fixture {{planetTitle}}.");
  await editor.getByLabel("Phrase text 2", { exact: true }).evaluate((el: HTMLTextAreaElement) => el.setSelectionRange(8, 23));
  await openVariableKey();
  await editor.getByRole("button", { name: "Insert {{signTitle}}", exact: true }).click();
  await expect(editor.getByLabel("Phrase text 2", { exact: true })).toHaveValue("fixture {{signTitle}}.");
  await editor.getByLabel("Phrase text 2", { exact: true }).fill("fixture {{planetTitle}}.");
  await editor.getByLabel("Phrase source 2", { exact: true }).fill("Corpus fixture#second");
  await expect(editor.locator(".admin-sky-writing-preview")).toHaveText("During this transit, fixture Saturn.");
  await editor.getByRole("button", { name: "Move phrase 2 up", exact: true }).click();
  await expect(editor.getByLabel("Phrase source 1", { exact: true })).toHaveValue("Corpus fixture#second");
  await editor.getByRole("button", { name: "Move phrase 1 down", exact: true }).click();
  await expect(editor.locator(".admin-sky-writing-preview")).toHaveText("During this transit, fixture Saturn.");
  await editor.getByLabel("Phrase text 2", { exact: true }).fill("");
  await expect(editor.locator(".admin-sky-writing-preview")).toHaveText("No writing saved for this section.");
  await editor.getByLabel("Phrase text 2", { exact: true }).fill("fixture {{planetTitle}}.");
  await editor.locator(".admin-sky-phrase-composition").scrollIntoViewIfNeeded();
  expect(await editor.evaluate(el => el.scrollWidth - el.clientWidth)).toBeLessThanOrEqual(1);
  const phraseStyle = await editor.getByLabel("Phrase text 1", { exact: true }).evaluate(labelStyle);
  expect(phraseStyle).toEqual(await editor.getByLabel("Phrase text 2", { exact: true }).evaluate(labelStyle));
  await page.screenshot({ path: `test-results/sky-phrases-${width}-${theme}.png` });
  await editor.getByRole("button", { name: "Organize into paragraphs", exact: true }).click();
  const packet = editor.getByRole("group", { name: "Section packet", exact: true });
  await packet.getByLabel("Section role", { exact: true }).selectOption("main");
  await packet.getByLabel("Target depth", { exact: true }).selectOption("deep");
  await packet.locator("details > summary").filter({ hasText: "Existing passage" }).click();
  await packet.getByLabel("Ingredient role 1", { exact: true }).selectOption("meaning");
  await packet.getByLabel("Ingredient role 2", { exact: true }).selectOption("example");
  await expect(editor.locator(".admin-sky-writing-preview")).toHaveText("During this transit, fixture Saturn.");
  await packet.getByRole("button", { name: "Add paragraph", exact: true }).click();
  await packet.locator("details > summary").filter({ hasText: /^Paragraph 2$/ }).click();
  const second = packet.locator("details").filter({ has: page.getByLabel("Paragraph job 2", { exact: true }) });
  await second.getByLabel("Paragraph job 2", { exact: true }).fill("Closing perspective");
  await second.getByRole("button", { name: "Add phrase", exact: true }).click();
  await second.getByLabel("Phrase text 1", { exact: true }).fill("Fixture closing paragraph.");
  await expect(editor.locator(".admin-sky-writing-preview")).toHaveText("During this transit, fixture Saturn.\n\nFixture closing paragraph.");
  await page.screenshot({ path: `test-results/sky-paragraphs-${width}-${theme}.png` });
  await editor.getByLabel("Article structure", { exact: true }).selectOption("body");
  await editor.getByRole("button", { name: "Add article outline", exact: true }).click();
  await expect(editor.getByLabel("Section name", { exact: true })).toHaveValue("Main placement");
  await expect(editor.locator(".admin-sky-writing-preview")).toHaveText("No writing saved for this section.");
  await editor.getByLabel("Writing section", { exact: true }).selectOption({ label: "How to work with it" });
  await packet.locator("details > summary").filter({ hasText: /^Item 1$/ }).click();
  await packet.getByLabel("Practical action 1", { exact: true }).fill("Fixture action.");
  await packet.getByRole("button", { name: "Add phrase", exact: true }).click();
  await packet.getByLabel("Connecting text 1", { exact: true }).fill(" ");
  await packet.getByLabel("Phrase text 1", { exact: true }).fill("Fixture rationale and example.");
  await expect(editor.locator(".admin-sky-writing-preview")).toHaveText("Fixture action. Fixture rationale and example.");
  await expect(packet.getByLabel("Section role", { exact: true })).toHaveValue("practical");
  expect(await editor.evaluate(el => el.scrollWidth - el.clientWidth)).toBeLessThanOrEqual(1);
  await page.screenshot({ path: `test-results/sky-practical-${width}-${theme}.png` });
  expect(errors).toEqual([]);
 });
}
