#!/usr/bin/env python3
"""
build_aspect_reviews.py
Promotes all 84 cc/aspect-pair/* evidence rows to REVIEWED_CLAUSE by authoring
voiced template slots. Each clause is decomposed for the transit templates:

  challenging (square/opposition) -> lived_scene, habitual_response, specific_cost,
                                     meaning_bridge, practical_action           (templates 4A / 4E-4I)
  supportive  (sextile/trine)     -> available_opening, underuse_pattern,
                                     deliberate_participation, meaning_bridge    (templates 4B / 4F)
  conjunction                     -> entangled_scene, function_a_lived,
                                     function_b_lived, concentration_action      (template 4C)

Voice: Marie Satori house voice. No banned seams (no "meets", "brings",
"moves through ... circumstances", keyword runs). Each slot is one clause.
Emits phrasebank/cc-aspect-pair-reviewed.json.
"""
import json, os

ASPECT_OF = {}  # filled from ids

# --- CHALLENGING (square / opposition): scene | response | cost | meaning | action
CH = {
"mars-square-pluto": ("a push to get your way hardens into a need to dominate the situation or the person in it",
  "you go all-or-nothing and try to force the outcome",
  "a power struggle and a bridge you will want back",
  "the intensity is real fuel, it just wants a target that is change rather than winning",
  "Aim the force at what you actually want to build, and leave one exit standing"),
"mars-square-saturn": ("the urge to move runs straight into a limit, a delay, or a wave of self-doubt",
  "you either push recklessly or freeze in place",
  "wasted effort and the sense that you are blocked",
  "the resistance is marking exactly where you need to get stronger",
  "Move in smaller structured steps instead of one big shove"),
"mercury-square-neptune": ("the facts blur and it is easy to hear the version you were hoping for",
  "you fill the gaps with a hunch and act on it",
  "a promise made on fog that has to be walked back",
  "clarity is available, it just has to be checked against something solid",
  "Confirm the detail against a real source before you sign or agree"),
"mercury-square-pluto": ("a conversation turns into a quiet contest over control or over whether your effort gets seen",
  "you maneuver, hint, or dig instead of saying it",
  "trust spent on a power play",
  "the real subject is recognition, and it responds to plainness, not pressure",
  "Say the honest thing directly instead of angling around it"),
"mercury-square-saturn": ("thoughts turn heavy and self-critical and words feel slow to come",
  "you read the seriousness as proof that it is hopeless",
  "a real idea left unsaid because it did not feel finished",
  "this is precision, not pessimism, and it rewards the plain structured version",
  "Say the clear, bare-bones version and let it be enough"),
"mercury-opposition-chiron": ("something said or heard touches an old sore spot and words land harder than intended",
  "you answer from the hurt and get defensive",
  "a defensive exchange where a repair was possible",
  "the sting is an opening for the honest conversation, not only for more hurt",
  "Use it for the healing conversation rather than the defensive one"),
"moon-opposition-chiron": ("something another person does lands right on an old bruise",
  "you treat their action as the whole wound",
  "a fight about them that was really about the tender spot",
  "the ache was there before they touched it",
  "Tend the bruise first, then decide what is actually about them"),
"moon-opposition-jupiter": ("what usually comforts you stops feeling like enough and you get restless for more",
  "you chase a bigger fix than the moment needs",
  "overreach that leaves the real need unmet",
  "the hunger is information about what is missing, not a mandate to supersize",
  "Name the actual need before you go looking for more"),
"moon-opposition-mars": ("your need for calm runs up against someone's heat or push",
  "irritation flares and you snap before you clock it",
  "a small conflict that did not have to happen",
  "the charge wants to move through your body, not your mouth",
  "Move first, then speak"),
"moon-opposition-mercury": ("you feel one thing and think another, and they will not line up",
  "you let the argument in your head overrule the feeling",
  "a decision that ignores half of what is true",
  "both the logic and the mood are carrying real data",
  "Hear both out before you decide anything"),
"moon-opposition-neptune": ("your feelings blur with everyone else's until you cannot tell which are yours",
  "you take the room's mood as your own",
  "a choice made on borrowed feeling",
  "your own signal is in there under the noise",
  "Get quiet and check what is actually yours before acting"),
"moon-opposition-pluto": ("emotional intensity runs into a control dynamic, an old jealousy or a buried feeling asking to be seen",
  "you react from the grip instead of choosing",
  "a reaction that hands someone else the wheel",
  "the feeling can be felt fully without running the show",
  "Feel it all the way through, then choose your response"),
"moon-opposition-saturn": ("your own needs collide with a duty or with someone's distance",
  "you drop yourself to hold it together, or drop the task to feel okay",
  "resentment on one side or a dropped ball on the other",
  "you do not actually have to choose between the two",
  "Make room for the feeling without abandoning the responsibility"),
"moon-opposition-sun": ("the face you show and the feeling underneath sit across from each other",
  "you pick one and disown the other",
  "a self that is either performed or overwhelmed",
  "both sides are you and both can be true at once",
  "Let the outer steadiness and the inner need coexist today"),
"moon-opposition-uranus": ("your need for security pulls hard against an urge to break away",
  "you either bolt or clamp down",
  "a disruption you caused instead of chose",
  "the restlessness is pointing at something that needs more room",
  "Give the need for space a small, deliberate outlet"),
"moon-opposition-venus": ("what you need for comfort pulls against what you want to give someone else",
  "you over-tend them and starve yourself, or the reverse",
  "a lopsided exchange nobody enjoys",
  "both your comfort and theirs get to count",
  "Balance your own care against theirs on purpose"),
"moon-square-chiron": ("an old hurt gets poked and you go straight to defense",
  "you act on the flinch before you notice it",
  "a reaction that reopens the wound",
  "the defensiveness is a bruise, not a verdict",
  "Notice the flinch before you move on it"),
"moon-square-jupiter": ("a good mood inflates and you promise more than the day can hold",
  "you commit big on a feeling",
  "obligations you cannot honor later",
  "the warmth is real, the scale is the thing to watch",
  "Enjoy the lift and keep the commitments to size"),
"moon-square-mars": ("feeling runs hot and reactive, with a short fuse right under the surface",
  "you say the sharp thing before you mean to",
  "a remark you would take back an hour later",
  "the heat is energy that wants a physical outlet",
  "Move the charge through your body before you speak"),
"moon-square-mercury": ("your head and your heart start to bicker",
  "you overthink the mood or talk yourself out of a real feeling",
  "a true feeling argued away",
  "the noise settles once you let the feeling be a fact",
  "Quiet the mental chatter first, then name what you feel"),
"moon-square-neptune": ("moods turn foggy and porous and you soak up everyone's feelings",
  "you make a big emotional call inside the haze",
  "a decision you cannot see clearly enough to trust",
  "the fog lifts with rest, it is not the truth",
  "Rest, and hold the big emotional decisions until it clears"),
"moon-square-north-node": ("what you are reaching for scrapes against what actually soothes you, and it feels awkward",
  "you retreat to the familiar because the growth is uncomfortable",
  "a small chance to grow, skipped for comfort",
  "the awkwardness is the stretch, not a stop sign",
  "Take one small step toward it anyway"),
"moon-square-pluto": ("emotional intensity turns toward control or a quiet brooding power struggle",
  "you grip the feeling and turn it over and over",
  "an afternoon lost to the spiral",
  "the intensity clears when you let it move",
  "Let the feeling pass through instead of holding it"),
"moon-square-saturn": ("a feeling runs into a cold wall and you feel unsupported or not enough",
  "you take the loneliness of the mood as a fact about your life",
  "self-criticism dressed up as realism",
  "the wall is the mood's weather, not the whole picture",
  "Comfort yourself first, then deal with the actual limit"),
"moon-square-sun": ("what would comfort you and what you think you should be doing pull in different directions",
  "you push through and resent it, or rest and feel guilty",
  "a day spent half in each",
  "you can pick one on purpose instead of being pulled",
  "Choose comfort or push deliberately, and let the other wait"),
"moon-square-uranus": ("restlessness spikes and feelings arrive without warning",
  "you bolt from the familiar to get relief",
  "a disruption you did not think through",
  "the urge is a signal that something is too tight",
  "Give yourself real space before you upend anything"),
"moon-square-venus": ("you want comfort and you want closeness, and the two are slightly crossed",
  "you soothe the gap with spending or sweets",
  "a quick fix that misses the real want",
  "the craving is pointing at a softer need underneath",
  "Reach for the actual comfort instead of the substitute"),
"saturn-square-jupiter": ("a wish to expand runs into something telling you to slow down and consolidate",
  "you either overreach or shut the growth down entirely",
  "growth that outruns its foundation, or a foundation with nothing on it",
  "optimism and realism are both right here",
  "Grow, and build the structure that lets the growth hold"),
"sun-opposition-moon": ("your public self and your private feelings pull opposite ways",
  "you perform steadiness and abandon what you need",
  "a composed exterior that costs too much to keep up",
  "the outer role and the inner need are both true",
  "Stay steady on the outside without dropping what you feel underneath"),
"sun-opposition-saturn": ("your aim runs up against hard reality or someone else's limit",
  "you read the gap as a verdict on your worth",
  "confidence spent arguing with a wall",
  "the limit is information about pacing, not about your value",
  "Name what is in your control and put steady work there"),
"sun-square-pluto": ("something asks you to drop a hollow version of yourself and get honest about power",
  "you grip harder for control instead of loosening",
  "a reckoning made heavier by the grip",
  "what is false is trying to fall away so something real can stand",
  "Let the hollow part go rather than defending it"),
"sun-square-saturn": ("your direction runs into a limit, a duty, or an authority saying not yet",
  "you take the block as proof you are not enough",
  "borrowed doubt standing in for real feedback",
  "this is a test of commitment, not a judgment",
  "Do the unglamorous part and let the confidence you build be earned"),
"venus-opposition-north-node": ("what you value and what you are growing toward pull against each other, often through another person",
  "you reach for the old comfort over the stretch",
  "a familiar pleasure that quietly keeps you in place",
  "the tension is showing you which choice actually moves you",
  "Choose the option that helps you grow, even if it is less familiar"),
"venus-opposition-pluto": ("closeness runs into power, jealousy, or the sense you have been giving far more than you get",
  "you react to the intensity before you know what you want",
  "more of yourself poured into an imbalance",
  "the imbalance is being exposed so you can address it",
  "Get clear on what you want from the connection before you react"),
"venus-square-saturn": ("a relationship, or your sense of being valued, feels tested, distant, or effortful, and doubt about being wanted creeps in",
  "you withdraw instead of asking directly whether you are wanted",
  "a connection judged only by its coldest moment",
  "the chill is a test of the bond, not proof you are unwanted",
  "Ask for what you need directly and let people show you through what they do"),
}

# --- SUPPORTIVE (sextile / trine): opening | underuse | participation | meaning
SU = {
"chiron-sextile-north-node": ("an old tender spot lines up with where you are meant to grow, and there is a gentle opening",
  "you leave the sore spot untouched because it is easier",
  "Tend it in one small honest way and let it point you forward",
  "the wound and the growth edge are pointing the same direction"),
"mars-sextile-pluto": ("focused intensity is available that can move something that has been stuck",
  "you let the drive sit idle to avoid the power struggle",
  "Aim it at one real, lasting change",
  "deep drive without the fight is rare and usable"),
"mars-trine-saturn": ("energy and discipline are cooperating, so you can work hard without burning out",
  "you coast and let the steady window pass",
  "Finish the thing you keep almost finishing",
  "this is productive drive that actually lasts"),
"mercury-trine-jupiter": ("ideas connect easily and explaining things feels natural",
  "you spend it on small talk instead of a real question",
  "Say the idea out loud before you have perfected it",
  "the mental flow wants a subject worth the reach"),
"mercury-trine-saturn": ("thinking is clear, careful, and organized, so you can plan and say the precise thing",
  "you let the focus drift to easy tasks",
  "Use it for the serious conversation or the detailed work",
  "precision and follow-through are both online"),
"moon-sextile-chiron": ("a gentle chance opens to tend an old sore spot",
  "you skip it because it feels small",
  "Do one kind thing toward the tender part",
  "small care goes a long way here"),
"moon-sextile-jupiter": ("a warm, hopeful feeling wants to rise in you",
  "you brush it off or hold it back",
  "Let it move through your body without forcing it bigger",
  "the optimism and the mood are lined up on their own"),
"moon-sextile-mars": ("a chance opens to turn a feeling into action",
  "you let the impulse fade",
  "Do the small brave thing the mood is pointing at",
  "the feeling is ready to become a move"),
"moon-sextile-mercury": ("it gets easier to put a feeling into words",
  "you keep avoiding the conversation",
  "Have the talk you have been putting off",
  "feeling and language are cooperating"),
"moon-sextile-neptune": ("a soft opening for intuition and compassion appears",
  "you talk yourself out of the nudge",
  "Follow it into something you make or someone you care for",
  "the gentle signal is worth trusting"),
"moon-sextile-pluto": ("a chance opens to go one level deeper without drama",
  "you stay on the surface",
  "Let one honest feeling surface and actually look at it",
  "depth is available cleanly right now"),
"moon-sextile-saturn": ("a chance opens to give a feeling some structure",
  "you let the mood stay loose and unsettled",
  "Add a steadying routine or a small boundary",
  "structure helps the feeling settle"),
"moon-sextile-sun": ("a small opening lines up how you feel with what you are doing",
  "you overlook the easy step",
  "Take it and let the mood carry the day",
  "self and feeling are gently in step"),
"moon-sextile-uranus": ("a chance opens to try a fresh emotional approach",
  "you default to the usual routine",
  "Break one small pattern and notice how it feels",
  "novelty is easy and low-risk today"),
"moon-sextile-venus": ("a soft opening for warmth, affection, and small pleasures appears",
  "you postpone the nice thing",
  "Reach for the comforting, lovely thing now",
  "tenderness is close to the surface"),
"moon-trine-chiron": ("it is easier than usual to feel the tender thing without being swamped by it",
  "you avoid it out of habit",
  "Let yourself feel it while it is gentle",
  "healing is unusually comfortable here"),
"moon-trine-jupiter": ("a warm, generous, feel-good flow is easy to share",
  "you keep it to yourself",
  "Spread the good feeling around",
  "the mood is genuinely generous"),
"moon-trine-mars": ("emotion is fueling action smoothly and you are moved by what you care about",
  "you sit on the energy",
  "Put it to work on something that matters to you",
  "feeling and drive are cooperating"),
"moon-trine-mercury": ("it is easy to name what you feel and talk it through",
  "you stay quiet anyway",
  "Say the honest, gentle thing",
  "feeling and words flow together"),
"moon-trine-neptune": ("a soft, imaginative, forgiving mood is available",
  "you let it pass unused",
  "Make something or offer someone a little grace",
  "empathy and imagination are open"),
"moon-trine-pluto": ("you can be honest about the heavy thing and come out lighter",
  "you keep it buried",
  "Say the true thing and let it renew you",
  "depth here restores rather than drains"),
"moon-trine-saturn": ("there is real comfort in routine, discipline, and knowing where you stand",
  "you resist the structure that would steady you",
  "Lean into the routine that grounds you",
  "contained feeling is its own comfort now"),
"moon-trine-sun": ("who you are and how you feel agree without effort",
  "you second-guess the easy confidence",
  "Take the day at its word",
  "comfort and confidence come easily"),
"moon-trine-uranus": ("change feels easy and you are comfortable doing it your own way",
  "you cling to the familiar out of habit",
  "Try the fresh approach that appeals to you",
  "emotional freedom is refreshing here"),
"moon-trine-venus": ("a warm, affectionate mood is good for closeness and self-kindness",
  "you keep the tenderness at arm's length",
  "Reach for connection or treat yourself gently",
  "affection comes easily today"),
"sun-trine-jupiter": ("confidence and opportunity align and doors feel open",
  "you hesitate and let the moment pass",
  "Say yes to growth you can actually honor",
  "the expansion is real and available"),
"sun-trine-saturn": ("ambition and structure are working with each other and steady effort pays off",
  "you wait instead of committing",
  "Commit to something long-term and build it properly",
  "discipline feels supportive rather than heavy"),
"venus-sextile-neptune": ("a gentle opening around love, art, and imagination appears",
  "you only admire it instead of acting",
  "Make one tangible, beautiful thing with what is already here",
  "inspiration can become real if you move on it"),
"venus-sextile-north-node": ("warmth and your growth edge cooperate and a small step toward what you want feels natural",
  "you wait for a bigger sign",
  "Reach for the connection or pleasure that also moves you forward",
  "pleasure and growth point the same way"),
"venus-trine-jupiter": ("good feeling, social ease, and a little luck in love and money flow",
  "you let the warmth go unspent",
  "Be generous without overextending",
  "the ease is genuine, the only risk is overdoing it"),
"venus-trine-neptune": ("romance, art, and compassion blend beautifully",
  "you drift off into the ideal",
  "Enjoy it with one foot on the ground about what is real",
  "love and imagination are cooperating"),
"venus-trine-saturn": ("affection and commitment sit easily together and your sense of worth feels stable",
  "you leave the good thing undefined",
  "Define what you want and make it durable",
  "warmth and structure agree here"),
}

# --- CONJUNCTION: entangled_scene | function_a | function_b | concentration_action
CO = {
"mars-conjunction-jupiter": ("drive and confidence swell at the same time and bold moves feel easy",
  "the push to act", "the appetite for more",
  "Take the big swing, sized to what you can actually follow through on"),
"mars-conjunction-north-node": ("your drive locks onto something you are genuinely hungry for",
  "the raw wanting", "the goal it is aimed at",
  "Point it at what matters and go, without skipping your basic needs"),
"mercury-conjunction-mars": ("thinking speeds up and words get sharp and quick",
  "the fast thought", "the urge to fire it off",
  "Stay deliberate about what you send"),
"moon-conjunction-chiron": ("an old feeling surfaces and a sore spot goes tender",
  "the mood", "the old wound it touches",
  "Be gentle with yourself, this is a place that still heals"),
"moon-conjunction-jupiter": ("the heart runs generous and the mood expands",
  "the feeling", "the urge to make it bigger",
  "Enjoy the warmth and watch the urge to overdo it"),
"moon-conjunction-mars": ("feelings run hot and fast and a mood moves you to act",
  "the feeling", "the impulse to act on it",
  "Aim the energy before you spend it"),
"moon-conjunction-mercury": ("feeling and thought run together, so you feel what you think",
  "the emotion", "the need to talk it out",
  "Say the tender thing plainly"),
"moon-conjunction-neptune": ("feelings turn dreamy and porous and you soak up the room",
  "the mood", "the blurred edges around it",
  "Enjoy the imagination and keep a boundary where you drift"),
"moon-conjunction-north-node": ("your feelings point straight at what you are growing toward",
  "the pull", "the direction it names",
  "Take one step closer without mistaking the intensity for a finished decision"),
"moon-conjunction-pluto": ("feelings run deep and intense and something buried can surface",
  "the depth of feeling", "the buried thing rising",
  "Let it move through instead of gripping it"),
"moon-conjunction-saturn": ("feelings turn heavy, serious, or lonely and you want to withdraw",
  "the heavy mood", "the pull to pull away",
  "Tend to yourself and let it pass without taking it as the truth"),
"moon-conjunction-sun": ("feelings and identity move as one, so you feel most yourself when you honor the mood",
  "what you need", "who you are",
  "Let the mood and the day point the same way"),
"moon-conjunction-uranus": ("moods turn sudden and restless and you need room to breathe",
  "the feeling", "the urge for space",
  "Expect the unexpected and give yourself room"),
"moon-conjunction-venus": ("feelings turn soft, affectionate, and pleasure-seeking",
  "the tenderness", "the wish for closeness",
  "Open a window for warmth, connection, and self-care"),
"sun-conjunction-north-node": ("who you are and where you are headed line up and you feel the pull toward something bigger",
  "your identity", "the direction it is drawn to",
  "Aim yourself at it deliberately, without burning past your own limits"),
"venus-conjunction-mars": ("attraction and drive line up, so what you want and who you want it from stop being separate",
  "the attraction", "the drive behind it",
  "Pursue it plainly instead of dressing it up as something more acceptable"),
"venus-conjunction-uranus": ("attraction turns sudden and electric, a spark or an urge to shake up how you love or spend",
  "the pull", "the urge to disrupt",
  "Enjoy the novelty without mistaking a jolt for a foundation"),
}

# habitual_response is consumed by template 4A as "{{habitual_response}} may intensify ...",
# so it must read as a gerund/noun phrase, not a "you ..." clause. It also serves 4E's
# standalone {{repeating_pattern}} sentence, where a terse gerund fragment fits the voice.
HR_GERUND = {
"mars-square-pluto":"Going all-or-nothing to force the outcome",
"mars-square-saturn":"Pushing recklessly or freezing in place",
"mercury-square-neptune":"Filling the gaps with a hunch and acting on it",
"mercury-square-pluto":"Maneuvering, hinting, or digging instead of saying it",
"mercury-square-saturn":"Reading the seriousness as proof it is hopeless",
"mercury-opposition-chiron":"Answering from the hurt and getting defensive",
"moon-opposition-chiron":"Treating their action as the whole wound",
"moon-opposition-jupiter":"Chasing a bigger fix than the moment needs",
"moon-opposition-mars":"Snapping before you clock the irritation",
"moon-opposition-mercury":"Letting the argument in your head overrule the feeling",
"moon-opposition-neptune":"Taking the room's mood as your own",
"moon-opposition-pluto":"Reacting from the grip instead of choosing",
"moon-opposition-saturn":"Dropping yourself to hold it together, or dropping the task to feel okay",
"moon-opposition-sun":"Picking one and disowning the other",
"moon-opposition-uranus":"Bolting or clamping down",
"moon-opposition-venus":"Over-tending them and starving yourself, or the reverse",
"moon-square-chiron":"Acting on the flinch before you notice it",
"moon-square-jupiter":"Committing big on a feeling",
"moon-square-mars":"Saying the sharp thing before you mean to",
"moon-square-mercury":"Overthinking the mood or talking yourself out of a real feeling",
"moon-square-neptune":"Making a big emotional call inside the haze",
"moon-square-north-node":"Retreating to the familiar because the growth is uncomfortable",
"moon-square-pluto":"Gripping the feeling and turning it over and over",
"moon-square-saturn":"Taking the loneliness of the mood as a fact about your life",
"moon-square-sun":"Pushing through and resenting it, or resting and feeling guilty",
"moon-square-uranus":"Bolting from the familiar to get relief",
"moon-square-venus":"Soothing the gap with spending or sweets",
"saturn-square-jupiter":"Overreaching, or shutting the growth down entirely",
"sun-opposition-moon":"Performing steadiness and abandoning what you need",
"sun-opposition-saturn":"Reading the gap as a verdict on your worth",
"sun-square-pluto":"Gripping harder for control instead of loosening",
"sun-square-saturn":"Taking the block as proof you are not enough",
"venus-opposition-north-node":"Reaching for the old comfort over the stretch",
"venus-opposition-pluto":"Reacting to the intensity before you know what you want",
"venus-square-saturn":"Withdrawing instead of asking directly whether you're wanted",
}
for _p, _g in HR_GERUND.items():
    _t = CH[_p]
    CH[_p] = (_t[0], _g, _t[2], _t[3], _t[4])

VAL = {"square":"challenging","opposition":"challenging","sextile":"supportive",
       "trine":"supportive","conjunction":"conjunction"}
LONG_TEMPLATE = {"saturn":"4E","jupiter":"4F","uranus":"4G","neptune":"4H","pluto":"4I"}

def aspect_of(pair):
    for a in ("conjunction","sextile","square","trine","opposition"):
        if f"-{a}-" in pair:
            return a
    raise ValueError(pair)

records=[]
def add(pair, kind, slots):
    a=aspect_of(pair)
    other=pair.split(f"-{a}-")[1]
    rec={
      "id": f"cc/aspect-pair/{pair}",
      "pair": pair.replace("-"," "),
      "aspect": a,
      "valence": VAL[a],
      "status": "REVIEWED_CLAUSE",
      "template_family": "personalized_transit",
      "recommended_short_template": {"challenging":"4A","supportive":"4B","conjunction":"4C"}[VAL[a]],
      "recommended_long_template": LONG_TEMPLATE.get(other) or LONG_TEMPLATE.get(pair.split(f"-{a}-")[0]),
      "slots": slots,
      "source_keys": [f"cc/aspect-pair/{pair}", f"cc/aspect/{a}", f"cc/ref/aspect-psychology/{a}"],
      "originalityCheck": "voiced; decomposed to slots; prohibited seams cleared",
    }
    records.append(rec)

for pair,(scene,resp,cost,mean,act) in CH.items():
    add(pair,"challenging",{"lived_scene":scene,"habitual_response":resp,"specific_cost":cost,
                             "meaning_bridge":mean,"practical_action":act})
for pair,(opening,under,part,mean) in SU.items():
    add(pair,"supportive",{"available_opening":opening,"underuse_pattern":under,
                            "deliberate_participation":part,"meaning_bridge":mean})
for pair,(ent,fa,fb,act) in CO.items():
    add(pair,"conjunction",{"two_functions_becoming_entangled_scene":ent,"function_a_lived":fa,
                             "function_b_lived":fb,"concentration_action":act})

out={"_meta":{"title":"Reviewed cc/aspect-pair clauses","promoted_from":"EVIDENCE_ONLY_UNTIL_REVIEWED",
      "count":len(records),"voice":"Marie Satori house voice","tier":"REVIEWED_CLAUSE",
      "note":"Slots feed the transit templates (4A/4B/4C short; 4E-4I long by transiting outer planet). "
             "A house still locates the scene at render time; these clauses supply the lived situation only."},
     "reviewed":records}
dest=os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),"phrasebank","cc-aspect-pair-reviewed.json")
json.dump(out,open(dest,"w"),indent=2,ensure_ascii=False)
print("wrote",len(records),"reviewed aspect-pair clauses ->",dest)
