#!/usr/bin/env python3
"""
build_stelliums.py — Me/Natal STELLIUM surface (authored, needs sign-off).

A stellium = 3+ planets concentrated in one sign or house. Doctrine from The Stellium
Handbook (Donna Cunningham): the concentration fuels a sense of mission, carries a
'too many eggs in one basket' shadow, and leaves the OPPOSITE house undernourished
(the balance point). Natal second-person register. Emits cc-stellium-authored.json
(filename omits 'reviewed' so transform globs skip it). Tier REVIEWED_CLAUSE.
"""
import json, os

SIGN = {
"aries":"With a stellium in Aries, initiative becomes the defining lens of your whole personality. You start things, push first, and feel most alive at the front of the line. Concentrated this heavily, the drive can outrun patience and turn other people's slower pace into a personal frustration. Your work is aiming all that fire at something worth finishing, so the starts you're so good at actually get to become things.",
"taurus":"With a stellium in Taurus, steadiness and the physical world become the ground everything else is built on. You want security you can touch, and you build slowly and well. Concentrated this heavily, that same steadiness can harden into stubbornness, or a fear of change that keeps you somewhere long past its comfort. Your work is holding your ground where it matters and loosening your grip where it has quietly become a cage.",
"gemini":"With a stellium in Gemini, the restless, curious mind becomes the center of gravity for your whole chart. You gather information, make connections, and need variety the way other people need rest. Concentrated this heavily, the mental energy can scatter across a dozen half-finished interests and mistake talking about a thing for doing it. Your work is letting some curiosities go deep instead of wide, so all that quickness leaves something built behind it.",
"cancer":"With a stellium in Cancer, feeling, memory, and belonging become the lens your whole life runs through. You attach deeply, remember everything, and read a room's emotional weather before anyone speaks. Concentrated this heavily, the sensitivity can tip into moods that run the show and a habit of caretaking that quietly drains you. Your work is building a home solid enough that you can feel everything without being swept away by it.",
"leo":"With a stellium in Leo, self-expression and the need to be seen become the engine of your whole personality. You create, you lead, and you warm the rooms you walk into. Concentrated this heavily, the hunger for recognition can start deciding your choices, so applause matters more than the work itself. Your work is creating from genuine joy, so the light you give off comes from something real rather than from needing the audience.",
"virgo":"With a stellium in Virgo, refinement, usefulness, and attention to detail become the ground you stand on. You notice what's off, you fix what's broken, and you find meaning in doing things well. Concentrated this heavily, the same sharp eye can turn on you as relentless self-criticism, and helpfulness can slide into control. Your work is letting good enough be enough, so your gift for improving things doesn't spend itself on flaws that were never the point.",
"libra":"With a stellium in Libra, relationship and the search for balance become the lens your whole life runs through. You read what others need, you smooth what's jagged, and you feel most yourself in connection. Concentrated this heavily, the pull toward harmony can cost you your own position, so you agree your way out of knowing what you actually want. Your work is staying in the room as yourself, so fairness finally includes you too.",
"scorpio":"With a stellium in Scorpio, depth, intensity, and the drive to reach the truth become the engine of your chart. You see beneath the surface, you commit completely, and you don't do things halfway. Concentrated this heavily, that intensity can curdle into control, suspicion, or a grip that won't release what it should. Your work is trusting some things to stay unproven, so your depth becomes a place people can come close to rather than a fortress.",
"sagittarius":"With a stellium in Sagittarius, meaning, freedom, and the horizon become the center of gravity for your whole personality. You need room, you chase the bigger picture, and you believe the next place holds the answer. Concentrated this heavily, the hunger for more can outrun any commitment and turn restlessness into a way of never quite arriving. Your work is letting a belief or a place be deep enough to stay for, so freedom stops meaning always leaving.",
"capricorn":"With a stellium in Capricorn, structure, ambition, and the long climb become the ground your whole life is built on. You take responsibility, you play the long game, and you'd rather earn it than be handed it. Concentrated this heavily, the drive to achieve can define your entire worth, so rest feels like failure and enough never quite arrives. Your work is letting your value exist apart from what you produce, so the mountain becomes something you climb rather than something you owe.",
"aquarius":"With a stellium in Aquarius, independence, ideas, and the wider group become the lens your whole life runs through. You think ahead, you question the rules, and you need the freedom to be yourself even inside a crowd. Concentrated this heavily, that same independence can wall you off, so detachment stands in for closeness and principle crowds out warmth. Your work is staying connected while you stay free, so your vision reaches people instead of orbiting above them.",
"pisces":"With a stellium in Pisces, imagination, empathy, and the longing to dissolve boundaries become the center of your chart. You feel everything, you drift into other people's states, and the invisible feels more real to you than the concrete. Concentrated this heavily, the openness can leave you without edges, so you absorb what isn't yours and lose the thread of your own life. Your work is building enough structure to hold the sensitivity, so your imagination becomes something you channel rather than something you drown in.",
}

HOUSE = {
1:"A stellium in the 1st house pours most of your energy into your own identity, presence, and the way you meet the world. You come across strongly and people feel you before you say much. Because so much collects here, the opposite 7th house of partnership can go undernourished, so relationships get filtered through how it affects you before there's room for the other person. Your balance work is letting others matter as much as your own becoming.",
2:"A stellium in the 2nd house pours most of your energy into security, resources, and what you're worth. You build a solid base and you understand the value of things. Because so much collects here, the opposite 8th house of shared and deeper resources can go undernourished, so intimacy, merging, and trusting someone with what's yours feel harder than earning it alone. Your balance work is learning that real security can include letting someone else in.",
3:"A stellium in the 3rd house pours most of your energy into thinking, talking, learning, and your immediate surroundings. Your mind is busy and your world is full of exchange. Because so much collects here, the opposite 9th house of the big picture can go undernourished, so you gather endless facts without letting them add up to a belief or a direction. Your balance work is letting all that information point somewhere and mean something.",
4:"A stellium in the 4th house pours most of your energy into home, family, and your inner foundation. Your roots run deep and your private world matters enormously. Because so much collects here, the opposite 10th house of career and public life can go undernourished, so stepping into visibility or ambition feels exposing in a way staying home never does. Your balance work is letting yourself be seen in the world without feeling you've abandoned the nest.",
5:"A stellium in the 5th house pours most of your energy into creativity, romance, play, and self-expression. You create, you perform, you love with your whole chest. Because so much collects here, the opposite 11th house of community and the long-term future can go undernourished, so the group, the cause, and tomorrow's plan lose out to today's spark. Your balance work is letting your self-expression feed something larger than the moment.",
6:"A stellium in the 6th house pours most of your energy into work, health, routine, and being useful. You refine your days and take real pride in doing things well. Because so much collects here, the opposite 12th house of rest and the inner life can go undernourished, so stillness feels unproductive and you stay busy to avoid what surfaces when you stop. Your balance work is letting rest and reflection count as part of a life well kept.",
7:"A stellium in the 7th house pours most of your energy into partnership and one-to-one relationship. You come alive in connection and you understand people by relating to them. Because so much collects here, the opposite 1st house of self can go undernourished, so you define yourself through who you're with and lose the thread of who you are alone. Your balance work is building a self solid enough to bring to a partnership rather than find inside one.",
8:"A stellium in the 8th house pours most of your energy into intimacy, depth, transformation, and shared resources. You go where others won't and you're not afraid of what's underneath. Because so much collects here, the opposite 2nd house of your own stable ground can go undernourished, so simple security and self-sufficiency feel less compelling than intensity and merging. Your balance work is building a base of your own steady enough to survive the depths you're drawn to.",
9:"A stellium in the 9th house pours most of your energy into meaning, belief, travel, and the search for the bigger picture. You chase understanding and the horizon calls to you. Because so much collects here, the opposite 3rd house of the everyday mind can go undernourished, so the grand vision floats above the daily conversations and small facts that would ground it. Your balance work is letting the big truths touch down in ordinary life.",
10:"A stellium in the 10th house pours most of your energy into career, reputation, and your public role. You're built to achieve and you feel the weight of the climb. Because so much collects here, the opposite 4th house of home and roots can go undernourished, so the private base that's supposed to hold you gets treated as an afterthought to the outer goal. Your balance work is tending the ground you come home to, so the achievement has somewhere to rest.",
11:"A stellium in the 11th house pours most of your energy into community, friendship, and the future you're building toward. You think in groups and causes and the long game. Because so much collects here, the opposite 5th house of personal joy and self-expression can go undernourished, so your own creativity and pleasure get postponed for the collective and the plan. Your balance work is letting yourself want something purely for the delight of it, apart from any cause.",
12:"A stellium in the 12th house pours most of your energy into the inner life, the unseen, and what lies beneath ordinary awareness. You live partly in a world others can't see and you feel the currents under the surface. Because so much collects here, the opposite 6th house of daily structure and health can go undernourished, so practical routines and bodily needs get neglected while your attention drifts inward. Your balance work is building enough daily structure to hold a life this porous.",
}

records = []
for sign, text in SIGN.items():
    records.append({"id": f"cc/stellium/in-sign/{sign}", "kind": "stellium_sign",
        "sign": sign, "text": text, "tier": "REVIEWED_CLAUSE",
        "surface": "me.stellium", "register": "natal second-person",
        "doctrine_source": "The Stellium Handbook (voiced original)",
        "review_note": "authored; needs Marie/editorial sign-off"})
for house, text in HOUSE.items():
    records.append({"id": f"cc/stellium/in-house/{house}", "kind": "stellium_house",
        "house": house, "opposite_house": (house + 5) % 12 + 1, "text": text,
        "tier": "REVIEWED_CLAUSE", "surface": "me.stellium", "register": "natal second-person",
        "doctrine_source": "The Stellium Handbook — opposite-house balance (voiced original)",
        "review_note": "authored; needs Marie/editorial sign-off"})

out = {"_meta": {"title": "Natal stelliums (authored, REVIEWED)", "count": len(records),
        "by_sign": len(SIGN), "by_house": len(HOUSE), "tier": "REVIEWED_CLAUSE",
        "surface": "me.stellium", "register": "natal second-person",
        "doctrine": "concentration + mission + too-many-eggs shadow + undernourished opposite house",
        "note": "Serve after sign-off. Composed with the house stellium's opposite as the balance point."},
       "reviewed": records}
dest = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                    "phrasebank", "cc-stellium-authored.json")
json.dump(out, open(dest, "w"), indent=2, ensure_ascii=False)
print(f"wrote {len(records)} stellium records ({len(SIGN)} sign + {len(HOUSE)} house) -> {dest}")
