import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { calendarSubscriptionFixture } from "../tests/helpers/calendar-subscription-fixture.js";
import { escapeCalendarText, foldCalendarLine, serializeCalendarFeed, selectCalendarFeedCopy } from "../api/_lib/calendar-feed.js";
import { getCalendarSubscriptionEvents, getLunarCalendarMonth } from "../apps/web/src/services/ephemeris.js";
import { calendarSubscriptionUrls } from "../apps/web/src/features/calendar/calendarSubscription.js";
import { calendarLocalDateKey } from "../apps/web/src/features/calendar/calendarPhaseLabel.js";
import { calendarSkyV4LunationContentKey } from "../apps/web/src/features/calendar/calendarContentKeys.js";
import { verifyCalendarFeedRuntimeImports } from "../tests/helpers/calendar-feed-runtime.mts";
import { calendarFeedExcerpt, calendarFeedDescription, calendarReadingUrl } from "../apps/web/src/features/calendar/calendarFeedPreview.js";
import { calendarFeedCopyReader } from "../api/_lib/calendar-feed-copy.js";
import { skyPlacementSourceRecords } from "../api/_lib/sky-placement-sources.js";

verifyCalendarFeedRuntimeImports();
const fixture = await calendarSubscriptionFixture();
const options = { include: ["key"], reminder: "At the time", timeZone: "America/New_York" };
const owner = { authorization: "Bearer fixture-owner" };
try {
  const previewBody = "First sentence.\n\nThe second includes 12.5 degrees. Third sentence! Fourth sentence stays in the app.";
  assert.equal(calendarFeedExcerpt(previewBody), "First sentence.\n\nThe second includes 12.5 degrees. Third sentence!");
  assert.equal(calendarFeedExcerpt("**First sentence.** Second sentence."), "First sentence. Second sentence.");
  assert.equal(calendarFeedExcerpt("# Event title\n\nFirst sentence. Second sentence. Third sentence. Fourth sentence."), "First sentence. Second sentence. Third sentence.");
  const readingPath = (id: string, date = "2026-09-21", timeZone = "America/New_York") => `/api/calendar-reading?${new URLSearchParams({ id, date, timeZone })}`;
  assert.equal((await fixture.invoke(readingPath("week-2026-09-21"), "POST")).status, 405);
  assert.equal((await fixture.invoke(readingPath("week-2026-09-21", "2026-02-30"))).status, 400);
  assert.equal((await fixture.invoke(readingPath("week-2026-09-21", "2026-09-21", "invalid"))).status, 400);
  assert.equal((await fixture.invoke(readingPath("../secrets"))).status, 400);
  assert.equal((await fixture.invoke(readingPath("week-2026-09-22"))).status, 404, "A fabricated weekly identity cannot produce a reading");
  const deployment = JSON.parse(readFileSync(new URL("../vercel.json", import.meta.url), "utf8"));
  const patterns = Object.keys(deployment.functions);
  assert(patterns.indexOf("api/calendar-feed.ts") < patterns.indexOf("api/**/*.ts"), "Vercel must match the feed's explicit configuration before the catch-all");
  assert.equal(deployment.functions["api/calendar-feed.ts"].includeFiles, "node_modules/swisseph-wasm/wasm/*");
  await fixture.db.exec("set role anon");
  await assert.rejects(fixture.db.query("select * from calendar_subscriptions"), /permission denied/);
  await assert.rejects(fixture.db.query("insert into calendar_feed_events(draft) values ('{}')"), /permission denied/);
  await fixture.db.exec("set role authenticated");
  await assert.rejects(fixture.db.query("select * from calendar_feed_events"), /permission denied/);
  await fixture.db.exec("reset role");
  assert.equal((await fixture.invoke("/api/admin/calendar-feed-events")).status, 401);
  const created = await fixture.invoke("/api/calendar-subscriptions", "POST", options);
  assert.equal(created.status, 201); const subscription = created.json().subscription;
  assert.equal((await fixture.invoke("/api/calendar-subscriptions", "POST", { ...options, include: [] })).status, 400);
  assert.equal((await fixture.invoke("/api/calendar-subscriptions", "POST", { ...options, timeZone: "bad-zone" })).status, 400);
  const second = (await fixture.invoke("/api/calendar-subscriptions", "POST", options)).json().subscription;
  assert.notEqual(subscription.token, second.token);
  const rows = (await fixture.db.query("select token_hash, manage_token_hash from calendar_subscriptions")).rows;
  assert(!JSON.stringify(rows).includes(subscription.token));
  const path = `/feed/${subscription.token}.ics`;
  assert.equal((await fixture.invoke("/feed/not-a-token.ics")).status, 404);
  assert.equal((await fixture.invoke(`/feed/${"Z".repeat(43)}.ics`)).status, 404);
  assert.equal((await fixture.invoke("/api/calendar-subscriptions", "PATCH", { ...options, ...subscription, manageToken: second.manageToken, expectedUpdatedAt: subscription.updatedAt })).status, 409);
  const event = { title: "Community calendar session", description: "Complete first paragraph.\n\nFinal sentence; preserved, exactly. 🌙", start: "2026-10-04T18:00:00.000Z", end: "2026-10-04T19:00:00.000Z", allDay: false, category: "key", url: "https://example.com/event" };
  let saved = (await fixture.invoke("/api/admin/calendar-feed-events", "POST", { action: "draft", event }, owner)).json().event;
  assert.equal((await fixture.invoke(readingPath(`event-${saved.id}`, "2026-10-04"))).status, 404, "Drafts cannot be opened through public links");
  const draftFeed = await fixture.invoke(path); assert.equal(draftFeed.status, 200); assert(!draftFeed.body.includes(event.title));
  let published = await fixture.invoke("/api/admin/calendar-feed-events", "PATCH", { action: "publish", event, id: saved.id, expectedUpdatedAt: saved.updated_at }, owner);
  assert.equal(published.status, 200); saved = published.json().event;
  const first = await fixture.invoke(path); assert.equal(first.status, 200); assert.match(first.headers["content-type"], /text\/calendar/); assert(first.body.includes(event.title));
  const uid = `event-${saved.id}@tldrastro`; assert(first.body.includes(`UID:${uid}`)); assert(first.body.includes("TRIGGER:PT0S"));
  assert(first.body.replace(/\r\n /gu, "").includes(`DESCRIPTION:${escapeCalendarText(event.description)}`));
  const linked = await fixture.invoke(readingPath(`event-${saved.id}`, "2026-10-04"));
  assert.equal(linked.status, 200);
  assert.equal(linked.json().reading.body, event.description);
  assert.equal(linked.json().reading.sourceUrl, event.url);
  assert(!linked.body.includes("draft") && !linked.body.includes(subscription.token));
  const eventLink = linked.json().reading.url;
  assert(first.body.replace(/\r\n /gu, "").includes(`Read more: ${eventLink}`), "Calendar clients display a link even if they hide the ICS URL field");
  assert.equal((await fixture.invoke(path, "HEAD")).body, "");
  assert.equal((await fixture.invoke(path, "GET", undefined, { "if-none-match": first.headers.etag })).status, 304);
  const changed = { ...event, title: "Updated community session", description: previewBody };
  const beforeDraft = saved.updated_at;
  saved = (await fixture.invoke("/api/admin/calendar-feed-events", "PATCH", { action: "draft", event: changed, id: saved.id, expectedUpdatedAt: saved.updated_at }, owner)).json().event;
  assert.equal((await fixture.invoke(path)).headers.etag, first.headers.etag, "Drafts do not change published feed or ETag");
  assert.equal((await fixture.invoke("/api/admin/calendar-feed-events", "PATCH", { action: "publish", event: changed, id: saved.id, expectedUpdatedAt: beforeDraft }, owner)).status, 409);
  saved = (await fixture.invoke("/api/admin/calendar-feed-events", "PATCH", { action: "publish", event: changed, id: saved.id, expectedUpdatedAt: saved.updated_at }, owner)).json().event;
  const updated = await fixture.invoke(path, "GET", undefined, { "if-none-match": first.headers.etag });
  assert.equal(updated.status, 200); assert.notEqual(updated.headers.etag, first.headers.etag); assert(updated.body.includes(changed.title)); assert.equal(updated.body.split(`UID:${uid}`).length, 2); assert(updated.body.includes("SEQUENCE:3"));
  assert((await fixture.invoke(`/feed/${second.token}.ics`)).body.includes(changed.title), "Existing subscriptions receive additions and edits");
  assert(!updated.body.includes("Fourth sentence stays"), "Subscriptions have the requested opening sentences only");
  const revisedReading = (await fixture.invoke(readingPath(`event-${saved.id}`, "2026-10-04"))).json().reading;
  assert.equal(revisedReading.body, previewBody, "The same event link retains the complete published body after edits");
  assert.equal(revisedReading.url, eventLink);
  const changedOptions = await fixture.invoke("/api/calendar-subscriptions", "PATCH", { ...options, reminder: "Day before", ...subscription, expectedUpdatedAt: subscription.updatedAt });
  assert.equal(changedOptions.status, 200);
  const preferred = (await fixture.invoke(path)).body.split("BEGIN:VEVENT").find(part => part.includes(`UID:${uid}`))!;
  assert(preferred.includes("TRIGGER:-P1D")); assert(preferred.includes("SEQUENCE:4"), "Preference changes advance the event version");
  saved = (await fixture.invoke("/api/admin/calendar-feed-events", "PATCH", { action: "cancel", id: saved.id, expectedUpdatedAt: saved.updated_at }, owner)).json().event;
  const cancelled = (await fixture.invoke(path)).body.split("BEGIN:VEVENT").find(part => part.includes(`UID:${uid}`))!;
  assert(cancelled.includes("STATUS:CANCELLED")); assert(cancelled.includes("SEQUENCE:5")); assert(!cancelled.includes("BEGIN:VALARM"));
  assert.equal((await fixture.invoke("/api/admin/calendar-feed-events", "POST", { action: "draft", event: { ...event, start: "2026-02-30T18:00:00.000Z" } }, owner)).status, 400);
  assert.equal((await fixture.invoke("/api/admin/calendar-feed-events", "POST", { action: "publish", event: { ...event, url: "javascript:alert(1)" } }, owner)).status, 400);
  assert.equal((await fixture.invoke("/api/admin/calendar-feed-events", "POST", { action: "publish", event: { ...event, description: "{{unresolved}}" } }, owner)).status, 422);
  fixture.setStorageFailure(true); assert.equal((await fixture.invoke(path)).status, 503); fixture.setStorageFailure(false);
  const folded = foldCalendarLine("DESCRIPTION:" + "🌙 naïve, ".repeat(40));
  for (const line of folded.split("\r\n")) assert(Buffer.byteLength(line) <= 75);
  assert.equal(folded.replace(/\r\n /gu, ""), "DESCRIPTION:" + "🌙 naïve, ".repeat(40));
  const allDay = serializeCalendarFeed([{ ...event, readingId: "day", uid: "day@tldrastro", start: "2026-10-04", end: "2026-10-05", allDay: true, modified: "2026-09-22T00:00:00Z", sequence: 1 }], options as any);
  assert(allDay.includes("DTSTART;VALUE=DATE:20261004\r\nDTEND;VALUE=DATE:20261005"));
  const links = calendarSubscriptionUrls(subscription.token, "https://calendar.example"); assert(links.https.startsWith("https://calendar.example/feed/")); assert(links.webcal.startsWith("webcal://")); assert.equal(new URL(links.google).searchParams.get("cid"), links.webcal);
  // Request-scoped publication selection cannot leak drafts, retired rows or stale versions.
  const key = "sky.test.calendar", source = { id: "source", content_key: key, status: "LIVE", lane: "serving", body: "Exact published first and last sentence.", updated_at: "2026-09-22T00:00:00Z", source_snapshot: { review_status: "approved" } };
  const ledger = new Map([[key, { content_key: key, state: "live", revision: 1, row_id: source.id, row_updated_at: source.updated_at, updated_at: source.updated_at } as any]]);
  assert.equal(selectCalendarFeedCopy([key], "2026-10-04", [source], ledger)?.body, source.body);
  assert.equal(selectCalendarFeedCopy([key], "2026-10-04", [{ ...source, updated_at: "2026-09-23T00:00:00Z" }], ledger), null);
  assert.equal(selectCalendarFeedCopy([key], "2026-10-04", [{ ...source, sections: { packageDraft: { Body: "private" } } }], ledger), null);
  ledger.get(key).state = "retired"; assert.equal(selectCalendarFeedCopy([key], "2026-10-04", [source], ledger), null);
  // Compare two separate dates with the actual Calendar calculation, never catalog dates.
  const calculated = await getCalendarSubscriptionEvents(2026);
  const sun = calculated.find(event => event.type === "ingress" && event.planet === "Sun" && event.toSign === "Libra")!;
  assert(sun);
  const sunKey = "sky-placement/article/sun/libra", sunRecord = skyPlacementSourceRecords.get(sunKey)!;
  const sunRow = { ...source, id: "published-sun", content_key: sunKey, body: "", event_type: "sky-writeup-variable-import", sections: { packageRecord: sunRecord } };
  const sunLedger = new Map([[sunKey, { ...ledger.get(key), content_key: sunKey, state: "live", row_id: sunRow.id } as any]]);
  const sunBody = calendarFeedCopyReader(sunLedger, [sunRow]).eventBody(sun, options.timeZone, calculated);
  assert(sunBody.includes(sunRecord.placementArticle), "Variable-only Studio imports retain the approved canonical article");
  const sunRevision = { ...sunRow, sections: { packageRecord: { ...sunRecord, studio_version_status: "approved-serving-revision", placementArticle: "Published article opening. Published article ending." } } };
  assert(calendarFeedCopyReader(sunLedger, [sunRevision]).eventBody(sun, options.timeZone, calculated).includes("Published article opening. Published article ending."));
  assert.equal(calendarFeedCopyReader(sunLedger, [{ ...sunRevision, updated_at: "2026-09-23T00:00:00Z" }]).eventBody(sun, options.timeZone, calculated), "", "Stale canonical revisions cannot resurrect bundled or legacy copy");
  assert.equal(calendarFeedCopyReader(sunLedger, [{ ...sunRevision, review_state: "needs_review" }]).eventBody(sun, options.timeZone, calculated), "", "Held canonical revisions cannot resurrect bundled copy");
  sunLedger.get(sunKey).state = "retired";
  assert.equal(calendarFeedCopyReader(sunLedger, [sunRow]).eventBody(sun, options.timeZone, calculated), "", "Retired canonical articles cannot fall through to a legacy renderer");
  const sunRowId = "af2f1000-0000-4000-8000-000000000003";
  await fixture.db.query("insert into generated_interpretations(id,content_key,status,lane,body,updated_at,source_snapshot,sections) values($1,$2,'LIVE','serving','','2026-09-23T00:00:00Z',$3,$4)", [sunRowId, sunKey, JSON.stringify({ review_status: "approved" }), JSON.stringify(sunRevision.sections)]);
  await fixture.db.query("insert into content_publications(content_key,state,revision,row_id,row_updated_at,updated_at) select content_key,'live',1,id,updated_at,updated_at from generated_interpretations where id=$1", [sunRowId]);
  const sunSub = (await fixture.invoke("/api/calendar-subscriptions", "POST", { ...options, include: ["seasons"] })).json().subscription;
  const sunEntry = async () => (await fixture.invoke(`/feed/${sunSub.token}.ics`)).body.replace(/\r\n /gu, "").split("BEGIN:VEVENT").find(part => part.includes(`event=${encodeURIComponent(sun.id)}`))!;
  const beforeSun = await sunEntry();
  assert((await fixture.invoke(readingPath(sun.id, calendarLocalDateKey(sun.startsAt, options.timeZone)))).json().reading.body.includes("Published article opening. Published article ending."));
  const revisedSun = { packageRecord: { ...sunRevision.sections.packageRecord, placementArticle: "Updated article opening. Updated article ending." } };
  await fixture.db.query("update generated_interpretations set sections=$2,updated_at='2026-09-24T00:00:00Z' where id=$1", [sunRowId, JSON.stringify(revisedSun)]);
  await fixture.db.query("update content_publications set revision=2,row_updated_at='2026-09-24T00:00:00Z',updated_at='2026-09-24T00:00:00Z' where row_id=$1", [sunRowId]);
  const afterSun = await sunEntry();
  assert((await fixture.invoke(readingPath(sun.id, calendarLocalDateKey(sun.startsAt, options.timeZone)))).json().reading.body.includes("Updated article opening. Updated article ending."));
  assert.equal(afterSun.match(/UID:([^\r]+)/)![1], beforeSun.match(/UID:([^\r]+)/)![1]);
  assert(Number(afterSun.match(/SEQUENCE:(\d+)/)![1]) > Number(beforeSun.match(/SEQUENCE:(\d+)/)![1]), "Published package edits advance the same event's calendar version");
  assert(afterSun.includes("LAST-MODIFIED:20260924T000000Z"));
  const moon = calculated.find(event => event.type === "lunation" && event.primary && event.dateKey !== calendarLocalDateKey(event.startsAt, "America/New_York"))!;
  assert(moon, "Exercise an event that occurs on different local and UTC dates");
  const localDate = calendarLocalDateKey(moon.startsAt, "America/New_York");
  const moonKey = calendarSkyV4LunationContentKey({ ...moon, dateKey: localDate })!;
  const rowId = "af2f1000-0000-4000-8000-000000000001";
  await fixture.db.query("insert into generated_interpretations(id,content_key,target_date,status,lane,body,updated_at,source_snapshot) values($1,$2,$3,'LIVE','serving',$4,now(),$5)", [rowId, moonKey, localDate, "Published opening. Complete published ending.", JSON.stringify({ review_status: "approved" })]);
  await fixture.db.query("insert into content_publications(content_key,state,revision,row_id,row_updated_at,updated_at) select content_key,'live',1,id,updated_at,updated_at from generated_interpretations where id=$1", [rowId]);
  const moonSub = (await fixture.invoke("/api/calendar-subscriptions", "POST", { ...options, include: ["lunations"] })).json().subscription;
  const moonPath = `/feed/${moonSub.token}.ics`;
  const moonFeed = (await fixture.invoke(moonPath)).body.replace(/\r\n /gu, "");
  assert(moonFeed.includes("DESCRIPTION:Published opening. Complete published ending."), "Published Calendar copy uses the subscriber's local event date");
  assert(!moonFeed.includes("Quarter Moon"));
  assert(moonFeed.includes(`?date=${localDate}#calendar?view=day&date=${localDate}&event=${encodeURIComponent(moon.id)}`));
  const exactMoonReading = await fixture.invoke(readingPath(moon.id, localDate));
  assert.equal(exactMoonReading.status, 200); assert.equal(exactMoonReading.json().reading.id, moon.id);
  assert.equal(exactMoonReading.json().reading.body, "Published opening. Complete published ending.");
  const weekSub = (await fixture.invoke("/api/calendar-subscriptions", "POST", { ...options, include: ["weekly"] })).json().subscription;
  const weekFeed = (await fixture.invoke(`/feed/${weekSub.token}.ics`)).body.replace(/\r\n /gu, "");
  const week = await fixture.invoke(readingPath("week-2026-09-21"));
  assert.equal(week.status, 200);
  assert(week.json().reading.body.startsWith("A Full Moon in Aries arrives this week,"));
  assert(week.json().reading.body.endsWith("before turning one intense moment into a final verdict."));
  assert(weekFeed.includes(`DESCRIPTION:${escapeCalendarText(calendarFeedDescription(week.json().reading.body, week.json().reading.url))}`));
  const weeklyRecord = JSON.parse(readFileSync(new URL("../apps/web/src/content/fallbackArchitectureV3/bundled-initial-reader-rows-v3.json", import.meta.url), "utf8")).authoredCards.find((row: any) => row.contentKey === "authored/week-opener/full-moon");
  const weekRowId = "af2f1000-0000-4000-8000-000000000002";
  await fixture.db.query("insert into generated_interpretations(id,content_key,status,lane,body,updated_at,source_snapshot,sections) values($1,$2,'LIVE','serving',$3,now(),$4,$5)", [weekRowId, weeklyRecord.contentKey, weeklyRecord.body, JSON.stringify({ review_status: "approved" }), JSON.stringify({ packageRecord: weeklyRecord })]);
  await fixture.db.query("insert into content_publications(content_key,state,revision,row_id,row_updated_at,updated_at) select content_key,'live',1,id,updated_at,updated_at from generated_interpretations where id=$1", [weekRowId]);
  assert.equal((await fixture.invoke(readingPath("week-2026-09-21"))).json().reading.body, week.json().reading.body, "Published Studio package templates use the calculated sign and preserve the full approved body");
  const publishedWeekFeed = (await fixture.invoke(`/feed/${weekSub.token}.ics`)).body.replace(/\r\n /gu, "");
  assert(publishedWeekFeed.includes(`DESCRIPTION:${escapeCalendarText("A Full Moon in Aries arrives this week,")}`));
  assert(!publishedWeekFeed.includes("{{signTitle}}"));
  const weekRow = { ...source, content_key: weeklyRecord.contentKey, sections: { packageRecord: weeklyRecord } };
  const weekLedger = new Map([[weeklyRecord.contentKey, { ...ledger.get(key), content_key: weeklyRecord.contentKey, state: "live" } as any]]);
  assert.equal(selectCalendarFeedCopy([weeklyRecord.contentKey], "2026-09-21", [{ ...weekRow, sections: { packageRecord: { ...weeklyRecord, review_status: "needs_review" } } }], weekLedger, "Aries"), null);
  assert.equal(selectCalendarFeedCopy([weeklyRecord.contentKey], "2026-09-21", [{ ...weekRow, sections: { packageRecord: { ...weeklyRecord, body: "{{unknownSlot}}" } } }], weekLedger, "Aries"), null);
  await fixture.db.query("update content_publications set state='retired',revision=2 where content_key='authored/week-opener/full-moon'");
  assert.equal((await fixture.invoke(readingPath("week-2026-09-21"))).json().reading.body, "", "Retired bundled copy cannot reappear in the app link");
  const linkedUrl = new URL(calendarReadingUrl("https://example.com", localDate, moon.id, options.timeZone));
  assert.equal(new URLSearchParams(linkedUrl.hash.split("?")[1]).get("event"), moon.id);
  assert.equal(new URLSearchParams(linkedUrl.hash.split("?")[1]).get("timeZone"), options.timeZone);
  // Dated content uses the shared LIVE/serving gate; undated sources also
  // require the exact ledger version (checked above).
  await fixture.db.query("update generated_interpretations set body=$2,status='DRAFT',lane='reference',updated_at=clock_timestamp() where id=$1", [rowId, "Revised published opening. Complete revised ending."]);
  assert(!(await fixture.invoke(moonPath)).body.includes("Revised published opening"), "Draft Calendar copy cannot enter a subscription");
  await fixture.db.query("update generated_interpretations set status='LIVE',lane='serving',updated_at=clock_timestamp() where id=$1", [rowId]);
  await fixture.db.query("update content_publications set row_updated_at=(select updated_at from generated_interpretations where id=$1),updated_at=clock_timestamp(),revision=2 where content_key=$2", [rowId, moonKey]);
  assert((await fixture.invoke(moonPath)).body.replace(/\r\n /gu, "").includes("DESCRIPTION:Revised published opening. Complete revised ending."), "Existing URL reads newly published copy without redeployment");
  for (const month of [2, 8]) {
    const calendar = await getLunarCalendarMonth({ label: "UTC", latitude: 0, longitude: 0, timeZone: "UTC" }, new Date(Date.UTC(2026, month, 15)), { detail: "full" });
    const fullMoon = calendar.events.find(item => item.type === "lunation" && item.title.includes("Full") && Number(item.dateKey.slice(5, 7)) === month + 1)!;
    const equivalent = calculated.find(item => item.type === "lunation" && item.title === fullMoon.title && item.dateKey === fullMoon.dateKey)!;
    assert(equivalent); assert(Math.abs(Date.parse(equivalent.startsAt) - Date.parse(fullMoon.startsAt)) < 60000);
  }
  console.log("PASS calendar subscriptions: actual handlers + PostgreSQL migration, unique URLs, auth/RLS, draft/publish/edit/cancel, same-URL refresh, ETag, reminders, full text, UTF-8 folding, provider links and calculation parity");
} finally { await fixture.close(); }
