import assert from 'node:assert/strict';
import {rows,invoke,providerFixture,feedbackFixture,storageFixture} from '../tests/helpers/lunation-writing-api.mts';
import {lunationArticleEvents} from '../api/_lib/lunation-article-facts';
import {lunationArticleHash as hash} from '../src/astro-writing/lunationArticleWriting.mjs';

const event=(await lunationArticleEvents('2026-10','America/New_York'))[0];
const prepared=await invoke('POST',{action:'prepare',month:'2026-10',timeZone:event.timeZone,eventId:event.id,direction:''});
assert.equal(prepared.status,200,JSON.stringify(prepared.payload));
let row=prepared.payload.rows[0];
const act=(action:string,extra:any={})=>invoke('POST',{action,id:row.id,expectedUpdatedAt:row.updated_at,...extra});
const originalBody='Synthetic rejected opening.\n\nComplete final paragraph, preserved exactly.';
row=(await act('save',{headline:'Synthetic original title',body:originalBody})).payload.rows[0];
const before=structuredClone(row),reason='Start with the calculated date, then explain the phase and signs.';
const calls=providerFixture.calls;
assert.equal((await invoke('POST',{action:'reject',id:row.id,expectedUpdatedAt:row.updated_at,reason},undefined,'wrong')).status,401);
for(const invalid of [undefined,'','   ',42,'x'.repeat(6001)])assert.equal((await act('reject',{reason:invalid})).status,400);
assert.equal((await act('reject',{reason,body:'Client-supplied replacement'})).status,400);
feedbackFixture.fail=true;
assert.equal((await act('reject',{reason})).status,503);
assert.deepEqual(rows.get(row.id),before,'A failed refresh preserves the entire saved draft.');
feedbackFixture.fail=false;
const guidance=rows.get('shared-guidance-fixture');
guidance.sections.writingProfile.voiceGuidance+=' Synthetic latest guidance for rejection.';
guidance.source_snapshot.revision=2;
const apiKey=process.env.OPENAI_API_KEY;delete process.env.OPENAI_API_KEY;
const rejected=await act('reject',{reason});
process.env.OPENAI_API_KEY=apiKey;
assert.equal(rejected.status,200,JSON.stringify(rejected.payload));
row=rejected.payload.rows[0];
const entry=row.source_snapshot.lunationWriting.rejections[0];
assert.equal(entry.reason,reason);
assert.equal(entry.headline,before.headline);
assert.equal(entry.body,originalBody);
assert.equal(entry.passageHash,hash({headline:before.headline,body:originalBody}));
assert.equal(entry.updatedAt,before.updated_at);
assert.deepEqual(entry.facts,before.facts);
assert.equal(entry.writing.planHash,before.source_snapshot.lunationWriting.planHash);
assert.equal(row.body,'');
assert.equal(row.headline,event.title);
assert.equal(row.status,'DRAFT');assert.equal(row.lane,'reference');
assert.equal(row.source_snapshot.lunationWriting.receipt,null);
assert.notEqual(row.source_snapshot.lunationWriting.planHash,before.source_snapshot.lunationWriting.planHash);
assert.equal(row.source_snapshot.lunationWriting.preview.writingProfile.revision,2);
assert(row.source_snapshot.lunationWriting.preview.writingProfile.profile.voiceGuidance.includes('Synthetic latest guidance for rejection.'));
assert(row.source_snapshot.lunationWriting.preview.corrections.some((c:any)=>c.owner_reason===reason&&c.bad.includes(originalBody)));
assert.equal(providerFixture.calls,calls,'Rejection and plan refresh must not call a model.');
assert.equal((await invoke('POST',{action:'reject',id:row.id,expectedUpdatedAt:before.updated_at,reason})).status,409);
assert.equal((await act('reject',{reason})).status,409,'An empty draft cannot be rejected again.');
assert.equal((await act('generate',{approvedPlanHash:before.source_snapshot.lunationWriting.planHash})).status,409);
const reopened=await invoke('GET',undefined,`/api/admin/lunation-writing?id=${row.id}`);
assert.deepEqual(reopened.payload.rows[0],row);
const generation=await act('generate',{approvedPlanHash:row.source_snapshot.lunationWriting.planHash});
assert.equal(generation.status,202,JSON.stringify(generation.payload));row=generation.payload.rows[0];
assert.equal(providerFixture.calls,calls+1);
assert(providerFixture.requests.at(-1).input.includes(reason));
assert(providerFixture.requests.at(-1).input.includes(originalBody.replaceAll('\n','\\n')));
assert.equal((await act('reject',{reason})).status,409,'Running requests cannot be rejected.');
assert.equal((await act('generate',{approvedPlanHash:row.source_snapshot.lunationWriting.planHash})).status,409);
providerFixture.draft={headline:'Synthetic replacement',body:'Synthetic replacement opening.\n\nReplacement ending.'};
row=(await act('poll')).payload.rows[0];
assert.equal(row.body,providerFixture.draft.body);
assert.deepEqual(row.source_snapshot.lunationWriting.rejections,[entry]);
const replacement=structuredClone(row);
// Simulate an edit arriving between the read and the conditional rejection write.
storageFixture.beforePatch=()=>rows.set(row.id,{...rows.get(row.id),body:'Synthetic newer editor text.',updated_at:'2099-01-01T00:00:00Z'});
assert.equal((await act('reject',{reason:'Second correction.'})).status,409);
assert.equal(rows.get(row.id).body,'Synthetic newer editor text.');
assert.deepEqual(rows.get(row.id).source_snapshot.lunationWriting.rejections,[entry]);
// Restore the isolated fixture only, then reject the replacement and retain its receipt.
rows.set(row.id,replacement);row=replacement;
const second=await act('reject',{reason:'Second correction.'});
assert.equal(second.status,200,JSON.stringify(second.payload));row=second.payload.rows[0];
const history=row.source_snapshot.lunationWriting.rejections;
assert.equal(history.length,2);assert.deepEqual(history[0],entry);
assert.equal(history[1].body,replacement.body);
assert.deepEqual(history[1].writing.receipt,replacement.source_snapshot.lunationWriting.receipt);
assert(!Object.hasOwn(history[1].writing,'rejections'),'History must not recursively duplicate earlier history.');
assert.equal(providerFixture.calls,calls+1);
console.log('PASS lunar rejection: exact history and feedback, refreshed plan, CAS conflicts, no-cost rejection, one explicit regeneration, reload and repeated rejection.');
