import assert from 'node:assert/strict';
import { matchingInitialSkyLoad, type InitialSkyLoad } from '../apps/web/src/services/skyApi';
import { skyDateTimeFromInput, isDateInputValue } from '../apps/web/src/services/skySelection';

const ny = { label: 'Synthetic New York', latitude: 40.7, longitude: -74, timeZone: 'America/New_York' };
const tokyo = { label: 'Synthetic Tokyo', latitude: 35.6, longitude: 139.6, timeZone: 'Asia/Tokyo' };
const now = new Date('2026-09-21T02:30:00Z');
assert.equal(skyDateTimeFromInput('2026-09-20', ny, true, now).toISOString(), now.toISOString());
assert.equal(skyDateTimeFromInput('2026-09-21', tokyo, true, now).toISOString(), now.toISOString());
assert.equal(skyDateTimeFromInput('2026-09-20', tokyo, true, now).toISOString(), '2026-09-20T03:00:00.000Z');
assert.equal(skyDateTimeFromInput('2026-11-01', ny, false, now).toISOString(), '2026-11-01T17:00:00.000Z');
assert.equal(isDateInputValue('2026-02-30'), false);
assert.equal(isDateInputValue('2026-02-28'), true);
const day = new Intl.DateTimeFormat('en-CA', { timeZone: ny.timeZone, year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date());
const initial: InitialSkyLoad = { day, location: ny, date: new Date(), live: true, startedAt: performance.now(), result: Promise.resolve(null), matches: () => initial, resolve: async () => { throw new Error("Unused test stub"); } };
assert.equal(matchingInitialSkyLoad(initial, day, ny), initial);
assert.equal(matchingInitialSkyLoad(initial, day, ny), initial, 'StrictMode replay retains the same exact request');
assert.equal(matchingInitialSkyLoad(initial, day, { ...ny, label: 'Renamed' }), initial);
assert.equal(matchingInitialSkyLoad(initial, '2026-01-02', ny), null);
assert.equal(matchingInitialSkyLoad(initial, day, tokyo), null);
assert.equal(matchingInitialSkyLoad(initial, day, { ...ny, timeZone: 'UTC' }), null);
assert.equal(matchingInitialSkyLoad({ ...initial, live: false }, day, ny), null);
assert.equal(matchingInitialSkyLoad({ ...initial, startedAt: performance.now() - 10_001 }, day, ny), null);
console.log('PASS: exact initial instant, selected-zone noon and DST, changed date/location/clock mode, StrictMode reuse and expired bootstrap rejection.');
