import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createHash} from 'node:crypto';
import {loadWeeklyOwnerEvidence,weeklyEvidenceMatch} from '../src/astro-writing/weeklyOwnerEvidence.mjs';
import {assertHoroscopeEvidenceDelivered} from '../src/astro-writing/horoscopeEvidenceReceipt.mjs';
import {horoscopeProfileEvidence} from '../src/astro-writing/horoscopePromptVariables.mjs';
import {defaultHoroscopeProfile} from '../src/astro-writing/horoscopeWritingProfiles.mjs';
import {store,installHoroscopeWriterFixture,invokeHoroscopeWritingWithReview as invoke,writerFixture} from '../tests/helpers/sky-article-save-api.mts';
import {prepareHoroscopeBrief} from '../api/_lib/horoscope-editions';
import {emptyHoroscopeEdition,horoscopeEditionKey,horoscopeEditionBody} from '../apps/web/src/content/horoscopeEditions.mjs';
import {projectReaderRow} from '../apps/web/src/content/readerRowProjection.mjs';

const hash=(text:string)=>createHash('sha256').update(text).digest('hex');
const read=(p:string)=>fs.readFileSync(p,'utf8');
const voice=JSON.parse(read('packages/astro-knowledge/voice/tldr-astro/satori-writer/voice-index.json'));
const sources=loadWeeklyOwnerEvidence(read,voice);
assert.equal(sources.length,48);assert.equal(new Set(sources.map(e=>e.sourcePath)).size,4);
for(const e of sources){
  assert.equal(e.text,read(e.sourcePath).slice(e.provenance.start,e.provenance.end));
  assert.equal(e.sourceRecordSha256,hash(e.text));
}
const august=sources.filter(e=>e.sourcePath.includes('august-24th'));
assert.equal(august.length,12);assert(august.every(e=>e.text.split(/\n\s*\n/u).length>=4),'Heading plus all three source paragraphs');
assert.throws(()=>loadWeeklyOwnerEvidence(p=>p===sources[0].sourcePath?read(p)+'changed':read(p),voice),/source changed/);
const revoked=structuredClone(voice);
const removed=revoked.entries.find(e=>e.sourcePath===august[0].sourcePath&&august[0].text.includes(e.text));removed.ownerApproved=false;
assert(!loadWeeklyOwnerEvidence(read,revoked).some(e=>e.id===august[0].id),'A revoked paragraph cannot be laundered into a complete primary unit');
const query={humanSituation:'Avoiding conflict by accommodating everyone and exhausting yourself',mechanism:'',surface:'weekly'};
const match=weeklyEvidenceMatch({text:'Accommodating everyone and avoiding conflict leaves you exhausted.',structuralFunction:'complete weekly sign reading'},query);
assert(match.score>weeklyEvidenceMatch({text:'The Sun in Libra brings a pleasant week.',sign:'libra'},query).score);
assert(match.matches.humanSituation.includes('accommodating'));

installHoroscopeWriterFixture();
const comparison='Private synthetic comparison opening.\n\nPrivate synthetic comparison ending.';
const block=`ACTIVE COMPLETE OWNER-DESIGNATED COMPARISONS\nComplete prose SHA-256: ${hash(comparison)}\nBEGIN COMPLETE PROSE private-fixture\n${comparison}\nEND COMPLETE PROSE private-fixture\n\n`;
const correction='OWNER CORRECTION: fixture scope\nKeep the full synthetic distinction.';
const profile={...defaultHoroscopeProfile('weekly'),sourceGuidance:block+correction};
let result=await store.invoke('POST',{profile,expectedUpdatedAt:null},'/api/admin/generated-content?writingProfiles=true');
assert.equal(result.status,200);const savedProfile=result.payload.profile;
const packet=await prepareHoroscopeBrief(new URL('http://localhost/?period=weekly&date=2026-10-07&timeZone=America/New_York'));
const edition=emptyHoroscopeEdition(packet.brief.window);
const rejected={id:'synthetic-rejection',scope:'aries',rejectedAt:'2026-10-06T12:00:00Z',passages:[{sign:'aries',headline:'Rejected fixture',body:'Exact rejected opening.\n\nExact rejected ending.'}]};
result=await store.invoke('POST',{contentKey:horoscopeEditionKey(edition.window),surface:'sky',mode:'article',eventType:'horoscope-edition',provider:'manual-admin',status:'DRAFT',lane:'serving',headline:'Synthetic evidence edition',body:horoscopeEditionBody(edition),sections:{horoscopeEdition:edition},facts:{horoscopeBrief:packet},sourceSnapshot:{studioWritingProfile:savedProfile,horoscopeGeneration:{rejections:[rejected]}}});
assert.equal(result.status,200);let row=result.payload.rows[0];
const action=async(action:string,extra:any={})=>{const r=await invoke({action,id:row.id,expectedUpdatedAt:row.updated_at,...extra});if(r.payload.rows?.[0])row=r.payload.rows[0];return r;};
result=await action('prepare');assert.equal(result.status,200,JSON.stringify(result.payload));assert.equal(writerFixture.calls,0);
const preview=result.payload.plan.readings.find(e=>e.sign==='aries').ownerEvidence;
assert.equal(preview.selection.eligible.filter(e=>e.proseFunction==='complete weekly sign reading').length,48);
assert.equal(preview.selection.eligible.length,88,'48 Weekly readings plus 39 Seasonal complete units and one Monthly essay');
assert(preview.selection.eligible.every(e=>e.proseFunction.startsWith('complete')));
assert.equal(preview.passages.at(-1).text,comparison);assert.equal(preview.savedCorrections,correction);
assert.deepEqual(preview.rejectedExamples[0].body,rejected.passages[0].body);
assert.equal(result.payload.plan.readings.find(e=>e.sign==='taurus').ownerEvidence.rejectedExamples.length,0,'Rejection stays with its sign');
result=await action('generate',{sign:'aries',approvedPlanHash:result.payload.plan.planHash});assert.equal(result.status,202,JSON.stringify(result.payload));
let active=row.source_snapshot.horoscopeGeneration.active;
const receipt=active.receipt.ownerEvidence,dispatched=writerFixture.requests.get(active.responseId);
const {sign,...transport}=dispatched;
assert.deepEqual(receipt.providerRequest,transport,'Saved request is the actual provider-bound request, including final governed instructions');
assert.equal(receipt.inputSha256,hash(dispatched.input));
assert.equal(receipt.providerRequest.input,dispatched.input);
assert.equal(receipt.providerRequest.instructions,dispatched.instructions);
assert.deepEqual(receipt.passages,preview.passages,'Preview and writer use the same complete passages');
assertHoroscopeEvidenceDelivered(receipt,dispatched.input);
assert.throws(()=>assertHoroscopeEvidenceDelivered(receipt,'missing input'),/missing/);
assert.throws(()=>assertHoroscopeEvidenceDelivered({...receipt,passages:[{...receipt.passages[0],text:'changed'}]},dispatched.input),/missing/);
assert(dispatched.input.includes(comparison));assert(dispatched.input.includes(correction));
assert(dispatched.input.includes(JSON.stringify(rejected.passages[0].body).slice(1,-1)));
result=await action('poll');assert.equal(result.status,200,JSON.stringify(result.payload));
const completed=row.source_snapshot.horoscopeGeneration.readings.aries.ownerEvidence;
assert.deepEqual(completed,receipt,'The receipt survives writer completion and independent review');
const reviewed=[...writerFixture.reviewRequests.values()].at(-1);
const reviewEvidence=JSON.parse(reviewed.input).evidence;
assert.deepEqual(reviewEvidence.rejectedExamples,receipt.rejectedExamples,'Reviewer receives the same complete edition-and-sign-scoped negative evidence');
const reviewPassages=[...reviewEvidence.ownerExamples,...horoscopeProfileEvidence(reviewEvidence.writingProfile.profile.sourceGuidance).passages];
assert(receipt.passages.every(p=>reviewPassages.some(e=>e.text===p.text)),'Reviewer sees the identical complete evidence');
assert.deepEqual(reviewEvidence.ownerEvidence.passages.map(p=>p.sha256),receipt.passages.map(p=>p.sha256),'Review provenance identifies the exact sources without duplicating their text');
assert.deepEqual(row.source_snapshot.studioWritingProfile,savedProfile);
assert(!JSON.stringify(projectReaderRow(row)).includes(comparison),'Private examples never enter the public reader projection');
assert(!JSON.stringify(projectReaderRow(row)).includes('ownerEvidence'));
assert.equal(writerFixture.calls,1);assert.equal(writerFixture.reviewCalls,1);
// A profile using only the original four variables must still verify source hashes.
const changed={...profile,sourceGuidance:block.replace(comparison,comparison+' altered')+correction};
result=await store.invoke('POST',{profile:changed,expectedUpdatedAt:savedProfile.updatedAt},'/api/admin/generated-content?writingProfiles=true');assert.equal(result.status,200);
result=await action('prepare');assert.equal(result.status,500);assert.equal(writerFixture.calls,1,'Invalid evidence fails before another request');
assert.throws(()=>horoscopeProfileEvidence(block+block),/unique/);
console.log('PASS Weekly evidence bridge: 48 intact canonical units, revoked-source exclusion, auditable ranking, complete private comparisons, sign-scoped rejection, zero-call preview, exact provider receipt, reviewer parity, persistence and public privacy. Simulated provider only.');
