import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { calendarSubscriptionFixture } from "../tests/helpers/calendar-subscription-fixture.js";
import { escapeCalendarText, foldCalendarLine, serializeCalendarFeed, selectCalendarFeedCopy } from "../api/_lib/calendar-feed.js";
import { getCalendarSubscriptionEvents, getLunarCalendarMonth } from "../apps/web/src/services/ephemeris.js";
import { calendarSubscriptionUrls } from "../apps/web/src/features/calendar/calendarSubscription.js";
import { calendarLocalDateKey } from "../apps/web/src/features/calendar/calendarPhaseLabel.js";
import { calendarSkyV4LunationContentKey } from "../apps/web/src/features/calendar/calendarContentKeys.js";
import { verifyCalendarFeedRuntimeImports } from "../tests/helpers/calendar-feed-runtime.mts";

verifyCalendarFeedRuntimeImports();
const fixture = await calendarSubscriptionFixture();
const options = { include: ["key"], reminder: "At the time", timeZone: "America/New_York" };
const owner = { authorization: "Bearer fixture-owner" };
try {
  const deployment = JSON.parse(readFileSync(new URL("../vercel.json", import.meta.url), "utf8"));
  const patterns = Object.keys(deployment.functions);
  assert(patterns.indexOf("api/calendar-feed.ts") < patterns.indexOf("api/**/*.ts"), "Vercel must match the feed's explicit configuration before the catch-all");
  assert.equal(deployment.functions["api/calendar-feed.ts"].includeFiles, "node_modules/swisseph-wasm/wasm/*");
  await fixture.db.exec("set role anon");
  await assert.rejects(fixture.db.query("select * from calendar_subscriptions"), /permission denied/);
  await assert.rejects(fixture.db.query("insert into calendar_feed_events(draft) values ('{}')"), /permission denied/);
  await fixture.db.exec("set role authenticated");
  await assert.rejects(fixture.db.query("select * from calendar_feed_events"), /permission denied/);
  await fixture.db.exec("reset role");
  assert.equal((await fixture.invoke("/api/admin/calendar-feed-events")).status, 401);
  const created = await fixture.invoke("/api/calendar-subscriptions", "POST", options);
  assert.equal(created.status, 201); const subscription = created.json().subscription;
  assert.equal((await fixture.invoke("/api/calendar-subscriptions", "POST", { ...options, include: [] })).status, 400);
  assert.equal((await fixture.invoke("/api/calendar-subscriptions", "POST", { ...options, timeZone: "bad-zone" })).status, 400);
  const second = (await fixture.invoke("/api/calendar-subscriptions", "POST", options)).json().subscription;
  assert.notEqual(subscription.token, second.token);
  const rows = (await fixture.db.query("select token_hash, manage_token_hash from calendar_subscriptions")).rows;
  assert(!JSON.stringify(rows).includes(subscription.token));
  const path = `/feed/${subscription.token}.ics`;
  assert.equal((await fixture.invoke("/feed/not-a-token.ics")).status, 404);
  assert.equal((await fixture.invoke(`/feed/${"Z".repeat(43)}.ics`)).status, 404);
  assert.equal((await fixture.invoke("/api/calendar-subscriptions", "PATCH", { ...options, ...subscription, manageToken: second.manageToken, expectedUpdatedAt: subscription.updatedAt })).status, 409);
  const event = { title: "Community calendar session", description: "Complete first paragraph.\n\nFinal sentence; preserved, exactly. 🌙", start: "2026-10-04T18:00:00.000Z", end: "2026-10-04T19:00:00.000Z", allDay: false, category: "key", url: "https://example.com/event" };
  let saved = (await fixture.invoke("/api/admin/calendar-feed-events", "POST", { action: "draft", event }, owner)).json().event;
  const draftFeed = await fixture.invoke(path); assert.equal(draftFeed.status, 200); assert(!draftFeed.body.includes(event.title));
  let published = await fixture.invoke("/api/admin/calendar-feed-events", "PATCH", { action: "publish", event, id: saved.id, expectedUpdatedAt: saved.updated_at }, owner);
  assert.equal(published.status, 200); saved = published.json().event;
  const first = await fixture.invoke(path); assert.equal(first.status, 200); assert.match(first.headers["content-type"], /text\/calendar/); assert(first.body.includes(event.title));
  const uid = `event-${saved.id}@tldrastro`; assert(first.body.includes(`UID:${uid}`)); assert(first.body.includes("TRIGGER:PT0S"));
  assert(first.body.replace(/\r\n /gu, "").includes(`DESCRIPTION:${escapeCalendarText(event.description)}`));
  assert.equal((await fixture.invoke(path, "HEAD")).body, "");
  assert.equal((await fixture.invoke(path, "GET", undefined, { "if-none-match": first.headers.etag })).status, 304);
  const changed = { ...event, title: "Updated community session", description: "Owner's complete revised body.\nFinal revised sentence." };
  const beforeDraft = saved.updated_at;
  saved = (await fixture.invoke("/api/admin/calendar-feed-events", "PATCH", { action: "draft", event: changed, id: saved.id, expectedUpdatedAt: saved.updated_at }, owner)).json().event;
  assert.equal((await fixture.invoke(path)).headers.etag, first.headers.etag, "Drafts do not change published feed or ETag");
  assert.equal((await fixture.invoke("/api/admin/calendar-feed-events", "PATCH", { action: "publish", event: changed, id: saved.id, expectedUpdatedAt: beforeDraft }, owner)).status, 409);
  saved = (await fixture.invoke("/api/admin/calendar-feed-events", "PATCH", { action: "publish", event: changed, id: saved.id, expectedUpdatedAt: saved.updated_at }, owner)).json().event;
  const updated = await fixture.invoke(path, "GET", undefined, { "if-none-match": first.headers.etag });
  assert.equal(updated.status, 200); assert.notEqual(updated.headers.etag, first.headers.etag); assert(updated.body.includes(changed.title)); assert.equal(updated.body.split(`UID:${uid}`).length, 2); assert(updated.body.includes("SEQUENCE:2"));
  assert((await fixture.invoke(`/feed/${second.token}.ics`)).body.includes(changed.title), "Existing subscriptions receive additions and edits");
  const changedOptions = await fixture.invoke("/api/calendar-subscriptions", "PATCH", { ...options, reminder: "Day before", ...subscription, expectedUpdatedAt: subscription.updatedAt });
  assert.equal(changedOptions.status, 200);
  const preferred = (await fixture.invoke(path)).body.split("BEGIN:VEVENT").find(part => part.includes(`UID:${uid}`))!;
  assert(preferred.includes("TRIGGER:-P1D")); assert(preferred.includes("SEQUENCE:3"), "Preference changes advance the event version");
  saved = (await fixture.invoke("/api/admin/calendar-feed-events", "PATCH", { action: "cancel", id: saved.id, expectedUpdatedAt: saved.updated_at }, owner)).json().event;
  const cancelled = (await fixture.invoke(path)).body.split("BEGIN:VEVENT").find(part => part.includes(`UID:${uid}`))!;
  assert(cancelled.includes("STATUS:CANCELLED")); assert(cancelled.includes("SEQUENCE:4")); assert(!cancelled.includes("BEGIN:VALARM"));
  assert.equal((await fixture.invoke("/api/admin/calendar-feed-events", "POST", { action: "draft", event: { ...event, start: "2026-02-30T18:00:00.000Z" } }, owner)).status, 400);
  assert.equal((await fixture.invoke("/api/admin/calendar-feed-events", "POST", { action: "publish", event: { ...event, url: "javascript:alert(1)" } }, owner)).status, 400);
  assert.equal((await fixture.invoke("/api/admin/calendar-feed-events", "POST", { action: "publish", event: { ...event, description: "{{unresolved}}" } }, owner)).status, 422);
  fixture.setStorageFailure(true); assert.equal((await fixture.invoke(path)).status, 503); fixture.setStorageFailure(false);
  const folded = foldCalendarLine("DESCRIPTION:" + "🌙 naïve, ".repeat(40));
  for (const line of folded.split("\r\n")) assert(Buffer.byteLength(line) <= 75);
  assert.equal(folded.replace(/\r\n /gu, ""), "DESCRIPTION:" + "🌙 naïve, ".repeat(40));
  const allDay = serializeCalendarFeed([{ ...event, uid: "day@tldrastro", start: "2026-10-04", end: "2026-10-05", allDay: true, modified: "2026-09-22T00:00:00Z", sequence: 1 }], options as any);
  assert(allDay.includes("DTSTART;VALUE=DATE:20261004\r\nDTEND;VALUE=DATE:20261005"));
  const links = calendarSubscriptionUrls(subscription.token, "https://calendar.example"); assert(links.https.startsWith("https://calendar.example/feed/")); assert(links.webcal.startsWith("webcal://")); assert.equal(new URL(links.google).searchParams.get("cid"), links.webcal);
  // Request-scoped publication selection cannot leak drafts, retired rows or stale versions.
  const key = "sky.test.calendar", source = { id: "source", content_key: key, status: "LIVE", lane: "serving", body: "Exact published first and last sentence.", updated_at: "2026-09-22T00:00:00Z", source_snapshot: { review_status: "approved" } };
  const ledger = new Map([[key, { content_key: key, state: "live", revision: 1, row_id: source.id, row_updated_at: source.updated_at, updated_at: source.updated_at } as any]]);
  assert.equal(selectCalendarFeedCopy([key], "2026-10-04", [source], ledger)?.body, source.body);
  assert.equal(selectCalendarFeedCopy([key], "2026-10-04", [{ ...source, updated_at: "2026-09-23T00:00:00Z" }], ledger), null);
  assert.equal(selectCalendarFeedCopy([key], "2026-10-04", [{ ...source, sections: { packageDraft: { Body: "private" } } }], ledger), null);
  ledger.get(key).state = "retired"; assert.equal(selectCalendarFeedCopy([key], "2026-10-04", [source], ledger), null);
  // Compare two separate dates with the actual Calendar calculation, never catalog dates.
  const calculated = await getCalendarSubscriptionEvents(2026);
  const moon = calculated.find(event => event.type === "lunation" && event.primary && event.dateKey !== calendarLocalDateKey(event.startsAt, "America/New_York"))!;
  assert(moon, "Exercise an event that occurs on different local and UTC dates");
  const localDate = calendarLocalDateKey(moon.startsAt, "America/New_York");
  const moonKey = calendarSkyV4LunationContentKey({ ...moon, dateKey: localDate })!;
  const rowId = "af2f1000-0000-4000-8000-000000000001";
  await fixture.db.query("insert into generated_interpretations(id,content_key,target_date,status,lane,body,updated_at,source_snapshot) values($1,$2,$3,'LIVE','serving',$4,now(),$5)", [rowId, moonKey, localDate, "Published opening. Complete published ending.", JSON.stringify({ review_status: "approved" })]);
  await fixture.db.query("insert into content_publications(content_key,state,revision,row_id,row_updated_at,updated_at) select content_key,'live',1,id,updated_at,updated_at from generated_interpretations where id=$1", [rowId]);
  const moonSub = (await fixture.invoke("/api/calendar-subscriptions", "POST", { ...options, include: ["lunations"] })).json().subscription;
  const moonPath = `/feed/${moonSub.token}.ics`;
  const moonFeed = (await fixture.invoke(moonPath)).body.replace(/\r\n /gu, "");
  assert(moonFeed.includes("DESCRIPTION:Published opening. Complete published ending."), "Published Calendar copy uses the subscriber's local event date");
  assert(!moonFeed.includes("Quarter Moon"));
  assert(moonFeed.includes(`/#calendar?date=${localDate}`));
  // Dated content uses the shared LIVE/serving gate; undated sources also
  // require the exact ledger version (checked above).
  await fixture.db.query("update generated_interpretations set body=$2,status='DRAFT',lane='reference',updated_at=clock_timestamp() where id=$1", [rowId, "Revised published opening. Complete revised ending."]);
  assert(!(await fixture.invoke(moonPath)).body.includes("Revised published opening"), "Draft Calendar copy cannot enter a subscription");
  await fixture.db.query("update generated_interpretations set status='LIVE',lane='serving',updated_at=clock_timestamp() where id=$1", [rowId]);
  await fixture.db.query("update content_publications set row_updated_at=(select updated_at from generated_interpretations where id=$1),updated_at=clock_timestamp(),revision=2 where content_key=$2", [rowId, moonKey]);
  assert((await fixture.invoke(moonPath)).body.replace(/\r\n /gu, "").includes("DESCRIPTION:Revised published opening. Complete revised ending."), "Existing URL reads newly published copy without redeployment");
  for (const month of [2, 8]) {
    const calendar = await getLunarCalendarMonth({ label: "UTC", latitude: 0, longitude: 0, timeZone: "UTC" }, new Date(Date.UTC(2026, month, 15)), { detail: "full" });
    const fullMoon = calendar.events.find(item => item.type === "lunation" && item.title.includes("Full") && Number(item.dateKey.slice(5, 7)) === month + 1)!;
    const equivalent = calculated.find(item => item.type === "lunation" && item.title === fullMoon.title && item.dateKey === fullMoon.dateKey)!;
    assert(equivalent); assert(Math.abs(Date.parse(equivalent.startsAt) - Date.parse(fullMoon.startsAt)) < 60000);
  }
  console.log("PASS calendar subscriptions: actual handlers + PostgreSQL migration, unique URLs, auth/RLS, draft/publish/edit/cancel, same-URL refresh, ETag, reminders, full text, UTF-8 folding, provider links and calculation parity");
} finally { await fixture.close(); }
