import assert from 'node:assert/strict';
import {parseTemplate,renderTemplate} from '../src/monthly-writing/template';
import {createMonthlyEdition,monthlyTargets,renderMonthly,applyMonthlyPhrases,validateMonthlyTemplate,validateMonthlyEdition,stableJson} from '../src/monthly-writing/model';
import {monthlyTemplateStarter} from '../src/monthly-writing/starter';
import {monthlyFixture} from '../tests/monthly-writing/fixtures';
const render=(pattern:string,definitions:any={},context:any={})=>renderTemplate(pattern,definitions,context,{phrase:(name,def)=>({value:def.value})});
const nested={one:{kind:'template',value:'Before {{two}} after'},two:{kind:'template',value:'{{word}}'},word:{kind:'phrase',value:'fixture'}};
assert.equal(render('{{one}}',nested).text,'Before fixture after');
assert.deepEqual(render('{{empty}}',{empty:{kind:'template',value:''}}).issues,[]);
assert.match(render('{{one}}',{one:{kind:'template',value:'{{two}}'},two:{kind:'template',value:'{{one}}'}}).issues[0].message,/Circular/);
assert.throws(()=>parseTemplate('{{#a}}{{#a}}ok{{/a}}{{/b}}'),/Mismatched/);
assert.throws(()=>parseTemplate('{{constructor}}'),/Unsupported/);
assert.throws(()=>parseTemplate('{{{raw}}}'),/braces/);
assert.throws(()=>parseTemplate('{{#open}}'),/Unclosed/);
assert.equal(render('{{#flag}}{{missing}}{{/flag}}{{^flag}}safe{{/flag}}',{}, {flag:false}).text,'safe');
assert.equal(render('{{#items}}{{card}}{{/items}}',{card:{kind:'template',value:'{{label}};'}},{items:[{label:'First'},{label:'Second'}]}).text,'First;Second;');
assert.equal(render('{{#items}}{{#flag}}{{label}}{{/flag}}{{/items}}',{}, {items:[{flag:true,label:'A'},{flag:false,label:'B'}]}).text,'A');
assert(render('{{#typo}}hidden{{/typo}}').issues.some(issue=>issue.code==='unknown_variable'));
assert(render('{{bad}}',{bad:{kind:'phrase',value:'{{injected}}'}}).issues.some(issue=>issue.code==='literal_token'));
const facts=monthlyFixture(),template=monthlyTemplateStarter(),edition=createMonthlyEdition(facts,template);
assert(!JSON.stringify(template).includes('northNodeHoroscopes'));
const first=monthlyTargets(facts,edition);
assert(!first.rendered.issues.some(issue=>['transitOverview','lunarOverview','monthlyIntegration'].includes(issue.name)));
assert(!first.targets.some(target=>target.name==='primaryMonthlyThemeFocus'));
assert(first.targets.filter(target=>target.name==='eventFocus').every(target=>/new|full/u.test(target.eventId)));
assert(!first.rendered.text.includes('eclipse'));
assert(!first.rendered.text.includes('primaryMonthlyThemeFocus'));
edition.themeCount=2;
assert(monthlyTargets(facts,edition).targets.some(target=>target.name==='secondaryMonthlyThemeFocus'));
const filled=applyMonthlyPhrases(edition,monthlyTargets(facts,edition).targets.map(target=>({...target,value:target.name.includes('Focus')?'fixture focus':target.definition.grammar==='verb-phrase'?'make a fixture change':'a fixture experience'})));
const before=stableJson(filled.template);
assert.equal(renderMonthly(facts,filled).issues.length,0);
assert.equal(stableJson(filled.template),before,'Assembly must not flatten patterns');
const leaf=monthlyTargets(facts,filled).targets[0];filled.locked=[leaf.id];
assert.throws(()=>applyMonthlyPhrases(filled,[{...leaf,value:'replacement'}]),/protected/);
assert.throws(()=>applyMonthlyPhrases(filled,[{id:'edition::monthlyOverview',name:'monthlyOverview',eventId:'',value:'flattened paragraph'}]),/non-phrase/);
assert.throws(()=>validateMonthlyTemplate({...template,definitions:{...template.definitions,monthName:{kind:'phrase',value:'Fake'}}}),/reserved/);
assert.throws(()=>validateMonthlyEdition({...filled,month:'invalid'}),/month/);
assert.throws(()=>validateMonthlyEdition({...edition,themeCount:1,leadEventId:null,supportingEventIds:[]}),/reviewed event/);
assert.throws(()=>renderMonthly({...facts,fingerprint:'changed'},filled),/changed/);
assert.throws(()=>renderMonthly({...facts,month:'2027-09'},filled),/changed/);
const nextYear=createMonthlyEdition(monthlyFixture('2027-09'),template);assert.equal(Object.keys(nextYear.values).length,0);
const eclipses=structuredClone(facts);eclipses.events[2].type='solar-eclipse';eclipses.events[3].type='lunar-eclipse';
const eclipseEdition=createMonthlyEdition(eclipses,template);const ec=renderMonthly(eclipses,eclipseEdition).text;
assert(ec.includes('Solar eclipse')&&ec.includes('Lunar eclipse'));assert(!ec.includes('## New Moon')&&!ec.includes('## Full Moon'));
const sourceTemplate=monthlyTemplateStarter();sourceTemplate.body='{{openingSeasonFocus}} / {{closingSeasonFocus}}';
sourceTemplate.definitions.openingSeasonFocus.libraryName='seasonFocus';sourceTemplate.definitions.closingSeasonFocus.libraryName='seasonFocus';
const se=createMonthlyEdition(facts,sourceTemplate);
se.librarySnapshot=[{id:'v',name:'seasonFocus',value:'base',updatedAt:'v1',overrides:[{scope:'sign',planet:'',sign:'virgo',value:'first'},{scope:'sign',planet:'',sign:'libra',value:'second'}]}];
assert.equal(renderMonthly(facts,se,[{...se.librarySnapshot[0],value:'new value',overrides:[]}]).text,'first / second','Saved editions use pinned library values');
assert.equal(stableJson({b:1,a:{d:2,c:3}}),stableJson({a:{c:3,d:2},b:1}));
console.log('PASS monthly templates: recursion, conditions, scoped repetitions, cycles, literal boundaries, seasonal vs monthly themes, per-year editions, eclipse de-duplication, protected phrases, and pinned library values.');
