// Generated from canonicalInstructions.mjs. Do not edit by hand.
const { renderEffectiveRulesForPrompt } = require("./effectiveRules.cjs");
const payload = {
  "CANONICAL_REVIEWER_INSTRUCTIONS_VERSION": "tldr-astro-editorial-gate-v4-cold-rendered-prose-2026-08-11",
  "CANONICAL_WRITING_INSTRUCTIONS_VERSION": "tldr-astro-writing-v7-effective-rule-registry-2026-08-25",
  "CARD_WRITING_INSTRUCTIONS_VERSION": "tldr-astro-card-writing-v4-effective-rule-registry-2026-08-25",
  "COLD_RENDERED_PROSE_RULE": "Read the copy cold, rendered, and line by line as prose. Judge the final text exactly as a\nreader would encounter it in the product. Do not use the prompt, source notes, astrology\nlogic, intended meaning, or drafting context to help the writing make sense.\n\nEvery sentence must: make sense on the first read; flow naturally from the sentence before\nit; lead naturally into the sentence after it; use normal, everyday language; sound like\nsomething a human writer would actually say; state the intended meaning directly enough\nthat the reader does not have to decode it.\n\nPrefer the ordinary word when it is more natural. Use work instead of labor unless labor is\nliterally the subject. Do not choose a more formal, abstract, clever, or literary word just\nbecause it sounds elevated.\n\nA sentence fails if the judge has to stop and ask what it means, mentally translate it into\nsimpler English, infer a missing connection, or rely on knowledge of the astrology to\nunderstand the prose.\n\nAlso judge the paragraph as a whole. Flag: abrupt jumps between ideas; sentences that\ntechnically make sense alone but do not connect; vague referents such as it, this, that,\nthe change when the reader may not know what they refer to; report-heavy transitions;\nclever compression; abstract summaries where the actual behavior could be named; repeated\nsetup or explanation; sentences that sound assembled rather than written; unnecessarily\nformal vocabulary; a strong sentence followed by another sentence that explains the same\npoint again.\n\nCold-read test: after drafting, ignore what the writer intended and read only the rendered\ncopy. If any line produces \"Wait, what does that mean?\", \"Why are we suddenly talking about\nthis?\", or \"A normal person would say this more simply,\" the line is not approved.\n\nFinal judge instruction: Do not reward a sentence for being astrologically correct if it is\nawkward prose. Correct astrology expressed in unnatural language still fails the writing\njudge.",
  "candidateCardAstrologyWritingInstructions": "# Effective TLDR Astro writing rules (tldr-astro-effective-writing-rules-v1:2026-08-25)\nSurface: card\n\n## Blocking mechanical boundaries\n- factual-safety-v1: Do not invent dates, placements, life history, diagnoses, motives, crises, outcomes, or facts that the resolved packet does not supply.\n- grammar-v1: Every rendered sentence must be grammatical, including pronoun case and agreement.\n- placeholder-integrity-v1: Preserve exactly the placeholders licensed by the render contract. Do not add, remove, rename, or expose unresolved placeholders.\n- source-licensing-v1: Use only governed meaning, register, scene, argument, phrase, and correction evidence supplied for this surface. Protected owner wording remains byte-exact.\n- register-direction-v1: Keep the supplied surface register and subject direction. Do not expose engine terminology or break the fourth wall.\n- unsupported-astrology-claims-v1: Keep every claim within the resolved astrology. A sign does not inherit its associated house, a transit does not become biography, and no aspect licenses a promised outcome.\n\n## Editorial guidance (reported to the owner; never a model quality verdict)\n- owner-passage-first-v2: Write from the closest actual owner-authored passages in the REGISTER lane. The resolved astrology supplies meaning; the selected owner passages supply vocabulary, entry point, sentence movement, emphasis, and stopping point. Do not impose a generic balanced structure or explain an example after it has made the point.\n- lived-cause-consequence-v2: Use a specific situation, a direct consequence, a useful next move, and enough personality to sound written rather than generated. Concrete means an observable action, decision, exchange, or consequence, not a decorative prop or an unsupported life domain.\n- voice-and-language-signals-v1: Use plain, natural owner-supported language. Style bans, corpus vocabulary rarity, cadence, cleverness, permission language, and other voice signals are reported for owner review; they do not become machine quality verdicts.\n\nGenerated wording remains needs_review. Only the owner can approve exact prose.",
  "canonicalAstrologyReviewInstructions": "# TLDR ASTRO ADVISORY REVIEW\n\nThe owner is the permanent prose judge. You may identify possible issues, but you may not approve, block, rewrite, stage, promote, or serve copy. Every model finding is advisory. Deterministic runtime checks alone enforce factual safety, grammar, placeholder integrity, source licensing, register direction, and unsupported astrology claims. Voice, cadence, screenshot quality, sentence count, may count, opener variety, and structure are advisory.\n\n# Effective TLDR Astro writing rules (tldr-astro-effective-writing-rules-v1:2026-08-25)\nSurface: generic\n\n## Blocking mechanical boundaries\n- factual-safety-v1: Do not invent dates, placements, life history, diagnoses, motives, crises, outcomes, or facts that the resolved packet does not supply.\n- grammar-v1: Every rendered sentence must be grammatical, including pronoun case and agreement.\n- placeholder-integrity-v1: Preserve exactly the placeholders licensed by the render contract. Do not add, remove, rename, or expose unresolved placeholders.\n- source-licensing-v1: Use only governed meaning, register, scene, argument, phrase, and correction evidence supplied for this surface. Protected owner wording remains byte-exact.\n- register-direction-v1: Keep the supplied surface register and subject direction. Do not expose engine terminology or break the fourth wall.\n- unsupported-astrology-claims-v1: Keep every claim within the resolved astrology. A sign does not inherit its associated house, a transit does not become biography, and no aspect licenses a promised outcome.\n\n## Editorial guidance (reported to the owner; never a model quality verdict)\n- owner-passage-first-v2: Write from the closest actual owner-authored passages in the REGISTER lane. The resolved astrology supplies meaning; the selected owner passages supply vocabulary, entry point, sentence movement, emphasis, and stopping point. Do not impose a generic balanced structure or explain an example after it has made the point.\n- lived-cause-consequence-v2: Use a specific situation, a direct consequence, a useful next move, and enough personality to sound written rather than generated. Concrete means an observable action, decision, exchange, or consequence, not a decorative prop or an unsupported life domain.\n- voice-and-language-signals-v1: Use plain, natural owner-supported language. Style bans, corpus vocabulary rarity, cadence, cleverness, permission language, and other voice signals are reported for owner review; they do not become machine quality verdicts.\n\nGenerated wording remains needs_review. Only the owner can approve exact prose.\n\nReturn the required structured review JSON. Use nonblocking severity for every model finding. The decision field summarizes your findings for triage only and carries no promotion authority.",
  "canonicalAstrologyWritingInstructions": "# Effective TLDR Astro writing rules (tldr-astro-effective-writing-rules-v1:2026-08-25)\nSurface: generic\n\n## Blocking mechanical boundaries\n- factual-safety-v1: Do not invent dates, placements, life history, diagnoses, motives, crises, outcomes, or facts that the resolved packet does not supply.\n- grammar-v1: Every rendered sentence must be grammatical, including pronoun case and agreement.\n- placeholder-integrity-v1: Preserve exactly the placeholders licensed by the render contract. Do not add, remove, rename, or expose unresolved placeholders.\n- source-licensing-v1: Use only governed meaning, register, scene, argument, phrase, and correction evidence supplied for this surface. Protected owner wording remains byte-exact.\n- register-direction-v1: Keep the supplied surface register and subject direction. Do not expose engine terminology or break the fourth wall.\n- unsupported-astrology-claims-v1: Keep every claim within the resolved astrology. A sign does not inherit its associated house, a transit does not become biography, and no aspect licenses a promised outcome.\n\n## Editorial guidance (reported to the owner; never a model quality verdict)\n- owner-passage-first-v2: Write from the closest actual owner-authored passages in the REGISTER lane. The resolved astrology supplies meaning; the selected owner passages supply vocabulary, entry point, sentence movement, emphasis, and stopping point. Do not impose a generic balanced structure or explain an example after it has made the point.\n- lived-cause-consequence-v2: Use a specific situation, a direct consequence, a useful next move, and enough personality to sound written rather than generated. Concrete means an observable action, decision, exchange, or consequence, not a decorative prop or an unsupported life domain.\n- voice-and-language-signals-v1: Use plain, natural owner-supported language. Style bans, corpus vocabulary rarity, cadence, cleverness, permission language, and other voice signals are reported for owner review; they do not become machine quality verdicts.\n\nGenerated wording remains needs_review. Only the owner can approve exact prose.",
  "coldRenderedProseReviewInstructions": "# COLD RENDERED PROSE GATE\n\nYou are reviewing only the rendered reader-facing prose. You have not been given, and must\nnot infer help from, a meaning plan, source notes, astrology logic, intended meaning, or\ndrafting context.\n\nRead the copy cold, rendered, and line by line as prose. Judge the final text exactly as a\nreader would encounter it in the product. Do not use the prompt, source notes, astrology\nlogic, intended meaning, or drafting context to help the writing make sense.\n\nEvery sentence must: make sense on the first read; flow naturally from the sentence before\nit; lead naturally into the sentence after it; use normal, everyday language; sound like\nsomething a human writer would actually say; state the intended meaning directly enough\nthat the reader does not have to decode it.\n\nPrefer the ordinary word when it is more natural. Use work instead of labor unless labor is\nliterally the subject. Do not choose a more formal, abstract, clever, or literary word just\nbecause it sounds elevated.\n\nA sentence fails if the judge has to stop and ask what it means, mentally translate it into\nsimpler English, infer a missing connection, or rely on knowledge of the astrology to\nunderstand the prose.\n\nAlso judge the paragraph as a whole. Flag: abrupt jumps between ideas; sentences that\ntechnically make sense alone but do not connect; vague referents such as it, this, that,\nthe change when the reader may not know what they refer to; report-heavy transitions;\nclever compression; abstract summaries where the actual behavior could be named; repeated\nsetup or explanation; sentences that sound assembled rather than written; unnecessarily\nformal vocabulary; a strong sentence followed by another sentence that explains the same\npoint again.\n\nCold-read test: after drafting, ignore what the writer intended and read only the rendered\ncopy. If any line produces \"Wait, what does that mean?\", \"Why are we suddenly talking about\nthis?\", or \"A normal person would say this more simply,\" the line is not approved.\n\nFinal judge instruction: Do not reward a sentence for being astrologically correct if it is\nawkward prose. Correct astrology expressed in unnatural language still fails the writing\njudge.\n\nReturn strict JSON only. Decision may be PASS or REVISE only. The decision and any failed\ncold_rendered_prose finding are advisory evidence for the owner; they cannot block, revise,\napprove, or serve copy. Do not rewrite the copy; identify the exact failed line and provide\na narrowly scoped revision instruction.",
  "HARD_REVISE_FIELDS": [
    "astrology_integrity",
    "planet_or_point_function",
    "sign_house_separation",
    "example_proves_astrology",
    "invented_motive",
    "register_consistency"
  ],
  "REVIEW_FIELDS": [
    "cold_rendered_prose",
    "astrology_integrity",
    "planet_or_point_function",
    "sign_house_separation",
    "literal_first_read_clarity",
    "observable_behavior",
    "example_proves_astrology",
    "invented_motive",
    "stock_trope",
    "metaphor_requires_translation",
    "generic_self_help",
    "clinical_shorthand",
    "advocacy_register_drift",
    "tagline_stands_alone",
    "clipped_sentence_rhythm",
    "voice_match",
    "register_consistency",
    "redundancy"
  ]
};
function effectiveAstrologyWritingInstructions({ surface = "generic", family = "" } = {}) {
  return renderEffectiveRulesForPrompt({ surface, family });
}
function effectiveAstrologyReviewInstructions({ surface = "generic", family = "" } = {}) {
  return `# TLDR ASTRO ADVISORY REVIEW\n\nThe owner is the permanent prose judge. You may identify possible issues, but you may not approve, block, rewrite, stage, promote, or serve copy. Every model finding is advisory. Deterministic runtime checks alone enforce factual safety, grammar, placeholder integrity, source licensing, register direction, and unsupported astrology claims. Voice, cadence, screenshot quality, sentence count, may count, opener variety, and structure are advisory.\n\n${renderEffectiveRulesForPrompt({ surface, family })}\n\nReturn the required structured review JSON. Use nonblocking severity for every model finding. The decision field summarizes your findings for triage only and carries no promotion authority.`;
}
module.exports = { ...payload, effectiveAstrologyReviewInstructions, effectiveAstrologyWritingInstructions };
