/** Semantic roles for the live reader. Concrete values live in theme.css. */
export const liveTokenRoles = {
  surfacePage: "--bg",
  surfacePanel: "--surface",
  surfaceRaised: "--surface-2",
  textPrimary: "--ink",
  textSecondary: "--ink-2",
  textMuted: "--muted",
  borderDefault: "--line",
  borderSubtle: "--line-2",
  borderStrong: "--line-strong",
  cardFill: "--card-bg",
  cardStroke: "--card-border",
  cardRadius: "--card-radius",
  cardShadow: "--card-shadow",
  fontDisplay: "--font-display",
  fontBody: "--font-body",
  fontUi: "--font-ui",
  fontLabel: "--font-label",
  fontGlyph: "--font-glyph",
  textBody: "--text-body",
  leadingBody: "--leading-body",
  trackingBody: "--tracking-body",
  stackGap: "--stack-gap",
  sectionGap: "--section-gap",
  pageWidth: "--container-app-wide"
} as const;

export const liveTokenSources = {
  "--bg": "theme.css",
  "--surface": "theme.css",
  "--surface-2": "theme.css",
  "--ink": "theme.css",
  "--ink-2": "theme.css",
  "--muted": "theme.css",
  "--line": "theme.css",
  "--line-2": "theme.css",
  "--line-strong": "theme.css",
  "--card-bg": "theme.css",
  "--card-border": "theme.css",
  "--card-radius": "theme.css",
  "--card-shadow": "theme.css",
  "--font-display": "theme.css",
  "--font-body": "theme.css",
  "--font-ui": "theme.css",
  "--font-label": "theme.css",
  "--font-glyph": "theme.css",
  "--text-body": "theme.css",
  "--leading-body": "theme.css",
  "--tracking-body": "theme.css",
  "--stack-gap": "theme.css",
  "--section-gap": "theme.css",
  "--container-app-wide": "theme.css"
} as const;
