import { zodiacSignOrder } from "./moonSignTransitions.js";
import { calendarSeasonTransitionCountdown } from "./calendarSeasonTransitionFacts.js";

export {
  calendarSeasonTransitionCountdown,
  calendarSeasonTransitionFactsFromSun,
  calendarSeasonTransitionIsCurrent
} from "./calendarSeasonTransitionFacts.js";

/** Owner-provided pair-specific season-change copy. Not generated summaries. */
export const calendarSeasonTransitions: Record<string, string[]> = {
  "pisces-aries": [
    "Pisces season ends {{date}}, when the Sun enters Aries. After a month of sitting with uncertainty or letting something come to an end, our attention shifts toward the choices we can make now. You may not know how a conversation will go, where an application will lead, or how someone will respond to a boundary, but waiting cannot answer all of those questions for you. Aries season helps us act on what we do know and learn from what happens next, rather than treating certainty as a condition for beginning.",
    "Aries season begins {{date}}, when the Sun enters Aries. The Sun's time in Pisces can make us more aware of feelings we have been putting aside, including our own. Aries brings that awareness into the choices we make. You may understand why someone needs your help and still need to tell them what you can offer, or recognize that you have been going along with a plan you no longer want. Acting on that knowledge does not erase your care for anyone else. It gives your own wishes a say in what happens next, even when the decision disappoints someone.",
    "Aries season begins {{date}}, when the Sun enters Aries. The Sun's time in Pisces can give an idea time to develop before we know how to explain it. In Aries, we begin to find out what happens when we try it. You may have been imagining a project without knowing its final form, then discover that making a first version answers questions that thinking alone could not. Something you pictured may work differently in practice, or an unexpected result may give you a clearer direction. Beginning does not require knowing exactly what you will produce; it gives you an experience you can use to decide what comes next.",
    "Aries season begins {{date}}, when the Sun enters Aries. After a month with the Sun in Pisces, paying attention to what we feel becomes a reason to make a choice. You may understand why someone needs your help and still dread agreeing to one more thing. Understanding their situation hasn't changed your availability, but somehow your own plans are already the first thing you consider canceling. Aries season brings your wishes back into the decision. Before you offer the evening you had set aside for yourself, consider what you can give without resenting it. You can care about someone's disappointment without treating it as proof that you should have said yes.",
    "Aries season begins {{date}}, when the Sun enters Aries. After a month with the Sun in Pisces, what we've been imagining gives us something to try. The idea may be vivid in your head and harder to explain when someone wants to know how it would work. You don't need a finished plan, but you may need a first attempt. Aries season brings attention to what you can learn by making something, sending the proposal, or testing the part you keep thinking about. The result may change your original idea, and that is useful information rather than a reason you should have waited. Give yourself a chance to discover what the idea can become outside your imagination."
  ],
  "aries-taurus": [
    "Aries season ends {{date}}, when the Sun enters Taurus. After a month of starting things and acting on what we want, we begin to notice how those choices feel to live with. You can still want what you started and find that the pace leaves you exhausted, the cost strains your budget, or the effort leaves little time to enjoy it. Taurus season brings attention to what we can sustain and what makes the effort worthwhile. We may need to slow down or change how we spend our resources so that enjoying our lives does not keep becoming something we postpone until the work is done.",
    "Taurus season begins {{date}}, when the Sun enters Taurus. The Sun's time in Aries may have helped us act on something we had wanted for a while. Taurus turns our attention to giving that choice enough support to continue. You might set aside a regular afternoon for a project instead of giving it every spare hour, or notice that doing less at once lets you enjoy the work rather than rush through it. The effort needs to fit the life you have, including your need for rest and pleasure. A manageable pace gives something new time to become a valued part of your life, rather than another demand you dread returning to.",
    "Taurus season begins {{date}}, when the Sun enters Taurus. After the Sun's time in Aries has drawn attention to what we want to pursue, Taurus brings us closer to the results and how we want to live with them. You may have reached a milestone and already begun planning the next one, before noticing what has become easier or letting yourself enjoy what you achieved. Taurus gives pleasure a place alongside progress. We can decide which efforts still deserve our resources and which have already done what we needed them to do, without inventing another challenge before we have had a chance to appreciate the change.",
    "Taurus season begins {{date}}, when the Sun enters Taurus. After a month with the Sun in Aries, the things we were eager to begin need a pace we can live with. You may still love the project and dread opening your laptop because every session turns into another late night. Wanting something doesn't give you an unlimited supply of energy. Taurus season brings attention to the conditions that make continuing feel worthwhile, including enough rest to enjoy what you're doing. Decide when you'll work and when you'll stop, rather than making exhaustion the thing that ends the day. You're trying to give something a lasting place in your life, not prove how much of your life you can give up for it.",
    "Taurus season begins {{date}}, when the Sun enters Taurus. After a month with the Sun in Aries, pursuing what we want gives way to noticing what our efforts have made possible. You reach a goal, feel pleased for half an hour, then start planning the next one before the achievement has changed anything about how you live. Taurus season brings you back to what you hoped the progress would give you. Notice what has become easier, enjoy what you've worked for, and let some of that satisfaction last longer than the announcement. There will be other things to pursue. You don't have to make this accomplishment smaller in order to give yourself a reason to keep going."
  ],
  "taurus-gemini": [
    "Taurus season ends {{date}}, when the Sun enters Gemini. After a month of deciding what is worth keeping, building, or investing in, new information can give us a reason to reconsider. You may discover that the terms are different from what you understood, learn about an option you had overlooked, or have a conversation that changes what you thought you wanted. Gemini season helps us stay curious enough to revise a decision using the information we have now, rather than defending what we believed before. Changing our minds does not mean the earlier choice was a mistake.",
    "Gemini season begins {{date}}, when the Sun enters Gemini. The Sun's time in Taurus can help us recognize what is worth our continued attention. Gemini builds on that investment through the ideas and approaches we encounter when we talk to other people. You might hear how someone solved a problem you keep encountering, then try a method that makes your own work easier. A commitment does not have to come with a fixed opinion about how everything should be done. We can keep caring about the same thing while learning new ways to develop it, especially when we are willing to ask questions instead of assuming we have already found the only useful answer.",
    "Gemini season begins {{date}}, when the Sun enters Gemini. What we learned about our priorities during the Sun's time in Taurus helps us ask more useful questions. You may know what you want from an opportunity and now need to find out what is included, what can be negotiated, or how it compares with another option. Gemini brings attention to those exchanges, including the follow-up question we almost leave unasked because we assume we should already know. Clearer information gives us more to work with when we choose. What matters to us can remain the same while our understanding of the available options becomes broader.",
    "Gemini season begins {{date}}, when the Sun enters Gemini. After a month with the Sun in Taurus, what we've invested in gives us a reason to get curious. Someone mentions a different way of handling a task you've been struggling with, and suddenly a problem you thought you had to tolerate looks more workable. Before explaining why their approach wouldn't suit you, find out how it works. You may use only part of it, but that part could save you hours. Gemini season builds on your experience by giving you more to compare it with. You've already put time into learning how to do this; you don't have to spend the next six months proving you never need anyone else's advice.",
    "Gemini season begins {{date}}, when the Sun enters Gemini. After a month with the Sun in Taurus, knowing what matters to us helps us ask better questions about the options available. You hear an enthusiastic description of an opportunity, but still don't know what you would be expected to do. Instead of admitting that, you catch yourself nodding along because everyone else sounds so certain. Gemini season brings attention to the missing detail. Go back and ask about the time involved, the expectations, or the part of the explanation that didn't make sense. Being easy to talk to doesn't require pretending everything is clear. Learning what an opportunity involves gives you a better chance of choosing something you'll be glad you accepted."
  ],
  "gemini-cancer": [
    "Gemini season ends {{date}}, when the Sun enters Cancer. After a month of talking things through and comparing possibilities, we begin to notice what we need once the conversation is over. You may feel tense before one visit and at ease before another, or realize that being the person everyone relies on has left you with little support of your own. Cancer season helps us take those responses seriously as we decide where to give our time and care. Understanding everyone's reasons matters, but so does noticing which relationships and routines allow us to rest, feel connected, and receive support as well as give it.",
    "Cancer season begins {{date}}, when the Sun enters Cancer. Conversations during the Sun's time in Gemini may have helped us discover who we enjoy hearing from and what we want to talk about more openly. Cancer brings attention to how we make those connections part of our lives. You may exchange messages with someone throughout the week and realize that you miss having time together without interruptions, or notice how much easier it is to admit a difficult day when you do not have to make it sound entertaining. We can build on that connection by making time for each other and being clearer about the kind of company we need.",
    "Cancer season begins {{date}}, when the Sun enters Cancer. The Sun's time in Gemini may have given us a new way to understand something familiar. Cancer brings that understanding into how we care for ourselves and the people closest to us. A conversation may help you understand why a family habit developed, without making it something you have to repeat. You might keep a tradition that comforts you, adapt one to suit your life now, or begin a regular gathering with people you have chosen as family. Knowing more about where we come from can help us decide what we want to continue and what we would like to do differently.",
    "Cancer season begins {{date}}, when the Sun enters Cancer. After a month with the Sun in Gemini, the conversations we've been enjoying give us a reason to make more time for the people having them. You can exchange messages all week and still miss someone, especially when every reply happens between other obligations. Cancer season brings attention to the kind of contact that leaves you feeling cared for, not just caught up. Suggest a time to talk when neither of you has to rush somewhere else, and let the conversation include more than the version of your life you can make sound interesting. You also need relationships where you can have an ordinary, uneventful, difficult day and still be good company.",
    "Cancer season begins {{date}}, when the Sun enters Cancer. After a month with the Sun in Gemini, what we learn about our histories helps us decide what we want to continue. A conversation may explain why a family tradition matters so much, while also helping you notice how much work you've taken on to maintain it. You love seeing everyone; you don't love needing two days to prepare and another to recover. Cancer season brings attention to how the connection could continue with more care for the people making it happen. Keep what makes the gathering meaningful and discuss what could be simpler. Understanding why something matters doesn't mean every detail has to stay the same for it to keep mattering."
  ],
  "cancer-leo": [
    "Cancer season ends {{date}}, when the Sun enters Leo. After a month of paying closer attention to our needs and what we want to protect, we turn toward what we want to share. You may be ready to show work you have kept private, take credit for something you made, or say what you want without first making it easier for someone else to accept. Leo season brings attention to expression and the responses it draws. We cannot control how everyone responds, but we can decide how much authority to give that response over what we create, enjoy, or choose to share.",
    "Leo season begins {{date}}, when the Sun enters Leo. The Sun's time in Cancer can remind us which relationships allow us to relax and feel supported. In Leo, that sense of belonging can give us more confidence to contribute something of our own. You may suggest a plan you would enjoy rather than wait to hear everyone else's ideas, or invite people to celebrate an achievement you would usually mention only in passing. Letting people care about us also means letting them know what delights us. We can welcome their enthusiasm without needing everyone to share it before we allow ourselves to enjoy something.",
    "Leo season begins {{date}}, when the Sun enters Leo. The Sun's time in Cancer can help us recognize the conditions that make it easier to be ourselves. Leo builds on that recognition by bringing more of what we enjoy into what we share with others. You may notice how freely you talk about an interest with someone you trust, then hear yourself dismiss it as unimportant around people you know less well. Leo brings attention to that moment of holding back. We can let people see our enthusiasm without promising that what we love will impress them, or turning every personal interest into something we need to be exceptionally good at.",
    "Leo season begins {{date}}, when the Sun enters Leo. After a month with the Sun in Cancer, the support we receive can give us more confidence to share what makes us happy. You finally finish something you worked hard on, then leave it out when a friend checks in. Maybe you don't want to sound full of yourself, or you'd rather know they'll be impressed before you mention it. Leo season brings attention to that hesitation. Tell them what you made and why you're proud of it, without immediately explaining all the ways it could have been better. Let the people who care about you know what you're celebrating, not only what you're trying to get through.",
    "Leo season begins {{date}}, when the Sun enters Leo. After a month with the Sun in Cancer, noticing where we feel most ourselves gives us a clue about what deserves more expression. You talk freely about an interest with someone you trust, then dismiss it as silly the moment someone less familiar hears about it. The interest hasn't changed; your concern about being judged has. Leo season brings attention to what happens when you let your enthusiasm be noticed without immediately trying to make it less noticeable. Talk about what you enjoy without listing all the reasons it might not impress anyone. You don't have to turn something you love into something you're exceptionally good at before it deserves a place in your life."
  ],
  "leo-virgo": [
    "Leo season ends {{date}}, when the Sun enters Virgo. After a month of giving more attention to what we want to create and enjoy, we turn toward the daily work that supports those things. You can care deeply about a project and still struggle to make progress when every hour is booked or the plan depends on having the same energy every day. Virgo season helps us make specific changes to the routine, from removing an unnecessary step to giving a recurring task enough time. The goal is to make daily life work better, not give ourselves another standard to keep proving we can meet.",
    "Virgo season begins {{date}}, when the Sun enters Virgo. What we enjoyed creating during the Sun's time in Leo gives us something worth developing. Virgo brings attention to the skills and adjustments that help us make it closer to what we intended. You may return to a draft and see where an explanation is missing, or realize that a task would be easier with a technique you have not learned yet. We can be proud of what we made and interested in improving it. The next useful step addresses something specific, rather than making every unfinished detail a reason to question our ability.",
    "Virgo season begins {{date}}, when the Sun enters Virgo. The Sun's time in Leo can remind us how much we need activities we do for the pleasure of them. Virgo helps us arrange daily life so those activities are easier to return to. You may love having people over but dread the preparation, or want to keep making something without having to clear an entire afternoon every time. A simpler plan can preserve what we enjoy while removing work that adds little to the experience. Paying attention to the details becomes useful when it helps us do more of what matters, rather than making enjoyment depend on everything being done perfectly.",
    "Virgo season begins {{date}}, when the Sun enters Virgo. After a month with the Sun in Leo, what we've created gives us something worth developing. You open a draft, notice one weak section, and suddenly start questioning the whole idea. But a paragraph that needs work isn't evidence that you had nothing worth saying. Virgo season helps you get specific enough to improve something without turning the process into an argument against yourself. Find the missing explanation, practice the unfamiliar technique, or get feedback on the part you cannot quite resolve. Keep what is already doing its job. The point of revising is to improve the work, not keep postponing the day you let it be finished.",
    "Virgo season begins {{date}}, when the Sun enters Virgo. After a month with the Sun in Leo, the things we enjoy deserve practical support, not just good intentions. You keep planning to return to a creative project, but every attempt begins with finding the materials, clearing a surface, and remembering where you stopped. By the time you're ready, you've used much of the hour you had. Virgo season brings attention to the small changes that make returning easier. Keep what you need together, leave yourself a useful note, or simplify the preparation so it doesn't become a project of its own. The routine has done its job when you spend more time doing what you enjoy and less time getting ready to enjoy it."
  ],
  "virgo-libra": [
    "Virgo season ends {{date}}, when the Sun enters Libra. After a month of working on the routines and details that keep life functioning, we turn toward how that work is divided between people. You can have an organized schedule and paid bills while still being the person who remembers every appointment, rearranges plans, and smooths over every disagreement. Libra season brings attention to the agreements behind those habits, including the ones nobody remembers making. Cooperation means more than getting everything done; it also means noticing whose time is treated as flexible, whose needs are postponed, and what would have to change for the arrangement to be fair.",
    "Libra season begins {{date}}, when the Sun enters Libra. The Sun's time in Virgo can help us find a method that works. Libra brings that knowledge into the practical give-and-take of doing something with another person. You may be used to handling a task one way and discover that someone else can get a good result differently. Agreeing on what matters, from the deadline to the outcome, can leave both people with more freedom in how they contribute. Sharing responsibility also means allowing another person some say in the process, rather than handing over the work while keeping every decision for ourselves.",
    "Libra season begins {{date}}, when the Sun enters Libra. The Sun's time in Virgo can make the work behind an ordinary day easier to recognize. Libra brings that awareness into the arrangements we make with each other. You may agree to take on more during someone else's busy week, then need to discuss what happens when you are the one who needs help. Fairness does not always mean doing exactly the same amount at exactly the same time. It means the arrangement can respond to both people's needs, rather than turning one person's temporary generosity into a responsibility they are expected to keep indefinitely.",
    "Libra season begins {{date}}, when the Sun enters Libra. After a month with the Sun in Virgo, the methods we've developed meet another person's way of doing things. You finally hand over a task, then find yourself checking every step and correcting choices that don't affect the result. Some instructions matter; others may simply be habits you've never had to explain. Libra season brings attention to the difference between sharing responsibility and assigning someone work while keeping every decision for yourself. Agree on the outcome and what each of you needs from the other, then allow their judgment to count too. You don't have to lower the standard to stop being the only person who decides how it's met.",
    "Libra season begins {{date}}, when the Sun enters Libra. After a month with the Sun in Virgo, recognizing what keeps daily life functioning makes it easier to see how that work is shared. You took on more during someone's difficult week, but three months later you're still doing it, and revisiting the arrangement feels like letting them down. Libra season brings attention to how a generous choice becomes an expectation nobody remembers discussing. Name what you took on temporarily and what you can continue, rather than waiting until you're too resentful to talk about it calmly. Fairness doesn't require both people to do the same amount every day, but your time and energy need to matter when the arrangement is being decided."
  ],
  "libra-scorpio": [
    "Libra season ends {{date}}, when the Sun enters Scorpio. After a month of considering how we cooperate and make relationships work, we turn toward what those arrangements leave unspoken. You may agree on who pays for what and still disagree about who gets to make the decisions, or avoid discussing a change in intimacy because you are afraid of what the conversation could mean. Scorpio season brings attention to what is at stake when we depend on someone. We begin to consider not only what speaking honestly might change, but what keeping quiet is already costing us.",
    "Scorpio season begins {{date}}, when the Sun enters Scorpio. The Sun's time in Libra can help us reach agreements that respect both people's needs. Scorpio brings attention to the trust involved in living by those agreements. You may be ready to rely on someone and still hesitate to tell them what has made that difficult in the past. Explaining why a particular promise matters to you can help them understand a concern that otherwise comes out as repeated checking or reluctance to accept help. We can build on the willingness to cooperate by being more honest about what depending on each other involves.",
    "Scorpio season begins {{date}}, when the Sun enters Scorpio. The Sun's time in Libra can help us establish how we want to work together. Scorpio brings attention to what happens when living with an agreement reveals something we could not have anticipated. You may have agreed to share a project and now want a different role, yet hesitate because the other person could take that change as rejection. The practical conversation may also need to include what each person is afraid the change would mean. A connection can deepen when both people are able to say what has changed, rather than having to prove their loyalty by wanting the same arrangement forever.",
    "Scorpio season begins {{date}}, when the Sun enters Scorpio. After a month with the Sun in Libra, reaching an agreement gives us a chance to discover what relying on it feels like. You've worked out the details with someone, but you keep checking that they still intend to follow through. The plan may be clear while your fear of being let down remains unspoken. Scorpio season brings attention to what this particular promise means to you. Explain why it matters instead of hoping they'll understand from how often you check, and pay attention to what they actually do. Trust can develop through repeated follow-through; you don't have to pretend consistency is unimportant in order to seem easy to deal with.",
    "Scorpio season begins {{date}}, when the Sun enters Scorpio. After a month with the Sun in Libra, the agreements we've made bring us closer to what each person needs in order to remain invested. You agreed to share a project, but the role you took on no longer suits you, and you worry that saying so will sound like abandoning the other person. Scorpio season brings attention to the concern beneath the practical conversation. You may need to explain both what you want to change and what you still care about. Tell them which part of the work no longer fits and what you would like to contribute instead. They need a chance to respond to what you want now, not only rely on what you agreed to before."
  ],
  "scorpio-sagittarius": [
    "Scorpio season ends {{date}}, when the Sun enters Sagittarius. After a month of looking closely at what was difficult to admit or discuss, our attention begins to widen beyond the immediate situation. You may understand what happened and why it hurt, yet still be unsure how much it should shape the choices you make next. Sagittarius season helps us reconsider the conclusions we have drawn, especially when one experience has started to determine what we expect from everything else. We can take what we learned seriously and still choose a direction based on something we want to explore, not only something we hope to avoid.",
    "Sagittarius season begins {{date}}, when the Sun enters Sagittarius. Looking closely at an experience during the Sun's time in Scorpio can show us what we do not want to repeat. Sagittarius helps us consider what we would like to experience instead. You might understand why a certain kind of work frustrated you, then become curious about people who have found another way to use the same skills. Their experience can add possibilities to what you have learned from your own. We can take a difficult lesson seriously while allowing what we discover next to influence our expectations, rather than assuming the familiar outcome is the only one available.",
    "Sagittarius season begins {{date}}, when the Sun enters Sagittarius. Being honest about what matters during the Sun's time in Scorpio can change what we want from the future. A goal you once pursued for someone else's approval may no longer interest you, while a subject you used to dismiss may now seem worth studying. Sagittarius helps us explore the possibilities those discoveries create. You may seek out a teacher or spend time with people whose lives show you a way of doing things you had not considered. A new direction does not have to become a complete set of answers; it can give us something worth learning more about.",
    "Sagittarius season begins {{date}}, when the Sun enters Sagittarius. After a month with the Sun in Scorpio, knowing what we don't want to repeat gives us a starting point for considering what we want instead. You may be clear about the kind of work you never want to do again and less certain about what would interest you now. Sagittarius season widens the conversation beyond avoiding another disappointment. Talk to someone whose work makes you curious, and find out what their ordinary day involves, not just how they got there. Their experience may show you an option your own history hasn't offered yet. What disappointed you deserves to inform the next decision, not make every decision for you.",
    "Sagittarius season begins {{date}}, when the Sun enters Sagittarius. After a month with the Sun in Scorpio, being honest about what motivates us can change what we want from the future. You may have spent a long time working toward a title that no longer excites you, yet every time you consider another direction, you think about having to explain it. Sagittarius season brings attention to what interests you beyond the version of your life others have gotten used to hearing about. Learn from someone doing work you're curious about, or return to a subject you dismissed because you couldn't see where it would lead. You can take a new interest seriously without immediately turning it into a complete life plan."
  ],
  "sagittarius-capricorn": [
    "Sagittarius season ends {{date}}, when the Sun enters Capricorn. After a month of looking ahead and imagining what else might be possible, we begin to decide what we can commit to and what that commitment will require. You may care about the goal and still need to reduce its scope, agree on who will do the work, or give up another commitment to have enough time for it. Capricorn season brings attention to what we can reasonably promise and the responsibilities that follow. Revising the scope or deadline does not have to mean abandoning the ambition; it can give us a practical way to follow through.",
    "Capricorn season begins {{date}}, when the Sun enters Capricorn. The Sun's time in Sagittarius can help us imagine a future we want to move toward. Capricorn turns that direction into commitments we can plan around. You may be ready to begin a course, then need to work out which evenings are available and what support would help you finish it. Naming those requirements gives the ambition a place in your life beyond the initial excitement. We do not need to solve every later stage before beginning, but we do need a first stage that takes our existing responsibilities into account.",
    "Capricorn season begins {{date}}, when the Sun enters Capricorn. The Sun's time in Sagittarius can help us name an ambition we had not previously considered possible. Capricorn brings that ambition into the decisions we make about our time and responsibilities. You may need to tell someone that you cannot keep volunteering for every extra task because a goal of your own now needs regular attention. Following through can involve deciding what you will no longer take on, not only working harder at what you want. Protecting time for your own plans can be part of taking responsibility, rather than something you postpone until every other obligation is finished.",
    "Capricorn season begins {{date}}, when the Sun enters Capricorn. After a month with the Sun in Sagittarius, a possibility that excited us needs a practical way to begin. You find a course you want to take and can already imagine what finishing it would make possible. Now look at the evenings it requires and the responsibilities already filling them. Capricorn season helps you take the ambition seriously enough to arrange support before relying on determination alone. Work out what the first stage needs and what must change to make that stage manageable. You don't need to solve the next five years before beginning, but your plan needs to account for the person who will be doing the work, including the rest of their life.",
    "Capricorn season begins {{date}}, when the Sun enters Capricorn. After a month with the Sun in Sagittarius, imagining a future we want becomes a question of what we will protect time for now. You keep your promises to other people, then move the hours you set aside for yourself whenever someone needs something extra. Capricorn season brings attention to the decisions that determine what gets done, including what you agree to postpone. Before taking on another task, look at what you would be delaying to do it. Some responsibilities aren't optional, but not every request needs the same answer. Your ambition won't get a fair chance if working on it always counts as the least responsible use of your time."
  ],
  "capricorn-aquarius": [
    "Capricorn season ends {{date}}, when the Sun enters Aquarius. After a month of taking responsibility and working within limits, we step back to examine the rules shaping those responsibilities. You can meet every deadline and still be doing three people's jobs, or follow a process exactly and notice that it keeps creating the same problem. Aquarius season shifts our attention from how well we meet expectations to how those expectations were decided and who they work for. Comparing experiences with other people can help us see what needs to change, rather than assuming each person should find a better way to cope alone.",
    "Aquarius season begins {{date}}, when the Sun enters Aquarius. The Sun's time in Capricorn can show us what clear responsibilities and sustained effort make possible. Aquarius extends that attention to how more people can contribute to what has been built. You may have developed a process that works, then notice that everyone still has to come to you for information or permission to move forward. Sharing what you know and agreeing on who can make which decisions can help the work continue without depending on your constant availability. Taking responsibility for something can include making it possible for other people to take responsibility too.",
    "Aquarius season begins {{date}}, when the Sun enters Aquarius. What we learned about responsibility during the Sun's time in Capricorn can help us see how a shared structure affects the people using it. You may notice that the same people always contribute because meetings happen when others cannot attend, or that useful suggestions are overlooked because they come from someone new. Aquarius brings attention to whose experience is included when decisions are made. We can build on what already works by listening to people it has not worked for yet, rather than assuming that a good result for some means there is nothing more to consider.",
    "Aquarius season begins {{date}}, when the Sun enters Aquarius. After a month with the Sun in Capricorn, what we've learned through taking responsibility becomes something others can use too. You've built a process that works, but routine questions still arrive whenever you try to take time off because you're the only person who knows how everything connects. Aquarius season brings attention to how that knowledge can be shared. Explain the decisions behind the method, make the information accessible, and agree on what others can handle without checking with you. Your experience doesn't become less valuable when someone else learns from it. It can become the reason the work continues without requiring you to be available every minute.",
    "Aquarius season begins {{date}}, when the Sun enters Aquarius. After a month with the Sun in Capricorn, the structures we've built give us something to improve together. A process may be clear and organized while still making it difficult for some people to contribute. If everyone has to attend the same meeting to have a say, you may keep hearing from those with the most flexible schedules rather than those with the most useful experience. Aquarius season brings attention to that difference. Give people another way to contribute before deciding that their absence means they have nothing to add. The next improvement may come from someone your current process hasn't made it easy to hear."
  ],
  "aquarius-pisces": [
    "Aquarius season ends {{date}}, when the Sun enters Pisces. After a month of examining how things work, our attention shifts toward the feelings that an explanation alone cannot resolve. You may know exactly why a job exhausted you and still need rest, or understand why a relationship ended and still miss the person. Pisces season reminds us that understanding something is not the same as being finished with it. We may need time to rest, grieve, or express something through creative work without deciding immediately what the experience means, how to make it useful, or what should happen next.",
    "Pisces season begins {{date}}, when the Sun enters Pisces. The Sun's time in Aquarius can help us see how people's experiences are connected. Pisces brings us closer to what those experiences feel like to the people living through them. You may understand why a friend is struggling and find that the most useful thing you can do is listen before offering an explanation or a solution. They may need company while they work out what they feel, rather than another plan to follow. What we understand about the larger pattern can deepen our care for a particular person without making it our responsibility to resolve everything they are experiencing.",
    "Pisces season begins {{date}}, when the Sun enters Pisces. The Sun's time in Aquarius can help us recognize a pattern we no longer want to repeat. Pisces brings attention to what changing it feels like, including responses that do not fit neatly with the reasons behind our decision. You may understand that a role no longer suits you and still miss the belonging it gave you, or welcome a change while feeling sad about what it brings to an end. Those feelings do not have to cancel each other out. There can be time to rest, express what you miss, and let your response develop before deciding what you are ready for next.",
    "Pisces season begins {{date}}, when the Sun enters Pisces. After a month with the Sun in Aquarius, understanding the larger pattern can deepen our care for the person living through it. A friend tells you they're struggling, and you begin explaining what would help before they've finished telling you what happened. You may have useful advice, but they may need something else from you first. Pisces season brings attention to the difference between understanding someone's situation and listening to their experience of it. Find out what would help right now, rather than deciding that for them. You don't have to solve their sadness to be good company while they feel it, and they don't need to leave the conversation with another assignment.",
    "Pisces season begins {{date}}, when the Sun enters Pisces. After a month with the Sun in Aquarius, understanding why something needs to change brings us to the experience of living with that change. You leave a role that no longer fits, then miss the routine, the company, or knowing exactly where you belonged. The sadness may make you question a decision you had good reasons to make. Pisces season brings attention to the feelings that don't fit neatly into the explanation. Missing part of an experience isn't the same as wanting all of it back. Give yourself time to notice what you miss without using it to dismiss what needed to change, or expecting every feeling to agree with your decision immediately."
  ]
};

export const calendarSeasonTransitionVariantCount = 5;

export function calendarSeasonTransitionPair(fromSign: string, toSign: string) {
  return `${fromSign.toLowerCase().trim()}-${toSign.toLowerCase().trim()}`;
}

export function calendarSeasonTransitionKey(fromSign: string, toSign: string, variant = 1) {
  const from = fromSign.toLowerCase().trim();
  const to = toSign.toLowerCase().trim();
  if (!from || !to) return "";
  return variant > 1
    ? `authored/calendar-season-transition/${from}/${to}/variant-${variant}`
    : `authored/calendar-season-transition/${from}/${to}`;
}

export function calendarSeasonTransitionTitle(fromSign: string, toSign: string, variant = 1) {
  const from = fromSign.replace(/^\w/u, (letter) => letter.toUpperCase());
  const to = toSign.replace(/^\w/u, (letter) => letter.toUpperCase());
  const pair = `${from} to ${to}`;
  if (variant <= 1) return `${pair} · Ends`;
  return variant === 2 ? `${pair} · Begins` : `${pair} · Begins · ${variant - 1}`;
}

export function calendarSeasonTransitionKeys(fromSign: string, toSign: string) {
  return Array.from({ length: calendarSeasonTransitionVariantCount }, (_, index) => (
    calendarSeasonTransitionKey(fromSign, toSign, index + 1)
  )).filter(Boolean);
}

export function calendarSeasonTransitionKeyForSurface(
  fromSign: string,
  toSign: string,
  surface: "leftover" | "daily-sky",
  daysUntilSeasonEnd?: number | null
) {
  return calendarSeasonTransitionKey(
    fromSign,
    toSign,
    calendarSeasonTransitionVariantIndex({ surface, daysUntilSeasonEnd, fromSign }) + 1
  );
}

export function calendarSeasonTransitionVariantIndex(input: {
  surface: "leftover" | "daily-sky";
  daysUntilSeasonEnd?: number | null;
  fromSign?: string;
}) {
  const days = input.daysUntilSeasonEnd == null ? 0 : input.daysUntilSeasonEnd;
  if (input.surface === "daily-sky") {
    return ((days + 1) % 3 + 3) % 3;
  }
  if (days % 3 === 0) return 0;
  const pair = zodiacSignOrder.indexOf(input.fromSign?.toLowerCase().trim() as typeof zodiacSignOrder[number]);
  const begins = [1, 2, 3, 4];
  return begins[((pair < 0 ? 0 : pair) + days) % begins.length];
}

export function calendarSeasonTransitionWhen(daysUntilSeasonEnd: number | null | undefined, seasonEndDate: string) {
  if (daysUntilSeasonEnd === 1) return "in 1 day";
  if (daysUntilSeasonEnd === 2) return "in 2 days";
  if (daysUntilSeasonEnd === 3) return "in 3 days";
  return seasonEndDate.trim();
}

export function calendarSeasonTransitionDailySkySentence(
  fromSign: string,
  toSign: string,
  daysUntilSeasonEnd: number | null | undefined,
  seasonEndDate: string,
  override?: string | null
) {
  const from = fromSign.trim();
  const to = toSign.trim();
  const countdown = calendarSeasonTransitionCountdown(daysUntilSeasonEnd);
  const calendarDate = seasonEndDate.trim();
  if (!from || !to || !countdown || !calendarDate) return "";
  const raw = override?.trim() || `${from} season ends {{countdown}}, when the Sun enters ${to} on {{date}}.`;
  return raw.replaceAll("{{countdown}}", countdown).replaceAll("{{date}}", calendarDate);
}

export function fillCalendarSeasonTransitionDate(body: string, date: string) {
  const trimmed = body.trim();
  const when = date.trim();
  if (!trimmed || !when) return "";
  if (trimmed.includes("{{date}}")) return trimmed.replaceAll("{{date}}", when);
  return trimmed;
}

export function calendarSeasonTransitionForPair(
  fromSign: string,
  toSign: string,
  date: string,
  override?: string | null,
  variantIndex = 0
) {
  const pool = calendarSeasonTransitions[calendarSeasonTransitionPair(fromSign, toSign)] ?? [];
  const raw = override?.trim() || pool[variantIndex] || pool[0] || "";
  return fillCalendarSeasonTransitionDate(raw, date);
}

export function calendarSeasonTransitionForSurface(input: {
  fromSign: string;
  toSign: string;
  date: string;
  surface: "leftover" | "daily-sky";
  daysUntilSeasonEnd?: number | null;
  override?: string | null;
}) {
  const variantIndex = calendarSeasonTransitionVariantIndex({
    surface: input.surface,
    daysUntilSeasonEnd: input.daysUntilSeasonEnd,
    fromSign: input.fromSign
  });
  return calendarSeasonTransitionForPair(
    input.fromSign,
    input.toSign,
    input.date,
    input.override,
    variantIndex
  );
}

